### ISSUE TITLE
Add ABPVN (Adblock Plus Vietnamese List)

### ISSUE THREAD

**Issue by bershan2** [collinbarrett/FilterLists#101]
I noticed you don't have ABPVN (Adblock Plus Vietnamese List) in the table, hosted on <https://abpvn.com>. Earlier I had some (baseless, Google Translate-inspired) [suspicions](https://github.com/gorhill/uBlock/pull/2600#issuecomment-309343621), that were [debunked](https://github.com/gorhill/uBlock/pull/2600#issuecomment-309378108) later. I apologize for that.

The information on the website is scarce (it contains merely landing page and installation instructions), but I hope this is sufficient for both evaluating this list and adding it to the table if it is good:
```
{
  "descr": "The ABP advertising filter is built with the mission of improving the browsing experience for the vietnamese users. ABPVN may not help block all ads, but ABPVN will minimize the appearance of ads on most websites in Vietnam.",
  "descrSourceUrl": "https://abpvn.com",
  "donateUrl": "https://abpvn.com/napthe",
  "email": "support@abpvn.com",
  "forumUrl": "http://www.vn-zoom.com/f77/abp-bo-loc-quang-cao-cho-nguoi-viet-2856275.html",
  "homeUrl": "https://abpvn.com",
  "issuesUrl": "https://www.facebook.com/notes/bộ-lọc-quảng-cáo-cho-người-việt/kiếm-chút-tiền-lúc-rảnh-rỗi/1663248030564655",
  "list": "ABPVN List [linkneverdie.com]",
  "tagLang": "vi",
  "viewUrl": "https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt"
}
```

Note the following:
* `descr` was translated with Google Translate and slightly edited to fix grammar.
* `donateUrl` is a "paid VIP support page" and does **NOT** support HTTPS (defaults to HTTP). However, payment method does not require HTTPS:
   > [Users] donate to the list maintainer through scratch cards for adding credits to [author's] mobile plan.
* `forumUrl` is taken from the comments in the beginning of the list, no idea how popular it is.
* `issuesUrl` taken from free support link, but leads to a Facebook note describing
   > donation by using the referral code in the app from the note".

   It used to be `https://www.facebook.com/abpvn.org` a month ago.
* `viewUrl` is taken from GitHub, but their ["subscribe" web-page](https://abpvn.com/get) (does not support HTTPS) generates a random link for every user... Strange... Is that an active subscriber count?... For now, let's use GitHub link.

All quotes are by @Connor37 from [the uBlock Origin pull request #2600 discussion](https://github.com/gorhill/uBlock/pull/2600).

**Comment by collinbarrett** [comment]
Hey, thanks for the detailed information! I'll look into adding it when I get a chance.

**Comment by bershan2** [comment]
@collinbarrett The suspicions I had about this list turned out to be false (debunked on linked uBlock Origin issue), I updated the above report.

**Comment by collinbarrett** [comment]
Added. Thanks, @bershan2 !
