### ISSUE TITLE
add support for parsing AdGuard syntax platform "hints" from metadata

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#103]
Ensure all variants of Adguard lists are added.

Per [here](https://github.com/AdguardTeam/AdguardFilters/issues/3708#issuecomment-303155314).

**Comment by TerrakionSmash** [comment]
I think the easiest way to remedy this is to have the uBlock Origin version of Adguard English instead. AdBlock Plus doesn't support them anyway and Adguard English for Adguard is redundant.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by collinbarrett** [comment]
I'm still a bit confused on how AdGuard breaks out platform and extension specific lists. @ameshkov , can you shed any light on this? We currently have all of the basic lists outlined [here](https://kb.adguard.com/en/general/adguard-ad-filters), but are there platform-specific lists that we should index as well?

**Comment by ameshkov** [comment]
Hi! I guess we need to add an explanation about platform-specific filters there:)

Filters maintainers can use a special "hints" to control rules on a per-platform basis:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#platform_not_platform

I suppose that it'd be better to the `ublock` version of them. Meanwhile, we'll make it compatible with ABP: https://github.com/AdguardTeam/FiltersCompiler/issues/10

**Comment by ameshkov** [comment]
A bit more info on the filters metadata:

`"homeUrl": "https://github.com/AdguardTeam/AdguardFilters"` 
`"policyUrl"`: "https://kb.adguard.com/en/general/adguard-filter-policy"

**Comment by collinbarrett** [comment]
hmm, ok, will keep this open to try to index all of the platform-specific variants at some point. that would take some work, though, so might not get to it for awhile.

thanks!

**Comment by collinbarrett** [comment]
Closing into parent issue #202
