### ISSUE TITLE
RFI: Ebates affiliates exclusion list

### ISSUE THREAD

**Issue by TPS** [collinbarrett/FilterLists#104]
Similar to #35 & from https://www.ebates.com/help/troubleshooting.htm#abp, how about Ebates' exclusion list @ `abp:subscribe?location=https%3A%2F%2Fwww.ebates.com%2Fwhitelist%2Febates-cash-back-shopping.txt&title=Ebates%20Cash%20Back%20Shopping`?

**Comment by collinbarrett** [comment]
I've been really busy lately. If you can create a pull request adding your list to the [list data file](https://github.com/collinbarrett/FilterLists/blob/master/data/lists.json), I can implement quicker. Thanks!
