### ISSUE TITLE
Add infinitytec host lists

### ISSUE THREAD

**Issue by infinitytec** [collinbarrett/FilterLists#1049]
I'd like to submit some hosts files to the list.

All these lists are at https://github.com/infinitytec/blocklists

They are all released under the MIT license. 

First one: Ads and tracking.
Github: https://github.com/infinitytec/blocklists/blob/master/ads-and-trackers.txt

Hosts format: https://github.com/infinitytec/blocklists/raw/master/ads-and-trackers.txt

Second one: scams and phishing.
Github: https://github.com/infinitytec/blocklists/blob/master/scams-and-phishing.txt

Hosts format: https://github.com/infinitytec/blocklists/raw/master/scams-and-phishing.txt

If you have any questions, let me know!

**Comment by DandelionSprout** [comment]
Should be fixed when #1077 is commited.

**Comment by infinitytec** [comment]
Awesome! Thanks!
