### ISSUE TITLE
Add Better.fyiTrackersBlocklist

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#105]
Via @anarki999:
Dear Sir/Madam,

It would be much appreciated if you can add my list to the website too =P. I still updating the list. I am currently turning the tracker list from https://better.fyi/trackers/alexa-top-500-news/ into a subscription list for Adblock & uBlock Origin.

Here is the link of my link:
https://raw.githubusercontent.com/anarki999/Adblock-List-Archive/master/Better.fyiTrackersBlocklist.txt

And my Github homepage stored with some un-maintenance list before it was down.
https://github.com/anarki999/Adblock-List-Archive

Kind regards,
Cyrus

**Comment by Atavic** [comment]
That's a great idea!

**Comment by anarki999** [comment]
Thank you very much... I also added some anti-adblocking rules that the akk list doesn't have... to make even the testing site of Adblock Plus can't even detect it (a successful anti-adblocking) =P You guys can take a rough look =)

**Comment by collinbarrett** [comment]
I've been really busy lately. If you can create a pull request adding your list to the [list data file](https://github.com/collinbarrett/FilterLists/blob/master/data/lists.json), I can implement quicker. Thanks!

**Comment by anarki999** [comment]
I have made a pull request for it =P. Please help to double-check the language =P. Many thanks.
https://github.com/collinbarrett/FilterLists/pull/106

**Comment by Atavic** [comment]
Check: [fitlers](https://github.com/collinbarrett/FilterLists/pull/106/commits/ffb32f2a50e0c068926d74d184127eedc3fef9f2#diff-eca2fc2285b36af2101529602b746386R2)
