### ISSUE TITLE
Unblock materialdesignicons.com

### ISSUE THREAD

**Issue by jluisjuncal** [collinbarrett/FilterLists#1060]
In *1Hosts* file, there is an entry 
0.0.0.0 cdn.materialdesignicons.com  that needs to be unblocked.
There could be problems with pages that rely in the framework react and others

**Comment by gwarser** [comment]
This project/issue tracker is not affiliated with 1Hosts.

You should ask 1Host support for this:

```
# Title: 1Hosts (Complete)
# home: 1hos.cf/complete
...
# Please report any issues related to this file:
# XDA: go.energized.pro/badmojr
# e-mail: badmojr@gmail.com
# Telegram: t.me/badmojr
```

**Comment by collinbarrett** [comment]
Correct, FilterLists just helps people find lists to subscribe to. You'll need to contact the maintainer of that list to request getting a list removed.
