### ISSUE TITLE
1Hosts: update

### ISSUE THREAD

**Issue by badmojr** [collinbarrett/FilterLists#1074]
Hello! My apologies for the inconvenience.

1Hosts (Pro):-
https://1hos.cf/Pro/hosts.txt
https://1hos.cf/Pro/domains.txt
https://1hos.cf/Pro/adblock.txt

1Hosts (Complete):-
https://1hos.cf/complete/hosts.txt
https://1hos.cf/complete/domains.txt
https://1hos.cf/complete/adblock.txt

1Hosts (mini):
https://1hos.cf/mini/hosts.txt
https://1hos.cf/mini/domains.txt
https://1hos.cf/mini/adblock.txt

issues: https://github.com/badmojr/1Hosts/issues

**Comment by DandelionSprout** [comment]
There's a significant backlog of other things that have to be added or updated (#851), so it could take up to two weeks at worst before the changes will be implemented, unless you want to attempt a pull request of your own (I could help and guide you through it if you want me to).

**Comment by badmojr** [comment]
I'm not entitled so it's fine with me. :)

**Comment by collinbarrett** [comment]
Closed by #1124 .
