### ISSUE TITLE
FilterLists.com is currently broken

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#1076]
Currently it's a blank page with the following console log errors. I figured you (Collin) would want to know about it in a hurry.
![image](https://user-images.githubusercontent.com/22780683/67088932-af559f00-f1a6-11e9-9a21-2b569f6f518f.png)

**Comment by collinbarrett** [comment]
On vacation. Dependabot must've broken something. I may try to fix from my phone if I have time, but I may not be able to fix until Monday.

**Comment by thanuj10** [comment]
Can confirm. Broken on both Firefox and Chrome.

**Comment by collinbarrett** [comment]
Seems to be auto-resolved by [patching antd](https://github.com/collinbarrett/FilterLists/commit/9391f86988652f26cc4470696ff639181100a8f2).

Bug: https://github.com/ant-design/ant-design/issues/19274

If I go offline for more than a day or so in the future, I'll try to remember to disable Dependabot's auto-merge feature to prevent critical issues like this again.

**Comment by felix-22** [comment]
It's down again, both on Firefox and Opera.
