### ISSUE TITLE
I think there are 2 projects attempting to maintain 2 lists for EU cookie warnings

### ISSUE THREAD

**Issue by daf121** [collinbarrett/FilterLists#109]
his list: https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

from : https://www.kiboke-studio.hr/i-dont-care-about-cookies/

Maybe you guys should join forces to maintain 1 list only?

**Comment by collinbarrett** [comment]
Thanks, @daf121 .

FilterLists aims to simply be an index of all known lists. I would recommend contacting the maintainers of these two lists directly to see if they are interested in joining forces.
