### ISSUE TITLE
TLS Issue on Some Browsers

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#110]
I tried opening the security of my browsers, but I can't see the lists. Site lacks them and all I get below the top section is:

>Showing 1 to 302 of 302 entries
>A project by Collin M. Barrett. © 2017

**Comment by collinbarrett** [comment]
The site loads for me on Windows in both my heavily locked down Firefox as well as default Chrome. What browser are you using?

**Comment by Atavic** [comment]
Firefox ESR 52.0, Palemoon and k-meleon have the same issue.

Chrome tells me:
>This site can’t provide a secure connection
filterlists.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

>The client and server don't support a common SSL protocol version or cipher suite. This is likely to be caused when the server needs RC4, which is no longer considered secure.

**Comment by collinbarrett** [comment]
Hmm, interesting. The site is hosted behind CloudFlare, so it uses whatever their TLS is configured to support. Renaming this issue to be TLS-specific, and I will try to look into it when I have time. Must be related to TLS configs accepted by those browsers or something?

**Comment by Atavic** [comment]
I have disabled RC4 on some browsers. But not on Chrome that's my last resort browser.
I did this [test](https://www.ssllabs.com/ssltest/index.html) and the server is ok.

**Comment by collinbarrett** [comment]
Hmm, ok, yeah, I ran ssllabs as well. I think the site has fairly good support for modern protocols. Since I decided to use CloudFlare, I do not have much control over the last mile configuration, anyway.

Closing for now, but feel free to re-open if you find it is a significant issue.

**Comment by bershan2** [comment]
@collinbarrett There is some unprocessed PHP inside of <noscript>, because of the not closed `else` (closing bracket is in a different PHP tag).

**Comment by Atavic** [comment]
A huge workload, info bar let me know what was going on and... it is back. :feelsgood:

**Comment by collinbarrett** [comment]
Hi @Atavic . I'm sorry, I do not understand your last comment. Are you still experiencing this issue? Or is it working for you now? Thanks.

**Comment by Atavic** [comment]
All ok. You earned a star for this.

**Comment by Atavic** [comment]
:+1: All loads fine.

**Comment by collinbarrett** [comment]
Great! Glad to hear it!
