### ISSUE TITLE
Gridview of Lists Broken [High Priority]

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#111]
Via a couple contact form submissions, it has been reported that the grid view of the lists on the home page is broken. I can reproduce. I put up a notice for now while I investigate. I suspect it may have to do with a WordPress plugin auto-update.

**Comment by collinbarrett** [comment]
Possibly related to this: https://github.com/collinbarrett/FilterLists/issues/110#issuecomment-325104273

**Comment by collinbarrett** [comment]
I suspect it has to do with an auto-update that occurred on the wpDataTables plugin to v2 of the product. My support with them has ended, and I cannot spend the money to buy a new support license with them atm. I am going to try to roll back to a pre-2.0 version unless any other front-end devs spot the issue.

@bershan2, is it possibly the php issue you were talking about in #110 ? Any ideas on how to fix, or can you provide further context around the issue?

**Comment by gomoku** [comment]
I just've visited right now https://filterlists.com/ on FF 55.0.3 and got Bad Gateway error, I've reloaded the website several times, and still was gettting the error, but now the error is gone.

**Comment by collinbarrett** [comment]
Thanks, @gomoku I guess it was a temporary error. I am also on the latest FF and it is loading for me "fine" (less the grid view on the home page which is the whole point of the site :) now.

I will try to get the site fixed ASAP by either rolling back the plugin or restoring a recent backup. It's just been a busy week for me, and I haven't had the chance. Thanks, all, for your patience.

**Comment by collinbarrett** [comment]
Resolved by rolling back version of wpdatatables plugin. Disabled auto-update for this plugin.
