### ISSUE TITLE
viewUrl links to HTML page

### ISSUE THREAD

**Issue by gwarser** [collinbarrett/FilterLists#1114]
- [1893](https://github.com/collinbarrett/FilterLists/blob/abf2036729c5513853d78f42dbf9949f5a2858b3/data/FilterList.json#L20096) (GitHub page)
- [1706](https://github.com/collinbarrett/FilterLists/blob/abf2036729c5513853d78f42dbf9949f5a2858b3/data/FilterList.json#L17882) (404)

**Comment by collinbarrett** [comment]
Closed by #1124 .
