### ISSUE TITLE
A change in 2 .onion mirrors.

### ISSUE THREAD

**Issue by mozdevcontrib** [collinbarrett/FilterLists#1123]
I've chosen to self-host the onion "mirrors" of DomainVoider and iVOID instead of relying on 0xacab.org's onion site. That said, here are the links to each:
- **http://ip5n52t35zg7oam3ddvkckwrer2lehllk4pvkcfgbc6gqtfejxyrpfqd.onion/iVOID.hosts**
- **http://ip5n52t35zg7oam3ddvkckwrer2lehllk4pvkcfgbc6gqtfejxyrpfqd.onion/DomainVoider.txt**

This will allow me to keep them up to date and have a far better uptime. Note: every so often I'll be generating a new address; when I do I'll be sure to update the links either here or via email. 

Thank-you.

**Comment by collinbarrett** [comment]
Closed by #1124 .
