### ISSUE TITLE
The changes from #1124 don't seem to have gone live yet

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#1129]
This is most visible in how the ABP versions of *1hosts* aren't shown on the landing page, neither are any of the other new lists.

Is there any particular reason for it?

**Comment by collinbarrett** [comment]
The build is throwing a stackoverflow. Not sure why. I'll investigate when I have a chance.

https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=1930
