### ISSUE TITLE
add Adblock Turkish list

### ISSUE THREAD

**Issue by xorcan** [collinbarrett/FilterLists#1139]
before i made adblock list for Turkish websites [_at here_](https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt)

to-do 1: now two lists are available:
1. elemental list:  
title:  "**xorcan Türk element-ad-list​​ (Turkish)**"
link: "**https://raw.githubusercontent.com/xorcan/hosts/master/xelement.txt**"
2. harmful ips.:  
title: "**xorcan Türk harmful ip-list​​ (Turkish)**"
link: "**https://raw.githubusercontent.com/xorcan/hosts/master/xips.txt**"

you can add [filterlists.com](https://filterlists.com/)

to-do 2: edit added filter title:
edit [_this_](https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt) filterlist name from "xorcan türk ad-list" to "xorcan Türk ad-list (Turkish)" at you website.

THANK YOU

**Comment by DandelionSprout** [comment]
I believe this has been done in #1188, which I forgot to point out until now...
