### ISSUE TITLE
add upstream lists to Disconnect Malvertising Filter List

### ISSUE THREAD

**Issue by DJCrashdummy** [collinbarrett/FilterLists#116]
i'm not sure if it is an issue or not, but...
although i can't find something that it is declared somewhere, but i'm pretty sure _Disconnect Advertising Filter List_, _Disconnect Malware Filter List_ and _Disconnect Tracking Filter List_ are included into _Disconnect Malvertising Filter List_ and maybe it can/should be mentioned somewhere.

btw: the VIEW-buttons of _Disconnect Malware Filter List_ and _Disconnect Malvertising Filter List_ don't view the list, but starts a download.

**Comment by Atavic** [comment]
uBlockOrigin is considering to remove it, see: https://github.com/gorhill/uBlock/issues/3147#issuecomment-338295016

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by DJCrashdummy** [comment]
unfortunately it is still not mentioned anywhere, that several list are included into another one (and therefore not additionally needed)...

**Comment by collinbarrett** [comment]
@DJCrashdummy Yeah, it's in the dataset, but the UI of the app does not support it yet. That is certainly on the fairly near-term roadmap. I just realized I didn't have an issue open for that, though, so opened #287 . Hopefully we'll have time to get that in soon.

Thanks.
