### ISSUE TITLE
AdGuard Filter Subscriptions

### ISSUE THREAD

**Issue by Nzzyme** [collinbarrett/FilterLists#1192]
I only see 3 English AdGuard Filter subscriptions:

AdGuard Base Filter
AdGuard Base Filter without EasyList
Adguard English Filter (Domains)

Can you add all the remaining ones?
https://kb.adguard.com/en/general/adguard-ad-filters

**Comment by DandelionSprout** [comment]
They're all on the site already. It's just that they aren't marked by us as English-language-specific. 
![image](https://user-images.githubusercontent.com/22780683/69868161-3cf9d380-12a9-11ea-92de-5472163da34b.png)

**Comment by Nzzyme** [comment]
Ok, thanks. You may want to tag them.
