### ISSUE TITLE
update mirror links for ABPindo

### ISSUE THREAD

**Issue by gmarcher** [collinbarrett/FilterLists#1231]
Please add ABPindo mirror https://gitlab.com/ABPindo/indonesianadblockrules

`[ABPindo](https://subscribe.adblockplus.org/?location=https://gitlab.com/ABPindo/indonesianadblockrules/raw/master/subscriptions/abpindo.txt&title=ABPindo)`

**Comment by bogachenko** [comment]
@collinbarrett ABPindo already has 2 mirrors. Is it possible to add 3?

**Comment by collinbarrett** [comment]
Currently, no, only 2 mirrors are supported.

We could potentially replace:

`"viewUrlMirror1": "https://raw.githubusercontent.com/heradhis/indonesianadblockrules/master/subscriptions/abpindo.txt",`

since the `viewUrl` is at the same domain. mirrors are better used at different domains, maybe.

**Comment by collinbarrett** [comment]
I don't plan to add support for a 3rd mirror link at this time. Let me know if we should replace any of the existing 3 (primary or mirrors) with this GitLab one. [Link](https://github.com/collinbarrett/FilterLists/blob/87f1bb25e3bf6f47f4decf0fe9b2e82505f0655b/data/FilterList.json#L2066) to current URLs in data file.

**Comment by collinbarrett** [comment]
added as another mirror in #1943
