### ISSUE TITLE
Add "Hexxium Creations Threat List"

### ISSUE THREAD

**Issue by Hexxium** [collinbarrett/FilterLists#124]
We (Hexxium Creations) maintain a community driven list to protect users from spam, scams, malware, (basically anything malicious). NoTrack (https://github.com/quidsup/notrack) already includes our list in their application.

Link to our list (in text form) https://hexxiumcreations.github.io/threat-list/hexxiumthreatlist.txt
Link to our github where we maintain the list: https://github.com/HexxiumCreations/threat-list

Link to our website: https://www.hexxiumcreations.com/ -- this page specifically for this project https://www.hexxiumcreations.com/projects/malicious-domain-blocking/

**Comment by elypter** [comment]
what is wrong with the list?

**Comment by collinbarrett** [comment]
Nothing, I added it. See the link to the commit above (https://github.com/collinbarrett/FilterLists/commit/34cb12b635c9ba4f06d8c350396457b47d3f9d25). It may take up to 24 hours to show up on filterlists.com, though, due to caching.

**Comment by elypter** [comment]
now i see it. must have overlooked it
