### ISSUE TITLE
Updated .onion addresses

### ISSUE THREAD

**Issue by mozdevcontrib** [collinbarrett/FilterLists#1263]
http://w2caclgy62idhzyut23ucimqw5tsmfbl4b2iyjzpvngatast2fiqxbyd.onion/ivoid/iVOID.hosts
 `&`
http://w2caclgy62idhzyut23ucimqw5tsmfbl4b2iyjzpvngatast2fiqxbyd.onion/domainvoider/DomainVoider.txt

Thank-you. 🙂

**Comment by mozdevcontrib** [comment]
✌🏼

~intr0 Ⓐ Sent from ProtonMail Professional

**Comment by collinbarrett** [comment]
This might not show up on the live site for a bit due to [this](https://github.com/collinbarrett/FilterLists/issues/1173), unfortunately. I'll try to get that resolved ASAP.

**Comment by mozdevcontrib** [comment]
It's fine and most understandable, Collin. Thank-you.

~intr0 Ⓐ Sent from ProtonMail Professional
