### ISSUE TITLE
update ABP Anti-Circumvention Filter Lists to be only supported by ABP software

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#1308]
per https://github.com/uBlockOrigin/uBlock-issues/issues/857

**Comment by DandelionSprout** [comment]
I can *somewhat* agree to their notion of such. And it should be far from impossible to create a new `ABP Advanced` syntax to cover such things as `:-abp-properties` and `#$#abort-on-property-read`.

I do however disagree with the uBO's team's *reason* for such. Even if it allegedly screws up uBO big time⁽¹⁾, there's still some 50~60% worth of entries that are technically supported by it.

⁽¹⁾ = I've used that list for some 5 months now in Nano without visible problems, although I've visited virtually none of the sites covered by that list in that timespan.
