### ISSUE TITLE
1hos.cf is dead

### ISSUE THREAD

**Issue by CaptainFrosty** [collinbarrett/FilterLists#1334]
Needs to be removed.

**Comment by kowith337** [comment]
Agree, the site is dead and somewhat flagged by uBO badware risks.

However, I think I've seen GitHub repo in the past issue and not yet implement to change or add mirror, nevermind, here's the repo of [1Hosts](https://github.com/badmojr/1Hosts), hope this help.

**Comment by DandelionSprout** [comment]
This was technically fixed in https://github.com/collinbarrett/FilterLists/pull/1296... which still hasn't gone live due to #1173, which still hasn't been fixed due to reasons that are beyond my understanding.

**Comment by collinbarrett** [comment]
Thanks, @DandelionSprout .

Yes, data updates are not being updated on the live site at the moment as @DandelionSprout said. This is top priority for me to fix when I can find the time. Once that's fixed, 1hos will be covered.
