### ISSUE TITLE
Add J Extension Filter

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#1396]
Received via email:

> Howdy,admin.Im a visitor.
> 
> I want to tell u guy a little info about ur site:filterlists.com.It is that I have found a good filter but lack in the site.
> 
> URL:https://github.com/nanj-adguard2/nanj-kakuchou-filter
> 
> Instruction:Its a additional filter to the Japanese Nanj Kaishuu Filter(https://filterlists.com/lists/nanj-kaishuu-filter) as to enhance the former,It must be combined to use with any base filter just like AdGuard base filter or 280 Blocker filter for japanese site.
> 
> Could u add it to list for us?Anyway,say thanks to u and ur site,appreciate indeed!

**Comment by DandelionSprout** [comment]
The three Nanj Kakuchou lists are already on FilterLists.com, and I think they've been there for longer than the Nanj Kaishuu lists have.

**Comment by collinbarrett** [comment]
Right, sorry, I didn't have time to check earlier when I opened this issue. Yeah, I think this is the one they were talking about:

https://filterlists.com/lists/nanj-kakuchou-filter-supplement-rules
