### ISSUE TITLE
Change in Subscription URL FOR "AdditionalFiltersCN"

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1399]
https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/all.txt

has been changed to

https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt

**Comment by DandelionSprout** [comment]
This has been added this site's data to-do list at https://github.com/collinbarrett/FilterLists/issues/851, but I've had too little time to fix this in the past week, unfortunately.
