### ISSUE TITLE
add lists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#1400]
- https://github.com/loveqqzj/AdGuard
 - https://gitee.com/halflife/list/raw/master/ad.txt
 - https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt

**Comment by collinbarrett** [comment]
Submitter checked and said that this one is a duplicate:
https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt

The other two might be new.

**Comment by collinbarrett** [comment]
- https://gitee.com/banbendalao/adguard
- https://gitee.com/anye1998/Adguard-List-of-personal-rules

**Comment by DandelionSprout** [comment]
I added https://raw.githubusercontent.com/loveqqzj/AdGuard/master/Mobile.txt; and two lists from https://gitee.com/banbendalao/adguard.

https://gitee.com/halflife/list/raw/master/ad.txt seemed to me at first like a plain old compilation list, so I skipped it for now. Probably next time I make a pull.

https://gitee.com/anye1998/Adguard-List-of-personal-rules was stated quite firmly to be for personal use only, or at least that's what its metadata claimed.

**Comment by noirblack666** [comment]
I'm the one who post these thing to Mr Collin.Here I will make some explanation.

 @DandelionSprout 

> I added https://raw.githubusercontent.com/loveqqzj/AdGuard/master/Mobile.txt; and two lists from https://gitee.com/banbendalao/adguard.
 
Thx.A little suggestion,Could u append a "zh" language tag to them?All these four are for chinese sites. 


> https://gitee.com/halflife/list/raw/master/ad.txt seemed to me at first like a plain old compilation list, so I skipped it for now, and I only realised it wasn't as I was writing this comment. Probably better luck next time I make a pull.

Yup,ur right.This file wasn't only a composition of some well-known rules but also contains some additional rules that the author made for some certain sites.


> https://gitee.com/anye1998/Adguard-List-of-personal-rules was stated quite firmly to be for personal use only, or at least that's what its metadata claimed.

IMHO,it's not a problem.At first,I must mention I'm acquaint with Chinese and Chinese culture.What the author stated about his matter was just an account,just like a Disclaimer.**It just mean:Why I created this matter was just for my ease and convience**.It's neither a license agreement nor a prohibition or limitation.Plz take a glance at the **Comments** section below that page,the conversation has hinted that it can be use freely by anyone.

Of course,As a matter of opinion,I just make my own stance about it.How to treat it depends ur wisdom.Respect.

________________________________________________________________________________________________

At last,Express my huge gratitude to all ur contributors!Really awesome ur project!Thumbs up:+1:

**Comment by collinbarrett** [comment]
Closed by #1428
