### ISSUE TITLE
@collin I thought you might find this interesting

### ISSUE THREAD

**Issue by jawz101** [collinbarrett/FilterLists#1408]
I'm the same jawz101 that commented on your 3rd party font blog post a few years ago.  Anyways, I've been experimenting w/ blocking 1st party wordpress plugins as well.

Just wanted to see what you thought.

https://github.com/jawz101/ublockOrigin_wordpressWhitelist

**Comment by collinbarrett** [comment]
Interesting. Very cool. I suspect it will require a fair bit of work to whitelist resources that break the site. Not sure if maybe blacklisting known privacy-invasive resources might be a better approach? Unless your focus is just pure speed, than your approach makes sense.

Cool, once it's stable, happy to list it on FilterLists. Just let us know.
