### ISSUE TITLE
Rename filter list 

### ISSUE THREAD

**Issue by 3xploiton3** [collinbarrett/FilterLists#1417]
https://filters.adtidy.org/extension/chromium/filters/14.txt

Should be
https://filters.adtidy.org/extension/chromium/filters/AdGuard_Annoyances_Filter.txt

Look easy to read

**Comment by DandelionSprout** [comment]
The latter link leads to a 404 page on my end, and AdGuard has a tendency to stamp most or almost all of their link URLs with mere numbers (e.g. [AdGuard Base Filter](https://filters.adtidy.org/extension/chromium/filters/2.txt)).

**Comment by collinbarrett** [comment]
Confirmed. @3xploiton3 can you verify that second link is what you meant? It's 404-ing.

**Comment by 3xploiton3** [comment]
Sorry i mean rename file link,

**Comment by collinbarrett** [comment]
Sorry, I'm not understanding.

[Here](https://github.com/collinbarrett/FilterLists/blob/524cc1b92413b3ae231dba42d28e229c05d69561/data/FilterList.json#L1793) is what we currently have for this list.

The [second URL](https://filters.adtidy.org/extension/chromium/filters/AdGuard_Annoyances_Filter.txt) you shared returns 404.

What change are your suggesting?

**Comment by 3xploiton3** [comment]
sorry my english is bad, i mean can you change url filter name?  use the name according to each filter title

Forget this issue,
Because url from author 

I expect from filterlists.com
