### ISSUE TITLE
Maintenance of "ChinaList 2.0" List May Come to an End

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1419]
see:
http://tools.yiclear.com/ChinaList2.0.txt

Possible Reason:

https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.huorong.cn%2Finfo%2F1582284212427.html

**Comment by DandelionSprout** [comment]
The fact that it used fraudulent redirection entries, even if `$reload` was most likely only ever supported by Ad Cleaner, is indeed a pretty serious thing to be caught red-handed. I'll try to make sure that it'll be removed from FilterLists.com inside of a week.
