### ISSUE TITLE
Software icon cells are not wide enough

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#1420]
Essentially, some icons are cut off from view due to the Software column not being wide enough: 
![image](https://user-images.githubusercontent.com/22780683/75551000-74f0ee00-5a33-11ea-8bd3-2fd7c0eb4e1b.png)

For "Domains", it's the uBlock Origin and uMatrix icons that are cut off. For "Hosts (localhost IPv4)", it's the uMatrix icon.

I recommend making the software column 25~30px wider as it currently stands. Every one of the softwares listed for "Domains" are still actively maintained, so none could be plausibly removed from FilterLists entirely.

https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Web/ClientApp/site.css, as mentioned in https://github.com/collinbarrett/FilterLists/issues/743, no longer exists, so I don't seem to able to apply this fix myself.

**Comment by collinbarrett** [comment]
Gotchya. I think [this](https://github.com/collinbarrett/FilterLists/blob/46ce6adab56130b7814602e23d91d1d4172c7ccf/web/src/components/listsTable/ListsTable.tsx#L148) is the line to tweak.
