### ISSUE TITLE
CJX's Annoyance List & CJX's uBlock list

### ISSUE THREAD

**Issue by cjx82630** [collinbarrett/FilterLists#1424]
* CJX's Annoyance List (Already in https://filterlists.com/)  
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

* CJX's Annoyance List (An alternate address for Chinese users who cannot reach GitHub)
https://gitee.com/cjx82630/cjxlist/raw/master/cjx-annoyance.txt

*  CJX's uBlock list (only for ublock origin)
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt

*  CJX's uBlock list (only for ublock origin, An alternate address for Chinese users who cannot reach GitHub)
https://gitee.com/cjx82630/cjxlist/raw/master/cjx-ublock.txt

**Comment by collinbarrett** [comment]
Closed by #1428
