### ISSUE TITLE
Subscription URLs Changed for "Small but effective adblockplus format blocklist based on the (annal) W3tech and Cookiebot surveys" List

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1435]
Top 200:

https://github.com/Kees1958/WS3_annual_most_used_survey_blocklist/raw/master/Top200

Top 500:

https://github.com/Kees1958/WS3_annual_most_used_survey_blocklist/raw/master/Top500

**Comment by DandelionSprout** [comment]
Thanks for the heads-up. I chose to update the existing link to use the Top500 version. I chose to skip the Top200 version for now, as I don't really believe it'd serve any unique niches of its own that the Top500 version wouldn't do better.
