### ISSUE TITLE
differentiate between adguard base filter variants

### ISSUE THREAD

**Issue by 3xploiton3** [collinbarrett/FilterLists#1442]
https://filterlists.com/lists/adguard-base-filter
https://filterlists.com/lists/adguard-base-filter-optimized

what different?
they have same description

**Comment by DandelionSprout** [comment]
The official difference, is that entries that are preceded by `!+ NOT_OPTIMIZED` in the regular version, are not included in the Optimized version.

I can also that whitespaces and most source-context comments are removed in Optimized as well, resulting in a filesize of ~40% of that of the regular version.

**Comment by collinbarrett** [comment]
Thanks, @DandelionSprout . Worth it to update the description(s)? Or, nah?

**Comment by DandelionSprout** [comment]
I'm not 100% certain at the top of my head. I'll need to think about it for some hours/days.

**Comment by DandelionSprout** [comment]
After a significant amount of Googling, I've found https://adguard.com/en/blog/adguard-browser-extension-2-1.html; which claims that the optimized filters [were/are] based on AdGuard telemetry that aimed to figure out which entries that were frequently applied, and to a smaller degree excluding entries with `!+ NOT_OPTIMIZED` above them.

**Comment by DandelionSprout** [comment]
Meshkov confirmed on the new Slack listmaker server that all four of the following factors behind the optimising were officially intended:

* Being light on memory.
* Only applying entries that AdGuard's opt-in telemetry shows to be frequently applied.
* Getting under iOS and Safari ≥12's 50,000-entry limit.
* Simply just removing comments and info links.

So I'll hereby add it to [my(/our?) to-do list](https://github.com/collinbarrett/FilterLists/issues/851).
