### ISSUE TITLE
Closed Issue #1430 is Unresolved

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1448]
https://github.com/collinbarrett/FilterLists/issues/1430

Sorry to bother again. But...

Subscription URL on website still points to 

https://gitee.com/anye1998/Adguard-List-of-personal-rules/blob/master/List-of-personal-rules.txt

not

https://gitee.com/anye1998/Adguard-List-of-personal-rules/raw/master/List-of-personal-rules.txt

Subscribe with "https://gitee.com/anye1998/Adguard-List-of-personal-rules/blob/master/List-of-personal-rules.txt" will cause error.

https://imgur.com/a/tzN4JWH

**Comment by DandelionSprout** [comment]
Huh. I could've sworn I had fixed it a week ago, but apparently I didn't. My fault.

I'll see when I'll get it truly fixed. Hopefully early next week at best.
