### ISSUE TITLE
add CoinblockerLists

### ISSUE THREAD

**Issue by ZeroDot1** [collinbarrett/FilterLists#146]
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by collinbarrett** [comment]
Thanks, @ZeroDot1 . Updates on the current site are currently frozen to work on v3 of the site which is progressing rapidly. I will add this to the v3 db.

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!
