### ISSUE TITLE
Table is cutted at top

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#1485]
![Screenshot_20200326_153337](https://user-images.githubusercontent.com/19818572/77658602-36d5e400-6f77-11ea-9de9-9cddf444465e.png)

Table has cutted words at top, this looks bad.

**Comment by collinbarrett** [comment]
Seems to have been resolved by https://github.com/ant-design/ant-design/pull/22872 . Let me know if you are still seeing this.

**Comment by hawkeye116477** [comment]
Yes, now isn't cutted, but seems that word „description" is to high.
