### ISSUE TITLE
hpHosts no longer available to general public

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1506]
Click on https://hosts-file.net/ will redirect to 

https://www.malwarebytes.com/browserguard

I learned this from 

https://github.com/bongochong/CombinedPrivacyBlockLists/commit/7aa955d823f53527d40552d5899f537d09e7b9af

**Comment by DandelionSprout** [comment]
Can confirm; this is the talk of the town over at https://github.com/uBlockOrigin/uBlock-issues/issues/971.

**Comment by jspenguin2017** [comment]
The final version (in case someone is interested): https://raw.githubusercontent.com/NanoMeow/UltimateMirror/master/archive/hphosts.txt

NanoMeow updates it every week, and it hasn't changed since November last year.
