### ISSUE TITLE
yhosts author decides to suspend list maintenance "indefinitely"

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1541]
https://github.com/vokins/yhosts/blob/master/README.md

> Since 2009-06-06 - 2020-04-18

Not sure the exact reason. I guess it may have something to do with law enforcement's crackdown on Pandownload.

**Comment by DandelionSprout** [comment]
Considering the list seems to remain online, I'm inclined to let the list remain on FilterLists.com until any further developments happen.

**Comment by collinbarrett** [comment]
Thanks, I agree. Good to know it's being deprecated, but let's keep it for now.
