### ISSUE TITLE
New Maintainer of yhosts

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1552]
yhosts author vokins has authorized VeleSila to maintain the list.

https://github.com/vokins/yhosts/commit/017fa57a29532ec11163d2aa18691f7b2a170ff9

Could you change relevant URLs?

Subscribe 

abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2FVelesila%2Fyhosts%2Fmaster%2Fhosts.txt

View
https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt

Home
https://github.com/VeleSila/yhosts

Github Issues
https://github.com/VeleSila/yhosts/issues

**Comment by scafroglia93** [comment]
there are two host; there's a difference ?
@VeleSila

**Comment by VeleSila** [comment]
The Wiki page explains it in Chinese, but I haven't spent time on translating it to English yet.

In a word, you won't experience any differences if you're not Chinese. The "hosts" is the complete list. The "hosts.txt" removes some entries that blocks ads on app developed and own by some Chinese video websites. Removing them may cause issues if you play those websites' video on computer.
