### ISSUE TITLE
add "last updated" column

### ISSUE THREAD

**Issue by useronegit** [collinbarrett/FilterLists#1557]
And maybe a feature to sort to last updated

**Comment by gwarser** [comment]
Currently broken https://github.com/collinbarrett/FilterLists/issues/378

**Comment by collinbarrett** [comment]
Yeah, we used to have that, but the number of lists got so big it was hard for the automated bot to keep up. I certainly plan to re-enable it, it'll just take a significant amount of work.

**Comment by Laicure** [comment]
Same case with #794 last year

I have given up on FilterLists. :(

**Comment by DandelionSprout** [comment]
As it currently stands, the "Last updated" info would've had to updated manually, which'd be a morale-wise death wish when there's north of 1,800 lists to keep track of.

Thus I can't currently recommend adding such a column, despite the presence of a "Last Updated" infotag in the JSON files.

**Comment by asterriya** [comment]
Yeah, voted for that function. NextDNS somehow applied it.

**Comment by collinbarrett** [comment]
closing into #371
