### ISSUE TITLE
new list -> cybersaian italian

### ISSUE THREAD

**Issue by scafroglia93** [collinbarrett/FilterLists#1582]
Source ->
https://github.com/CyberSaiyanIT/InfoSharing

list (domain) ->
https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE

**Comment by scafroglia93** [comment]
Already added my mistake ;(

**Comment by DandelionSprout** [comment]
I actually don't think it has been added already, when I look through the existing lists.
