### ISSUE TITLE
i made a generic list to unsticky annoying header bars

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#162]
https://github.com/elypter/generic_annoying_stickybar_filter

Description | The list's functionality
-- | --
DescriptionSourceUrl | ?
DiscontinuedDate | n/a
DonateUrl | n/a
EmailAddress | elypter@yahoo.de
ForumUrl | n/a
HomeUrl | https://github.com/elypter/generic_annoying_stickybar_filter
IssuesUrl | https://github.com/elypter/generic_annoying_stickybar_filter/issues
*Languages | n/a
*License | CC3
*Maintainer | elypter
Name | Generic Annoying Stickybar Filter
SubmissionUrl | https://raw.githubusercontent.com/elypter/generic_annoying_stickybar_filter/master/prefixes.txt
*Syntax | uBlock Origin
*UpstreamFilterLists | n/a
ViewUrl | https://raw.githubusercontent.com/elypter/generic_annoying_stickybar_filter/master/prefixes.txt

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!
