### ISSUE TITLE
CAMELEON Hosts Deprecated

### ISSUE THREAD

**Issue by sr093906** [collinbarrett/FilterLists#1626]
https://github.com/WaLLy3K/wally3k.github.io/commit/7d8ec4c0e2a58b30bdc70a5559685153477a5c8b

on website

![image](https://user-images.githubusercontent.com/8369201/82282701-1189b300-99c7-11ea-9589-3961812a4894.png)

**Comment by DandelionSprout** [comment]
Thanks for the heads-up. It's now been added to a to-do tasklist.
