### ISSUE TITLE
add uMatrix Rules

### ISSUE THREAD

**Issue by Rictusempra** [collinbarrett/FilterLists#164]
https://github.com/Rictusempra/uMatrix-Rules

**Comment by Rictusempra** [comment]
update: it gots an org now: https://github.com/uMatrix-Rules

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by Rictusempra** [comment]
@collinbarrett Thanks for that.
Now @gorhill is not going to add subscriptions for uMatrix rules yet. So this list may need special use cases.
For example, provide direct download links for both rules (I not changing link easily).

**Comment by collinbarrett** [comment]
Hmm, haven't added any uMatrix rules syntax lists to the site yet. Thinking about how that will work. I'm not a uMatrix user personally. Can these lists be "subscribed to" in uMatrix like other lists can be subscribed to in uBlock?

Maybe we need to add a new syntax and software for uMatrix lists over in #7 ?

**Comment by elypter** [comment]
there is currently no way to subscribe to rules in umatrix but you can use a script to update a file in your profile folder and since it is the same syntax as in ublock and nano adblocker (they support both rules and filters) it might be possible to subscribe to one in the future in nano adblocker

**Comment by collinbarrett** [comment]
Ok, thanks. Does that syntax have a name that you'd suggest if I go ahead and list it? Something in the same vein as the syntaxes [here](https://github.com/collinbarrett/FilterLists/blob/master/data/Syntax.json) but that defines the uMatrix-style rules? I'll also add uMatrix to the list of [software](https://github.com/collinbarrett/FilterLists/blob/master/data/Software.json).

**Comment by bogachenko** [comment]
@collinbarrett please add an icon to it for the field - Software

PS Although the umatrix icon is scary. forgive me gorhill
