### ISSUE TITLE
Help on FilterLists.Api

### ISSUE THREAD

**Issue by znavoyan** [collinbarrett/FilterLists#165]
Hi, is there any help on how to use FilterLists.Api solution ?
I have compiled and run it. It starts listening on localhost:5000. But I don't know how to make queries.
Before that I successfully used a adblockparser module under Python, where the logic is very simple.
You first initialize AdblockRules() class by giving filter list filename as argument. After that it become possible to call should_block("http://url/"), which returns boolean value indicating if the site is ad.
As I understand, the FilterLists.Api is .net core web API implementation similar to the described one? Am I right? If yes, can you please advise how to make queries to this API and classify url/domains ? Can you please show a sample query?

Thanks,
Zaven.

**Comment by collinbarrett** [comment]
Hi Zaven,

The API is still under construction and has very little functionality currently. The only endpoint that is built currently can be accessed at https://api.filterlists.com/v1/lists . In its current state, however, it will probably not be very useful to you.

To build and run yourself, you'll need to spin up the database first using entity framework code first migrations. The scripts are all in the GitHub project, and some quick Google-ing should show you how to update the database using the scripts.

I hope to have the API more useful in the near future, but time has just been limited.

Check back soon.

Thanks!
