### ISSUE TITLE
add AdBlock Protector 2 lists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#167]
Though project is archived, add any lists from [AdBlock Protector 2](https://github.com/AdBlockProtector2/AdBlockProtector2/).

**Comment by xqk94524** [comment]
AdBlock Protector 2 was cancelled, in favor of the development of Nano defender.

And also the extension part, was never released.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by Atavic** [comment]
:+1: at what xqk94524 said above.
Archived project.

**Comment by Atavic** [comment]
Archived project.

**Comment by collinbarrett** [comment]
closing per above and [here](https://github.com/collinbarrett/FilterLists/issues/117#issuecomment-367443486)
