### ISSUE TITLE
add missing lists used by NextDNS

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#1697]
I think we have most of these, but there may be a few new ones.

https://github.com/nextdns/metadata/tree/master/privacy/blocklists

**Comment by DandelionSprout** [comment]
I found a total of zero new lists at that link.

But looking through https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json, on the other hand...:

* https://blocklist.cyberthreatcoalition.org/vetted/domain.txt
* https://raw.githubusercontent.com/sophoslabs/covid-iocs/master/malicious_domains.txt
* https://raw.githubusercontent.com/sophoslabs/covid-iocs/master/malware_domains.txt
* https://rescure.fruxlabs.com/rescure_domain_blacklist.txt
* https://rescure.fruxlabs.com/maze.txt
* https://rescure.fruxlabs.com/covid.txt
* https://managedsentinel.com/downloads/covid19_domains.txt
* https://kriskintel.com/ktip_domain_blacklist.txt
* https://kriskintel.com/ktip_maze.txt
* https://kriskintel.com/ktip_corona.txt
