### ISSUE TITLE
Add nocoin

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#170]
https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by hoshsadiq** [comment]
This is already on there: https://github.com/collinbarrett/FilterLists/commits?author=hoshsadiq

**Comment by hoshsadiq** [comment]
By the way, just out of curiosity, is there a reason you took the data out of Github? This prevents people from raising PRs (and everything must be done manually by raising an issue and then you would have to add it), as well as it was quite nice as people could potentially download the JSON file and give them an interface to select what they want to add.

**Comment by collinbarrett** [comment]
Thanks, @hoshsadiq .

I am working on a re-write with a much expanded data model. The model is a bit unwieldy for a single JSON file. Instead of open-sourcing the data via a json file, I am building a public/free API that allows users to get the specific json dataset that they want.

Unfortunately, progress has been slow on this recently, but I hope to pick it up again soon.

New Data Model: https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Data/Entities

**Comment by hoshsadiq** [comment]
Aah cool. That makes sense :)

**Comment by collinbarrett** [comment]
hey, @hoshsadiq ,  I just wanted to let you know i added the partial dataset that I am building [here](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). I am working on functionality to seed a new copy of the db from this dataset, and it will also serve as a way to host the data on GitHub and gather PRs for data updates.
