### ISSUE TITLE
Add new list please!

### ISSUE THREAD

**Issue by K-mikaZ** [collinbarrett/FilterLists#1731]
I have create a list that boost page loading by automatically creating redirect rules based on [gorhill's redirect-rule](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect-rule) (which are often omitted but important) for all present and futur filters/lists.

You can find it here: [Noop-My-Filters-Please](https://github.com/K-mikaZ/-Boost-Noop-My-Filters-Please-/blob/master/Noop-My-Filters-Please.txt) (the [RAW](https://raw.githubusercontent.com/K-mikaZ/-Boost-Noop-My-Filters-Please-/master/Noop-My-Filters-Please.txt) version)

You can test it before, of course.

**Comment by K-mikaZ** [comment]
precision:
Only for ublock and nano adblocker
It's not really a block list, it only applies the appropriate redirects to each filter that has omitted to specify it.
e.g:
the filter `||theBlockedSite.tld`
become:
`||theBlockedSite.tld$script,redirect-rule=noopjs` if it is a script concern,
`||theBlockedSite.tld$xhr,redirect-rule=nooptext` if it is a xhr concern...

**Comment by gwarser** [comment]
Your list is not valid.

I don't believe providing any response will be faster than just aborting network request. 

You need to read more about pre-parsing directives - [`!#if`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition). For example only these tokens are supported:

	ext_ublock
	env_chromium
	env_edge
	env_firefox
	env_mobile
	env_safari
	false
	cap_html_filtering
	cap_user_stylesheet

**Comment by K-mikaZ** [comment]
> Your list is not valid.
> You need to read more about pre-parsing directives - [`!#if`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition). For example only these tokens are supported:

OK, but take a look at the screenshot and explain why it works.
And the link that you give me (and for information that I have already read) points to https://github.com/AdguardTeam/AdguardBrowserExtension/issues/917 which explains:
``` 
Conditions:
When an adblocker encounters an !#if directive, followed eventually by an !#endif directive,
it will compile the code between the directives only if the specified condition is true. 
Condition supports all the basic logical operators.

```

> I don't believe providing any response will be faster than just aborting network request.

Test and tell me if it doesn't.

**Comment by llacb47** [comment]
These are the only valid directive values in uBo: https://github.com/gorhill/uBlock/blob/bc7f1492522f08477325242d95f4fd3992bf5d42/src/js/storage.js#L907

These are some, maybe not all, valid directive values in adguard: https://github.com/ameshkov/VscodeAdblockSyntax/blob/692fcdc7891f1ca176bd4c7776ed4b2903b36cb0/syntaxes/adblock.tmLanguage.json#L52

**Comment by gwarser** [comment]
> OK, but take a look at the screenshot and explain why it works.

Because unknown directives are ignored. All filters are parsed.

>And the link that you give me (and for information that I have already read) points to AdguardTeam/AdguardBrowserExtension#917 which explains:

So, your filter is only for AdGuard? uBO does not support most of the logic. These are pre-parsing directives, even if they work they will not be dynamically updated based on request type.

>Test and tell me if it doesn't.

This is your list. You need to prove it's useful.

> And please, explain to me why gorhill would create a redirect-rule if it was useless?

To fix anti-adblockers which expect some content to be returned in response.

**Comment by uBlock-user** [comment]
> And please, explain to me why gorhill would create a redirect-rule if it was useless?

`redirect-rule` provides ease for redirecting already existing blocking filters with responses and only creates `1` filter instead of `2`(as seen by using `$redirect`)

**Comment by gorhill** [comment]
> boost page loading by automatically creating redirect rules

Claims like this needs to be substantiated with evidences and in a way that everybody can reproduce.

**Comment by gwarser** [comment]
@K-mikaZ after all - thank you! Thanks to your list we learned that `ping`, `beacon`, and `websocket` redirecion is pointless/invalid and redirecting to `empty` creates redirection regardless of type. Besides that, snapshot of your list will be used to test pre-parsing directives.

# :smile:
