### ISSUE TITLE
Ublock protector now is Nano defender

### ISSUE THREAD

**Issue by xqk94524** [collinbarrett/FilterLists#174]
initially named AdBlock Protector, then Ublock protector and now the name is Nano defender.

note this is Chrome only solution and support Nano adblock and Ublock origin.

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!
