### ISSUE TITLE
CoinBlockerLists

### ISSUE THREAD

**Issue by alicektx** [collinbarrett/FilterLists#175]
[https://zerodot1.github.io/CoinBlockerLists/](url)
[https://github.com/ZeroDot1/CoinBlockerLists](url)

"_Simple lists that can help prevent cryptomining in the browser or other applications._"

GPL 3-licenced.

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by collinbarrett** [comment]
dup of #146
