### ISSUE TITLE
add kano1 's lists

### ISSUE THREAD

**Issue by kano1** [collinbarrett/FilterLists#176]
adware block
https://raw.githubusercontent.com/kano1/I/master/adware.txt
Spyware Block
https://raw.githubusercontent.com/kano1/Kano/master/Spyware.txt

**Comment by elypter** [comment]
The first list contains a whole page of whitelisted advertisement domains.

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by kano1** [comment]
I do not want to delete this whitelist list because I understand this is a good advertisement
or I will give you my new list  this list this no have whitelist advertisement
this is a collection based on issues in the media that say this is a bad advertisement

https://raw.githubusercontent.com/kano1/I/master/adware.txt

https://raw.githubusercontent.com/kano1/I/master/pop.txt

**Comment by collinbarrett** [comment]
Thanks for your thoughts. The goal of FilterLists is to be a largely un-opinionated directory of all available lists. It should expose relevant information about all known lists to give users the option to choose which they want to use.

**Comment by kano1** [comment]
thakyou collinbarrett 

and elypter 
thanks for the suggestion i  understand.. because what you want is privacy so I will not burden it with a white list but you must be really full privacy when you really want full privacy mybe

**Comment by collinbarrett** [comment]
Hi @kano1 , I'd like to get all of your lists indexed, but I'm a bit confused. It looks like you have five public repos that are all adblocking-type lists. Can you update here with links to all of your lists for adblocking, etc. that FilterLists can index? Ideally, provide all the properties information described [here](https://github.com/collinbarrett/FilterLists#properties) about each list. Thanks!

**Comment by kano1** [comment]
some of the domains in the suspect dangerous but I don't publish him because I doubt

**Comment by kano1** [comment]
some of the domains in the suspect dangerous but I don't publish him because I doubt 
Thanks for the help of his collinbarrett

**Comment by kano1** [comment]
some of the list here is what we suspect might be so this is the advertising url
my example typing /log/system or /proxy/ will then block the tracking list that uses the url

**Comment by arufam124** [comment]
i like GarudaSpeedUp  have 13list and block all ads it is not like all adblock have 90 000 list and no block all

I like spyware block I may rarely find a spyware filter that does not block ads

**Comment by tsugami1** [comment]
is good:
I always find out before using filters and I found something interesting where trojans were considered spyware and I found out that all of the devices are only one tool that detects it (block by avira)

https://www.virustotal.com/#/url/503fc46e3bee20710aa2b05c5843be9ee6c13484e4eec4783d468c656b8c4445/detection
![bad2](https://user-images.githubusercontent.com/42826820/45527319-80376600-b80d-11e8-9382-f87086a7f48e.png)

![badrab](https://user-images.githubusercontent.com/42826820/45527332-91807280-b80d-11e8-9dc1-1252dc6356d0.png)

**Comment by DandelionSprout** [comment]
If I understand you (tsugami1) correctly, then it pretty much confirms to me that anti-malware filter lists are a nice supplement to antivirus softwares, if not outright important to use.

It deserves mention that antivirus tools are usually pretty bad at blocking websites, and in my experience have more false positives than real positives. I've had _Trend Micro_ block the websites of N2 Elite, and had _Adguard DNS_ once block the image servers of Imgbox for a few days.

**Comment by collinbarrett** [comment]
Closing as complete enough for now. Feel free to comment if there is more work to be done and we can re-open.
