### ISSUE TITLE
AlleBlock

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#177]
| Property             | Description                                                              |
|----------------------|--------------------------------------------------------------------------|
| Description          | Filters, which makes easer to use of the largest Polish trading platforms like Allegro, Ceneo, eBay, OLX and Sprzedajemy and other, blocking unnecessary, annoying and potentially dangerous elements - ads, sponsored articles, or scripts that track user's activities. They enable simpler and faster use of supported websites without limiting their functionality, while increasing the privacy of buyers and sellers.                                                 |
| DonateUrl            | https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RN7R64TJLWQW6                                                  |
| EmailAddress | blablabla@alleblock.pl |
| HomeUrl              | https://alleblock.pl/                                                 |
| IssuesUrl            | https://github.com/maciejtarmas/AlleBlock/issues                                             |
| *Languages           | pl                                             |
| *License             | CC BY-NC 4.0 |
| *Maintainers         | @maciejtarmas                                                  |
| Name                 | AlleBlock                                         |
| SubmissionUrl        | `abp:subscribe?location=https%3A%2F%2Falleblock.pl%2Falleblock%2Falleblock.txt&amp;title=AlleBlock`                                           |
| *Syntax              | Adblock Plus            |
| ViewUrl              | https://alleblock.pl/alleblock/alleblock.txt                       |

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!
