### ISSUE TITLE
Distinguish between types of lists

### ISSUE THREAD

**Issue by hoshsadiq** [collinbarrett/FilterLists#178]
Currently all lists are seen as filter lists. It would be cool to distinguish between hosts files (such [BadHosts](http://www.hostsfile.org/Downloads/hosts.txt)), adblock filter lists ([AakList (Anti-Adblock Killer)](https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt)), and simple list of IPs/domains ([abuse.ch Feodo IP Blocklist](https://feodotracker.abuse.ch/blocklist/?download=ipblocklist)) to block. This goes back to what I said in #170, where uBlock Origin for example can query the API for just adblock filters, whereas pi-hole can query just the hosts files.

**Comment by collinbarrett** [comment]
Yep, I completely agree. It's in the works. See issue #7

**Comment by collinbarrett** [comment]
Also note that I am then going to link the syntaxes to the software tools that support them, which will allow users to filter only lists supported by uBlock Origin, for example. So many exciting things, just haven't had much time to work on it as of late.

https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Data/Entities/Software.cs
https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Data/Entities/SoftwareSyntax.cs

**Comment by hoshsadiq** [comment]
Cool. Is this a dotnet core project? I'm happy to try and contribute if a find the time

**Comment by collinbarrett** [comment]
It is! Awesome! I'm using it as a learning project for .NET Core, as well. I've been using .NET on my day job for quite a few years, but haven't had the chance to work with Core yet at work.

I am still going back and forth on the front-end. Current iteration is a shot at React, but the learning curve might be too great (not a JS / React guy).

I've used a lot of controls like Kendo/Telerik/DevExpress in the past, but none of these are free for open-source. So, open to suggestions on front-end tooling.

But, the backend/API skeleton is fairly fleshed out.
