### ISSUE TITLE
add Anti Fake News International List (AFNIL)

### ISSUE THREAD

**Issue by AFNIL-AntiFakeNewsInternationalList** [collinbarrett/FilterLists#179]
Property | Description
-- | --
Description | Anti fake News International List AFNIL’s intention is to merge third-party lists of known fakenews sites and make them usable for programs that can block.
HomeUrl | https://afnil-antifakenewsinternationallist.github.io/
IssuesUrl | https://github.com/AFNIL-AntiFakeNewsInternationalList/AFNIL/issues
*Languages | it, fr, de, us, br, hu, nl and others 
*License | GNU/GPL
*Maintainers | AFNIL Anti Fake News international List
Name | AFNIL Anti Fake News international List
SubmissionUrl | abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2FAFNIL-AntiFakeNewsList%2FAFNIL%2Fmaster%2FAFNIL-ABP-uBO.txt&title=AFNIL%20Anti%20Fake%20News%20List
*Syntax | uBlock Origin, Adblock Plus
*UpstreamFilterLists |  merge third-party lists of fake news sites from certain sources
ViewUrl | https://raw.githubusercontent.com/AFNIL-AntiFakeNewsInternationalList/AFNIL/master/AFNIL-ABP-uBO.txt

Property | Description
-- | --
HomeUrl | https://afnil-antifakenewsinternationallist.github.io/
Name | AFNIL Anti Fake News International List
*FilterLists | abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2FAFNIL-AntiFakeNewsList%2FAFNIL%2Fmaster%2FAFNIL-ABP-uBO.txt&title=AFNIL%20Anti%20Fake%20News%20List

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by Atavic** [comment]
From personal blogs as aanirfan to big forums as abovetopsecret... why block them?
What's left after using this list, google and yahoo homepages?
