### ISSUE TITLE
Feature request - clicking on tag loads all filters with that tag

### ISSUE THREAD

**Issue by RedDragonWebDesign** [collinbarrett/FilterLists#1796]
For example, if I click on either of the highlighted "crypto" tags, it'd be great if they'd load the list of filter lists, filtered so that I only see ones with the "crypto" tag.

![2020-07-20_023244](https://user-images.githubusercontent.com/43397938/87922895-74ccab80-ca31-11ea-8859-72bb7164cd59.png)

**Comment by collinbarrett** [comment]
closing into #263
