### ISSUE TITLE
Feature request - search box

### ISSUE THREAD

**Issue by RedDragonWebDesign** [collinbarrett/FilterLists#1797]
When I visit the page on PC, it only loads about 7 filters at a time. And I also can't filter by tag. This makes it a bit hard to look for certain types of filters.

A search box would really help with this. Where you type text, hit enter, and it displays filter list names that contain the search text.

**Comment by collinbarrett** [comment]
I think we have both of these features already. Let me know if I am misunderstanding your suggestion.

> And I also can't filter by tag.

![image](https://user-images.githubusercontent.com/6483057/87942347-fa7d4500-ca8b-11ea-94ca-066a24537fc1.png)

> A search box would really help with this. Where you type text, hit enter, and it displays filter list names that contain the search text.

![image](https://user-images.githubusercontent.com/6483057/87942411-108b0580-ca8c-11ea-80c4-bf2a2d158a87.png)

**Comment by RedDragonWebDesign** [comment]
Ah, you're correct, thank you for pointing that out. If you're interested, maybe make the search button a brighter color or more button looking or something. I honestly completely missed it.
