### ISSUE TITLE
Idea - narrower header and footer

### ISSUE THREAD

**Issue by RedDragonWebDesign** [collinbarrett/FilterLists#1798]
On PC, I can only see 7 rows per page at the moment. You could probably get 10 or more rows per page simply by shrinking the size of the header and the footer.

![2020-07-20_023801](https://user-images.githubusercontent.com/43397938/87923290-1b18b100-ca32-11ea-8d52-84c778d78824.png)

**Comment by collinbarrett** [comment]
I agree. This can be especially painful on mobile as well. I'm not much of a designer, and with a giant data table, it's hard to know how to optimize the real estate, etc. Narrower header/footer could certainly be an option.
