### ISSUE TITLE
Update ABP X Files (IT) link

### ISSUE THREAD

**Issue by gioxx** [collinbarrett/FilterLists#180]
Good morning.
Can You please update the link of ABP X Files? All files are hosted on GitHub, "Add" and "View" buttons doesn't work.

This is the correct URL:
https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt

Thanks in advance.
Giovanni.

**Comment by collinbarrett** [comment]
Will do. Unfortunately, I am having some issues updating the current version of the site. I will try to resolve them so I can perform this update, but I may not get it updated until the new v3 version of the site is launched. Thanks for your patience.

**Comment by gioxx** [comment]
You're welcome Collin. I just did it to report the problem.
I am a patient man :)

**Comment by collinbarrett** [comment]
If anyone is willing and able to help, I'll accept a PR against [Seed](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api/Seed). If not, I'll get to it eventually. Thanks!

**Comment by gioxx** [comment]
Closed without resolution? 😕

**Comment by collinbarrett** [comment]
The current version of the site is frozen (it was poorly designed, and too hard to update). I am working on a new version that I hope to launch very soon. Your request was updated in the new db in the commit shown right above your last comment. You can verify it is correct at https://beta.filterlists.com/ . I apologize I won't be able to fix it on the current site, but the current site should be replaced very soon. Thanks for maintaining the list!
