### ISSUE TITLE
it's not subscribing to filters

### ISSUE THREAD

**Issue by DialexG91** [collinbarrett/FilterLists#1802]
i cilck the "subscribe" button about 400000000000000000000000 times and doesn't happen anything, and neither the mirrors

**Comment by llacb47** [comment]
Do you have an adblocker installed? (uBlock Origin, adguard, ABP, etc.)

**Comment by collinbarrett** [comment]
> Do you have an adblocker installed? (uBlock Origin, adguard, ABP, etc.)

And, if so, which one? And, which browser are you using?

Closing for now, but will re-open if we get more details and determine it to be a bug.

**Comment by DialexG91** [comment]
of course i have it, uBlock Origin on Microsoft Edge, it also has happened on Chrome

**Comment by collinbarrett** [comment]
When you click a "Subscribe" button and nothing happens, are there any errors in the Chromium (Chrome or Edge) console (press F12 on Windows to open console)?

I just tested in Chrome and Edge (Chromium) with uBlock Origin and it worked. But, there may very well be corner cases where it doesn't.

If you can share any more info about specifically which "Subscribe" button you clicked, any other special environment considerations (other plugins, etc.) that could help, that'd be great.

**Comment by DandelionSprout** [comment]
I distinctly recall reading something about uBO's detection of `abp:subscribe` being bugged this summer, but I can't remember where.

I can definitely confirm the existence of the problem after clicking a bit around on FilterLists. Around 95% of Subscribe button presses would fail after the 4th-ish list whose Subscribe button was clicked.

**Comment by llacb47** [comment]
Maybe https://github.com/uBlockOrigin/uBlock-issues/issues/763.

**Comment by DialexG91** [comment]
> When you click a "Subscribe" button and nothing happens, are there any errors in the Chromium (Chrome or Edge) console (press F12 on Windows to open console)?
> 
> I just tested in Chrome and Edge (Chromium) with uBlock Origin and it worked. But, there may very well be corner cases where it doesn't.
> 
> If you can share any more info about specifically which "Subscribe" button you clicked, any other special environment considerations (other plugins, etc.) that could help, that'd be great

> When you click a "Subscribe" button and nothing happens, are there any errors in the Chromium (Chrome or Edge) console (press F12 on Windows to open console)?
> 
> I just tested in Chrome and Edge (Chromium) with uBlock Origin and it worked. But, there may very well be corner cases where it doesn't.
> 
> If you can share any more info about specifically which "Subscribe" button you clicked, any other special environment considerations (other plugins, etc.) that could help, that'd be grea

> When you click a "Subscribe" button and nothing happens, are there any errors in the Chromium (Chrome or Edge) console (press F12 on Windows to open console)?
> 
> I just tested in Chrome and Edge (Chromium) with uBlock Origin and it worked. But, there may very well be corner cases where it doesn't.
> 
> If you can share any more info about specifically which "Subscribe" button you clicked, any other special environment considerations (other plugins, etc.) that could help, that'd be great.

what do you mean which subscribe button? how do you add the filters to the ad blocker? and I didn't see any error on the console

**Comment by collinbarrett** [comment]
I was just asking which specific list(s)' subscribe button(s) were failing. But, I doubt it is tied to a specific list's button.

We've had issues in the past, too. I'm not sure if it is something FilterLists can fix, or if it is a uBlock Origin issue.

https://github.com/collinbarrett/FilterLists/issues/438

**Comment by DialexG91** [comment]
I finally add the filters manually copying and pasting the link of the filter in the uBlock's control panel, henceforth I'll do this way

**Comment by gorhill** [comment]
It's a uBO issue, working on it.
