### ISSUE TITLE
which adblock extensions is support

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#181]
add a information in new column, which specific list is supported by through which Adblock
`https://filterlists.com/`

like that design
![2018-01-17-adblock ublock adguard polish filters _ polish-ads-filter](https://user-images.githubusercontent.com/5884000/35071820-6d96a764-fbe2-11e7-9d16-fa9e0dc60cf2.png)
`https://www.certyficate.it/adblock/`

**Comment by collinbarrett** [comment]
Thanks, @KonoromiHimaries ! That is something we are working on for sure. I love the idea of using logos, though, that's a great UI suggestion.

Closing as duplicate of #11
