### ISSUE TITLE
Use generic Seed<T>(DbContext context) method

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#183]

**Comment by Atavic** [comment]
>I'll accept a PR against Seed.

There's an how to?

**Comment by collinbarrett** [comment]
Thanks, I'll work on creating that.

Until I do, it's a relational database dumped to json files. Start with adding or updating the list in FilterList.json. The other files contain other metadata about the list.



FYI for anyone else landing on this issue, @Atavic 's question was not related to this issue.

**Comment by Atavic** [comment]
:+1: Mr. Barrett !!

**Comment by collinbarrett** [comment]
asked SO question to solve here:
https://stackoverflow.com/questions/48330079/reference-public-dbset-property-of-generic-type
