### ISSUE TITLE
[FYI] Thai Paranoid Block by kowith337 (En, Thai)

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#184]
@kowith337 ThaiParanoidBlock
Description: Blocks ads, tracking, popup sites and servers mostly used on Thai sites.

DescriptionSourceUrl:  https://kowith337.github.io/ThaiParanoidBlock/
DiscontinuedDate: 2 days
DonateUrl EmailAddress ForumUrl N/A
HomeUrl: https://github.com/kowith337/ThaiParanoidBlock
IssuesUrl: https://github.com/kowith337/ThaiParanoidBlock/issues
*Languages: En, Thai
*License: Attribution-NonCommercial CC BY-NC
*Maintainers: kowith337
Name: ThaiParanoidBlock
*Syntax: uBlock Origin
*UpstreamFilterLists N/A

**ViewUrl:** https://github.com/kowith337/ThaiParanoidBlock/blob/master/ThaiParanoid.txt

HomeUrl: https://klout.com/kowith337
TwitterHandle: kowith337
*FilterLists: ThaiParanoidBlock and Thai AntiForceLike.

Seems well maintained as it has: DOM Element Hiding, Domain level block (e.g. Baidu, Hao123, DesktopWeather), Mobile Badvertisers, Anime Leeching List, First party annoyances (e.g. Google, Facebook, Twitter) and a few Strict blocking like disqusads.

**Comment by kowith337** [comment]
Seems like I'm not ready yet because it may block certain domains globally, such as Facebook (Both main and Messenger), Instagram, Twitter, etc.
or else, I need to make another branch and strip-down some global rules.

**Comment by collinbarrett** [comment]
Ok. Well, FilterLists is aimed at being a directory of all known lists. Even if your list still needs work, we'd like to capture it. We'll keep this issue open until I have a chance to merge it into the dataset. Thanks for working on a list!

**Comment by kowith337** [comment]
### Additional Info
#### UpStream usage
- [X Files: NoFacebookAds](https://github.com/gioxx/xfiles/blob/master/facebook.txt) (some DOM) [[commit](https://github.com/kowith337/ThaiParanoidBlock/commit/d95b9e4f1c323e44327c5fb92231b7f461e85b53)]
- [LeeCh-List](https://github.com/pureexe/LeeCh-List) by pureexe
- [ThaiConsentHosts](https://github.com/kowith337/ThaiConsentHosts) (Mobile badvertisers, stripped down subdomain rules)
  - I will be open new issue for give details about this hosts file later

**Comment by collinbarrett** [comment]
hi @kowith337 , by "UpStream usage", do you mean that Thai Paranoid uses some rules from these lists? Or that those lists use some rules from Thai Paranoid?
