### ISSUE TITLE
#1842's changes haven't gone live yet

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#1847]
I notice that the changes from #1842 hasn't gone live yet after 3 days. Is there any particular reason for that?

**Comment by collinbarrett** [comment]
Looks like there was an [intermittent test timeout error that blocked the CI build](https://dev.azure.com/collinbarrett/FilterLists/_build/results?buildId=4100&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=19586ee0-dbfa-5afa-af40-97d3e09dc4a4).

I just triggered a manual build, and I think it looks good now.

Thanks for reporting.
