### ISSUE TITLE
Separate the syntax category "uMatrix/uBlock Origin dynamic" into each of the two

### ISSUE THREAD

**Issue by Yuki2718** [collinbarrett/FilterLists#1848]
The syntax format is so different that I don't believe importing the one into the other works. I'll feel sorry if someone imported my uBlock dynamic rules to uMatrix and got a problem - despite it's titled with uBlock. Recent issues on uBlock, which @DandelionSprout will be familiar with, suggests such things can actually happen - people even subscribe dynamic rules as a static filter list. Apparently all the lists currently under this category are actually uMatrix rules and mines are only uBlock dynamic rules. So probably a reasonable steps will be creating a new Syntax ID for uBlock dynamic rules and make current ID for the category solely for uMatrix. I have no problem to make PR for my lists if that's done.

**Comment by DandelionSprout** [comment]
For me personally, the thing is that I genuinely can't tell the difference between the two extensions' dynamic formats. In my eyes it's the same spreadsheet table of green, red and white boxes. Here's from Nano Adblocker's quickmenu, for instance: 
![image](https://user-images.githubusercontent.com/22780683/89125704-a9843c80-d4e0-11ea-96b3-8a98028f41f2.png)

If you can prove me wrong through a better comparison made by someone who actually *do* use dynamic rules on an everyday basis (e.g. you), I'd be willing to correct my mistake within 48 hours.

**Comment by DandelionSprout** [comment]
After looking a bit around, I found there was a slightly different distinction to make: Lined rules (supported by uBO and uMatrix) and grouped/categorised rulesets (seemingly only supported by uMatrix).

I've identified 7 lists as belonging to the latter type of brand-new syntax:
* Vasiliy Polyakov
* uMatrix - Rulesets for English websites
* thematrixteeth's uMatrix Recipes
* Ruleset for Thai sites
* migueldemoura
* Kowith's Self Custom Ruleset
* themagicteeth (Currently mistitled "thematrixteeth")

**Comment by Yuki2718** [comment]
1. uMatrix doesn't have noop.
2. uMatrix rules have one more dimension than uBO dynamic - this is why you see grouped rule sets.

**Comment by collinbarrett** [comment]
Thanks, all. Closing per #1850 , but we can certainly re-open if more work needs to be done.

**Comment by DandelionSprout** [comment]
When it comes to №1, I thank you for pointing that out, though I was 3min too late to implement that to #1850 after I woke up. I'll get it done in my next PR, hopefully.

**Comment by Yuki2718** [comment]
Thanks @DandelionSprout for your hard work despite I didn't explain required things well - sorry I was tired. So apparently you changed the IDs for uMatrix recipes so I don't need to do anything, right?

**Comment by DandelionSprout** [comment]
That is correct, at least for those with the extra dimension.

For lined lists with noop, I plan to create yet another syntax with a corresponding ID.

**Comment by Yuki2718** [comment]
In uBO dynamic, you can only block/noop/allow per domain or specific request types:
`* abs.twimg.com * noop` globally noops whatever types of requests to `abs.twimg.com`, `* * 3p-script block` globally blocks whatever 3p requests for script, and `account.live.com gfx.ms * noop` noops whatever types of requests originated from `account.live.com` and going to `gfx.ms`. All these can be written in one line, so these are 1D info.

uMatrix, however, allows you to create 2D matrix rules: you may allow scripts originated from example.com and going to example.net AND at the same time block XHR in the same path - you can micro-manage rules per request types on a domain, which is impossible on uBO. This is what I meant.

Oh, and I forgot to mention there're some uMatrix-specific rules for request types such as cookie.

**Comment by Yuki2718** [comment]
> That is correct, at least for those with the extra dimension.

**Comment by DandelionSprout** [comment]
The current ID for lined dynamic rules is software-assigned to both uMatrix and to uBO-likes. 
![image](https://user-images.githubusercontent.com/22780683/89193391-33e2a400-d5a6-11ea-9257-c68979d17494.png)

Thus a new ID would need to be created and assigned only to uBO-likes.

**Comment by Yuki2718** [comment]
> The current ID for lined dynamic rules is software-assigned to both uMatrix and to uBO-likes.

Thx!
