### ISSUE TITLE
A Good filter source: 1hosts.cf

### ISSUE THREAD

**Issue by lancelot-moon** [collinbarrett/FilterLists#186]
Hi,

I think that you can add 1hosts.cf on your website.

https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360

It integrates many popular filters.

http://1hosts.cf/

B/R

**Comment by Atavic** [comment]
Seems good, no dupes.

   Blocked: 59,541 domains
   Size: 1.54 MB

I personally appreciate the addon found [here](http://1hosts.cf/addon/). :+1:

**Comment by lancelot-moon** [comment]
No, those add-on are just used in your own device because it will cause browsering issue if blocking them.

Ex: graph.facebook.com
It includes general and ads traffic package.

**Comment by kowith337** [comment]
Suggest to have HTTPS connections to 1hosts
