### ISSUE TITLE
Add Go-Hosts

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#188]
add to merge collection of #186
https://github.com/Lerist/Go-Hosts/blob/master/hosts-ad

**Comment by Atavic** [comment]
For mainland China, mostly. 

*Lerist.* is a dev with good votes on google play.

**Comment by collinbarrett** [comment]
any ideas what the difference is between hosts and hosts-ad? not sure the significance of the `180.97.235.30` ip, maybe it's something to do with the app that it is used in using a local proxy or something... they seem to be two separate lists, though?

**Comment by Atavic** [comment]
From description 

hosts: Google, Google Play, YouTube, Twitter, Facebook, Tumblr, Pixiv 	

is the basic one, while 

hosts-ad: Gamil, Instagram, Wikipedia, Yahoo, Telegram(WEB), Dropbox, Flipboard, Mage, Line, Pinterest, W3schools, Ingress, Twitch, SoundCloud, Xboxlive, WordPress, Tapatalk, Kobo, Vimeo, Nytimes, Issuu, Tor, DuckDuckGo, Imgur, Pcbeta...

is the addon for more sites. That ip seems the blackhole in his LAN. A personal choice.
