### ISSUE TITLE
add herndl hosts

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#189]
add to merge collection of #186
https://hosts.herndl.org/hosts_blacklist.txt

**Comment by Atavic** [comment]
This list has a problem IMHO, it includes:

>d12ulf131zb0yj.cloudfront.net
...
d3avqv6zaxegeu.cloudfront.net

but the subdomains will probably change periodically.

**Comment by Atavic** [comment]
This list has a problem IMHO, it includes:

    d12ulf131zb0yj.cloudfront.net
    ...
    d3avqv6zaxegeu.cloudfront.net

but the subdomains will probably change periodically.

Other lists do the same BTW

**Comment by collinbarrett** [comment]
hmm, ok, thanks. I'll keep an eye out for that. I still want FIlterLists to index all available lists, but hope to work on surfacing those of higher "quality" (definition tbd) to the top.
