### ISSUE TITLE
add ut-capitole hosts

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#196]
add to merge collection of #186
https://dsi.ut-capitole.fr/blacklists/download/ads.tar.gz

**Comment by Atavic** [comment]
:+1: I stumbled upon this list in the past, it's managed by a university and it is divided by *categories* like:

>adult	            1970413 	
cryptojacking 1111
drogue          1055 
malware        15200 
phishing        63508 
redirector      129382

**Comment by collinbarrett** [comment]
dup of #19
