### ISSUE TITLE
support capturing snapshots of compressed lists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#201]
The [snapshot service](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Services/SnapshotService) should be updated to support compressed (`.zip`, `.7z`) lists like [Airelle's Anti-Miscellaneous Hosts](http://rlwpx.free.fr/WPFF/hmis.7z).

Predecessor of #6 .

Related to #28 .

**Comment by elypter** [comment]
nano adblocker is also planning to implement compression and also other methods to reduce file size https://github.com/NanoAdblocker/NanoCore/issues/84

**Comment by collinbarrett** [comment]
https://github.com/collinbarrett/FilterLists/blob/master/scripts/sql/cantSnapshot.sql

**Comment by collinbarrett** [comment]
Remove 186 from excluded per #374
