### ISSUE TITLE
parse list metadata

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#202]
Per [this](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/917#issuecomment-364960536), we want to capture, parse, and display list metadata. Not all lists implement metadata in the exact same formatting, or at all, though, so it may be difficult to do.

Metadata to Capture:

- [ ] List's published Title (i.e., `! Title`)
- [ ] List's published updated date (i.e., `! Expires`)
- [ ] List's published Description (i.e., `! Description`)
- [ ] AdGuard syntax platform "Hints" (i.e., `!+ PLATFORM()`, `!+ NOT_PLATFORM()`) (per [this](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#platform-and-not_platform-hints))
- [ ] Pre-Processor Directives (per [this](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pre_processor)) (ref: [uBO's source](https://github.com/gorhill/uBlock/blob/3d867baf0b844cb1d411f5dacbec3c1b95108d3c/src/js/storage.js#L898))
- [ ] Misc. Comments - All other comments are now being tracked, maybe they are useful to surface in the app in some way. They are tracked not in any kind of order, and only one instance of each unique line per snapshot is tracked, so placement in the file is not usable. (ref: [uBO's source](https://github.com/gorhill/uBlock/blob/e3543924a06189878674372d8335193135856e3c/src/js/storage.js#L834))

**Note about current "Rule Count"** in the list details expanders. They are currently by each unique line in the list (including all metadata). As the checkboxes above get ticked off, the Rule Count will go down so as to only include actual rules (and not comments/metadata).

**Comment by collinbarrett** [comment]
ublock's source: https://github.com/gorhill/uBlock/blob/f64d703ba0a2baa9c8366f05117078380675189e/src/js/storage.js#L749

**Comment by DandelionSprout** [comment]
It's fair to close #695, but in that case I'd have wanted to add:

- [ ] List's published Description (i.e., `! Description`)

...to this thread's OP checklist, so that we don't really forget about adding descriptions specifically. Unless you have any objections of some sort to doing so, of course.

**Comment by collinbarrett** [comment]
Ah, sorry, I thought it was. Done.

**Comment by collinbarrett** [comment]
closing into #371
