### ISSUE TITLE
Block Ads on Twitch.tv

### ISSUE THREAD

**Issue by FirefoxWas** [collinbarrett/FilterLists#204]
Hi 

Can you add Block Ads on Twitch.tv  listed on your filterlists. 

Block Ads on Twitch.tv

s0.2mdn.net
c.amazon-adsystem.com
s.amazon-adsystem.com
d3aqoihi2n8ty8.cloudfront.net
ad.doubleclick.net
securepubads.g.doubleclick.net
supervisor.ext-twitch.tv
0914.global.ssl.fastly.net
ssl.google-analytics.com
adservice.google.com
imasdk.googleapis.com
www.googletagservices.com
www.gstatic.com
cdn.krxd.net
api.mixpanel.com
edge.quantserve.com
sb.scorecardresearch.com
www.summerhamster.com
fsm1019.global.ssl.fastly.net/fsm/ds

https://d2zv5rkii46miq.cloudfront.net/0/1.7.801/recovery_dfp_internal-v1.7.801.js
https://d2zv5rkii46miq.cloudfront.net/0/1.7.801/recovery_lib_api_iframe-v1.7.801.html
https://d2zv5rkii46miq.cloudfront.net/0/1.7.801/recovery_lib_rid_iframe-v1.7.801.html
www.twitch.tv##.js-player-ad-overlay.player-ad-overlay
https://2zra50425wzzregbr7nqy9ma6eh9ed.ext-twitch.tv
https://2zra50425wzzregbr7nqy9ma6eh9ed.ext-twitch.tv/2zra50425wzzregbr7nqy9ma6eh9ed/0.3.5/2487774cba46344a7774ba752a6b83c6/polyfills/intersection-observer.js
https://2zra50425wzzregbr7nqy9ma6eh9ed.ext-twitch.tv/2zra50425wzzregbr7nqy9ma6eh9ed/0.3.5/2487774cba46344a7774ba752a6b83c6/calendar.js
https://2zra50425wzzregbr7nqy9ma6eh9ed.ext-twitch.tv/2zra50425wzzregbr7nqy9ma6eh9ed/0.3.5/2487774cba46344a7774ba752a6b83c6/calendar.html?anchor=panel&language=en&mode=viewer&state=released
https://2zra50425wzzregbr7nqy9ma6eh9ed.ext-twitch.tv/2zra50425wzzregbr7nqy9ma6eh9ed/0.3.5/2487774cba46344a7774ba752a6b83c6/calendar.html?anchor=panel&language=en&mode=viewer&state=released
https://2zra50425wzzregbr7nqy9ma6eh9ed.ext-twitch.tv/2zra50425wzzregbr7nqy9ma6eh9ed/0.3.5/2487774cba46344a7774ba752a6b83c6/calendar.html?anchor=panel&language=en&mode=viewer&state=released
https://supervisor.ext-twitch.tv/supervisor/v1/supervisor.js
https://supervisor.ext-twitch.tv/supervisor/v1/index.html
https://extension-files.twitch.tv/helper/v1/twitch-ext.min.js

thanks

**Comment by collinbarrett** [comment]
FilterLists exists only to be an index of all available lists. We don't actually maintain any lists of rules ourselves. We are planning #33 to allow you to search to see if these rules are included on any lists already, but it'll be a bit before that's ready. In the meantime, feel free to create your own list that others can subscribe to, and I'll be happy to index it on FIlterLists.
