### ISSUE TITLE
fix viewUrl of hosts2ch

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#207]
I am having a difficult time locating the url of the actual hosts2ch list that users can subscribe to. It changed at some point in the last year, and I am having a difficult time finding it again even with Google Translate's help.

**Comment by Atavic** [comment]
Maybe is [this one](https://sites.google.com/site/logroid/files/hosts.txt) ?

**Comment by collinbarrett** [comment]
Thanks. hmm... maybe, but I think that's a different project. I have that one indexed separately. It would seem strange to have the same project on two different google sites (https://sites.google.com/site/hosts2ch/ and https://sites.google.com/site/logroid/).

**Comment by Atavic** [comment]
From a quick look on 2ch forum, logroid is linked to the old hosts2ch. Used translation BTW

**Comment by Atavic** [comment]
Wait, found this: https://sites.google.com/site/hosts2ch/ja

There's a missing MIME file type but it works.

**Comment by Atavic** [comment]
100234.advision-adnw.jp
    100602.advision-adnw.jp
    100651.advision-adnw.jp
    ...

[Weight: Low](https://github.com/collinbarrett/FilterLists/issues/209)
