### ISSUE TITLE
Dependabot spamming me on fork

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#2098]
Is there a way to disable dependabot for forks?

**Comment by collinbarrett** [comment]
Oof, looks like this might be a [known issue with Dependabot](https://github.com/dependabot/dependabot-core/issues/2198). Hmm... Will try to find some time to investigate more.

**Comment by collinbarrett** [comment]
you could try deleting `.github/dependabot.yml` from your fork. but, there should be a better solution, and not sure if that'll work.

**Comment by hawkeye116477** [comment]
That's not ideal solution, it might be problematic when doing Pull Requets, but seems that I can just do another branch for making Pull Requests and config file can be on that branch, cuz it must be present on default branch, so it won't work on another :smile:.

**Comment by collinbarrett** [comment]
will continue to monitor Dependabot features/fixes, but there's nothing I can really do about this at the moment. Dependabot provides a lot of value keeping the app's dependencies up to date.

If this remains an issue for anybody, either deleting `dependabot.yml` from the fork or deleting the fork altogether when it's not needed could be workarounds.
