### ISSUE TITLE
Search as you type

### ISSUE THREAD

**Issue by Nzzyme** [collinbarrett/FilterLists#2126]
Hello, I was checking the page (https://filterlists.com/) and wanted to give a suggestion. Currently, when we have to search for a particular filter subscription, we click on the search icon (magnifying glass icon), enter the search term and then have to click on the search button. The request is to perform a search and show the search results as soon as we type text in the search box. Is this possible?

**Comment by collinbarrett** [comment]
I agree. That would be a great feature. The current UI framework is Ant Design. I'm not sure if it supports that out of the box. I am not super strong in front-end and probably won't commit the time for this feature personally. But, happy to accept a pull request.

**Comment by collinbarrett** [comment]
Thanks for the suggestion. Unfortunately, closing as won't fix for now. Certainly open to PRs, but this is not something that I'll be personally prioritizing anytime soon. When using the column filters currently, you can also press the "Enter"/"Return" key on the keyboard rather than clicking "Ok".
