### ISSUE TITLE
add FutaFilter list

### ISSUE THREAD

**Issue by tasi788** [collinbarrett/FilterLists#2163]
https://github.com/FutaGuard/FutaFilter

cdn
https://filter.futa.gg/filter.txt
https://filter.futa.gg/hosts.txt
https://filter.futa.gg/nofarm_hosts.txt

with argo cdn
https://filter.futa.app/filter.txt
https://filter.futa.app/hosts.txt
https://filter.futa.app/nofarm_hosts.txt

**Comment by DandelionSprout** [comment]
The lists will at last be added pretty soon.

That being said, I'll give you (tasi788) an insider advice: "Futa" may mean something very normal in the ROC, but in the West it refers to futanari, which is not something an anti-ad list would usually identify with.
