### ISSUE TITLE
add btgregory's lists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#221]
https://github.com/btgregory
Per #75

**Comment by DandelionSprout** [comment]
His repo's readme claims that his lists are not intended for public use. Since I'm normally inclined to adher to such requests, should we (somehow) contact him and ask him if he wants to have his lists on FilterLists?

**Comment by collinbarrett** [comment]
Hey @btgregory , how do you feel about us indexing your lists on [filterlists.com](https://filterlists.com)?
