### ISSUE TITLE
add XPI's Filter List

### ISSUE THREAD

**Issue by troysjanda** [collinbarrett/FilterLists#2339]
Good morning I maintain the XPI Yahoocomplete list and would also like to have my other filter list added.

{
    "description": "Personal Filters to remove World Wide Web Annoyances for a better experience.",
    "homeUrl": "https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI",
    "id": 2475,
    "licenseId": 4,
    "name": "XPI's Filter List",
    "submissionUrl": "https://github.com/troysjanda/MyBlockLists/issues"
  },

Not sure what tags to put however this list blocks ads, trackers, and annoyances.

**Comment by troysjanda** [comment]
was or is there an issue with my submission, have no seen it added not trying to be pushy was just checking. :)

**Comment by collinbarrett** [comment]
Thanks for checking. No issue, we just need somebody to take the time to make a Pull Request with your change. That can be you, me, or another volunteer on the project. I just haven't had much time lately myself.

More Info:

- https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
- https://github.com/collinbarrett/FilterLists/issues/1674

**Comment by troysjanda** [comment]
I'm not sure how to do a pull request otherwise I would have.

**Comment by troysjanda** [comment]
Was added and going to close this issue
