### ISSUE TITLE
Yuki's uBlock Japanese filters - Annoyances and Annoyances+ are confused

### ISSUE THREAD

**Issue by Yuki2718** [collinbarrett/FilterLists#2361]
On `https://filterlists.com/` description of ` Annoyances+` is identical to the one of without `+`. Is this caused by some problem of handling `+`? If it's not easy to solve, I can change `+` to `Plus`.

**Comment by collinbarrett** [comment]
Ah, yes. This looks like a bug in our UI code that can't differentiate. Hmm. Yeah, if you are ok with spelling out "Plus", that might be best for now. Good catch.

**Comment by Yuki2718** [comment]
> Yeah, if you are ok with spelling out "Plus", that might be best for now.

Okay.
