### ISSUE TITLE
Add CoinBlockerLists

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#238]
There is a number of lists on that site with individual descriptions

https://zerodot1.github.io/CoinBlockerLists/

**Comment by collinbarrett** [comment]
thanks! but, dup of #146

**Comment by elypter** [comment]
sorry. i searched for "coin" in issues but that doesnt bring up anything.

**Comment by collinbarrett** [comment]
no worries, it's all good. rather have duplicates than having the db be incomplete! thanks!
