### ISSUE TITLE
add any new MajkilT lists

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#239]
add the other polish supplement lists
https://github.com/MajkiIT/polish-ads-filter#about

supplement list has be included by default in ublock
`https://github.com/AdguardTeam/AdguardBrowserExtension/issues/917`

list
`https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt`

**Comment by collinbarrett** [comment]
Thanks, I just opened #242 to address pre-processor directive relationships. FilterLists should be software-agnostic, so we still want to include all separate lists. However, we could show which other lists are `!#include`ed by software that supports it.

Keeping this issue open to ensure all of @MajkiIT 's list are indexed (we are missing a couple).

**Comment by collinbarrett** [comment]
I believe all of @MajkiIT 's lists are now correct. Please leave a comment here if any changes should be made.

**Comment by KonoromiHimaries** [comment]
@collinbarrett 
- add information about filters lists required for proper operation
- add information what adblockers are supported (internal lists and ant-dot only support ublock and adguard)

**Comment by collinbarrett** [comment]
@KonoromiHimaries 

- can you provide an example of this?
- this will be exposed via the Syntax. as long as each list has the correct SyntaxId, the new UI will show which Software supports it

**Comment by KonoromiHimaries** [comment]
> can you provide an example of this?

https://github.com/collinbarrett/FilterLists/issues/241

**Comment by KonoromiHimaries** [comment]
@collinbarrett 
- please remove the e-mail address from ant-dot, internal list, cookies, social and annoyance
- please add the discord address because that can be usefull
