### ISSUE TITLE
bad lists

### ISSUE THREAD

**Issue by jawz101** [collinbarrett/FilterLists#2394]
I've been going through all of the lists, primarily looking for host files.  Many of these lists are awful:

- 40+ are dead links
- some break things for dumb reasons
- many are combo lists based on other lists.
- many are outdated
- some are just arbitrarily throwing in personal decisions (ex: block cnn.com or foxnews.com depending on political leaning of the person even though it isn't listed as that sort of filter)

Basically, I hate it.  Personally, I would only think lists that are up-to-date, original, and useful/practical should be included.
Also, some have too many or too few entries.  If it has < 100 or > 20,000 entries it's hitting one of the bullet points I've listed.

It's really a shame for someone to add 30 lists thinking it would mean "more coverage".

But personally- I maintain a list on here and I wanted to see if some lists are finding things I may miss (maybe I only see ad companies that target my region.)  Most of these look like they were made by a kid to create an ULTIMATE BLOCKLIST forum post and just combine everyone else's list.  So then the next guy will do the same and so on.

**Comment by collinbarrett** [comment]
I hear you. I agree, there's a lot of work that can be done. But, this project is a labor of love that nobody makes any money off of. Pull Requests are always welcome.

As for the dead links, I know we have quite a few identified in #2341 . We just need to PR to remove them. If there are other specific dead links, you are welcome to open an Issue or PR identifying them specifically. Would like to automate this better with something like #21 eventually.

The goal of FilterLists was to provide a comprehensive directory of all known lists. We didn't want to necessarily make a value judgment around what lists are useful and which aren't. I'd love to provide more filtering/searching to help users find lists that are more valuable to them. Features like described in #371 would be super cool. But, finding time to work on it for free is tough.

Thanks for the feedback.

**Comment by DandelionSprout** [comment]
>some are just arbitrarily throwing in personal decisions (ex: block cnn.com or foxnews.com depending on political leaning of the person even though it isn't listed as that sort of filter)

After having gone through ~45 of the ~75 lists that meet the following criteria:
* Syntax: Hosts (localhost IPv4)
* Language: None in particular
* Tag: `ads`, while skipping those who also have `clickbait` or `anti-corp`

I feel confident in my belief that *none* of those lists are blocking `foxnews.com` or `www.foxnews.com`. If you know of any cases, they are either already marked with the `clickbait` tag (The `politics` tag is underutilised for hosts files), or would be comparatively easy for me to add that tag to.
