### ISSUE TITLE
filter lists

### ISSUE THREAD

**Issue by c2xusnpq6** [collinbarrett/FilterLists#2395]
Daily feed of bad IPs:
https://github.com/stamparm/ipsum
https://github.com/stamparm/ipsum/tree/master/levels

malware domains:
https://github.com/stamparm/blackbook/raw/master/blackbook.txt

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists

**Comment by collinbarrett** [comment]
Looks like this was added back in #2526 . Closing.
