### ISSUE TITLE
Chinese government tracking app blacklist & exaggerated news blacklist

### ISSUE THREAD

**Issue by sioxe823** [collinbarrett/FilterLists#2396]
[chinese_gov_forced_install.txt](https://github.com/sioxe823/Project-RnJlRUhL/blob/main/chinese_gov_forced_install.txt) for [`Adguard Android/iOS`](https://adguard.com/zh_tw/welcome.html)
a Chinese government tracking app blacklist

[exaggerated_news.txt](https://github.com/sioxe823/Project-RnJlRUhL/blob/main/exaggerated_news.txt) for [`Content Farm Terminator`](https://chrome.google.com/webstore/detail/content-farm-terminator/lcghoajegeldpfkfaejegfobkapnemjl) browser extension
List of domains that post exaggerated or fake or suspicious news, the list includes media belonging to the Chinese government, Apple Daily and Falun Gong
I'll add Shincheonji later

**Comment by c2xusnpq6** [comment]
Shincheonji added @collinbarrett

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
