### ISSUE TITLE
rename Polish lists

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#240]
https://github.com/MajkiIT/polish-ads-filter#about

- `Adblock & uBlock Polish Filters` change
to `Oficjalne polskie filtry do AdBlocka, uBlocka Origin i AdGuarda`
or `Official Polish filters for AdBlock, uBlock Origin & AdGuard`
or `Oficjalne polskie filtry`
or `Official Polish filters`

- `Adblock & uBlock Polish Cookies Filters` change
to `Polskie filtry ciasteczkowe`
or `Polish Cookies Filters`

- `Adblock Polish Social Rules` change
to `Polskie filtry społecznościowe`
or `Polish Social Filters`

- `Popup Blocker` change
to `Polskie filtry elementów irytujących`
or `Polish Annoyance Filters`
and add new link
`https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/PPB.txt`

**Comment by hawkeye116477** [comment]
These names were changed in beta version of page yet.
