### ISSUE TITLE
new list -> blocklists-personal.txt

### ISSUE THREAD

**Issue by scafroglia93** [collinbarrett/FilterLists#2411]
Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-personal.txt

In this list are the indicators of compromise that I find in the office among the various PCs of the company I work for

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
