### ISSUE TITLE
New Lists

### ISSUE THREAD

**Issue by DevShubam** [collinbarrett/FilterLists#2418]
AdBlocker Syntax Version: https://gitlab.com/DevShubam/blockd-filter/-/raw/main/adguard.txt

Hosts: https://gitlab.com/DevShubam/blockd-filter/-/raw/main/hosts.txt

**Comment by DandelionSprout** [comment]
The view URLs seem to have changed since the OP was originally written.

**Comment by collinbarrett** [comment]
Closing for now. @DevShubam , feel free to re-clarify which lists you are suggesting we add.
