### ISSUE TITLE
new list -> blocklists-certego

### ISSUE THREAD

**Issue by scafroglia93** [collinbarrett/FilterLists#2419]
Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-certego.txt

Born from the separation of the main list in order to follow in more detail the feeds released by the twitter account of Certego

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
