### ISSUE TITLE
new list -> blocklists-unit42-playbook

### ISSUE THREAD

**Issue by scafroglia93** [collinbarrett/FilterLists#2423]
Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-unit42-playbook.txt

Born following the reorganization of the main list in order to guarantee a better order

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
