### ISSUE TITLE
new list -> blocklists-unit42-silverterrier

### ISSUE THREAD

**Issue by scafroglia93** [collinbarrett/FilterLists#2424]
Source -> 
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-unit42-silverterrier.txt

Nigerian Business Email Compromise Update (from PanUnit42)

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
