### ISSUE TITLE
Add Elad Karako HOSTS/AdBlock (It's More than 10 MB)

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#247]
#Feature Request

Elad Karako HOSTS/AdBlock

*Three different formats:*
raw file is just a list without any prefix,
hosts.txt uses 127.0.0.1 prefix,
hosts0.txt uses 0.0.0.0 prefix.

There are 5 different lists for hiding of blocking specific ads.
The main one is listed below:

# Adding List

HOME
https://github.com/eladkarako/hosts

URL
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts.txt

*Contains 549863 badhosts !!*
**More than 10 MB**

DONATE PAGE
https://paypal.me/e1adkarak0

**Comment by collinbarrett** [comment]
dup of #119

**Comment by Atavic** [comment]
Searched for it, my bad.
