### ISSUE TITLE
ensure Subscribe links work

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#252]
tested with nano adblocker (ublock origin fork)

**Comment by collinbarrett** [comment]
hmm...

So, currently on the [beta](https://beta.filterlists.com), subscribe links are rendered like:
`abp:subscribe?location=http%3A%2F%2F1hosts.cf%2F&amp;title=1Hosts`

Using the [ABP link generator](https://adblockplus.org/en/abp_linkfactory), the same link gets generated like:
`abp:subscribe?location=http%3A%2F%2F1hosts.cf%2F&amp;title=1Hosts`

So, I think the encoded version of the ampersand is correct.


That being said, there have been issues with making sure FilterLists links are recognized by the extensions. The current beta version of the site seems to work hit-or-miss with subscribe links. I'm going to keep this issue open to address the broader scope of trying to ensure subscribe links work on the new version of the site. If anyone comes across this and has issues with subscribe links not working, please report below browser version, os version, which extension you are using, etc. Will try to fix.

More Info: https://github.com/collinbarrett/FilterLists/issues/79#issuecomment-282627707

**Comment by elypter** [comment]
it works now. looks like beta and stable site versions are the same now. if i stumble upon a list that doesnt work ill report it.

**Comment by collinbarrett** [comment]
links seem to work on various browsers/extensions I've tested. I'm going to go ahead and close for now, but let me know if you find a story where subscribe links fail.

**Comment by gwarser** [comment]
@collinbarrett you should probably revisit this `&amp;` escape. Sample link on https://adblockplus.org/en/abp_linkfactory and subscriptions on https://adblockplus.org/en/subscriptions all use `&`. uBO subscriber [was rewritten](https://github.com/uBlockOrigin/uBlock-issues/issues/763) to URL-parse subscription links and now require special handling for filterlists.com - https://github.com/gorhill/uBlock/commit/714f07dc2540cbb426bf46ee3e9c9c1913490c98

**Comment by collinbarrett** [comment]
re-opening per [this](https://github.com/uBlockOrigin/uBlock-issues/issues/763#issuecomment-692021106). I'm not sure how to fix just yet. not sure if it's a FilterLists.com issue. A uBO issue. A Chrome issue. Or something else...

**Comment by collinbarrett** [comment]
I think the remaining intermittent issue is a uBO issue that is [fixed in the latest dev build](scheme does not have a registered handler). Closing this for now.
