### ISSUE TITLE
FilterLists.com is broken again

### ISSUE THREAD

**Issue by felix-22** [collinbarrett/FilterLists#2520]
White blank page on both Firefox and Opera like in: https://github.com/collinbarrett/FilterLists/issues/1076#issuecomment-903737983 
It's not even indexed in Google anymore, so it is maybe down for several days already?
@collinbarrett

**Comment by collinbarrett** [comment]
thanks. 👀

**Comment by collinbarrett** [comment]
Not sure what happened. Were back. Thanks for the report.

**Comment by felix-22** [comment]
@collinbarrett it's broken again: 
- https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-965130681
- https://downforeveryoneorjustme.com/filterlists.com :
![y](https://user-images.githubusercontent.com/75935068/141124583-b4f1ef46-c609-416d-9c6e-6f6dad3bd81e.png)
![s](https://user-images.githubusercontent.com/75935068/141124746-faa0cb6d-d2b7-4aa5-9a66-2fcb81edc8e7.png)

**Comment by collinbarrett** [comment]
thanks, @felix-22 . I think it's fixed now. that commit ^above _should_ help prevent this particular issue in the future.
