### ISSUE TITLE
messiah.id

### ISSUE THREAD

**Issue by Hh12uGMLB** [collinbarrett/FilterLists#2539]
https://messiah.id/api/event
https://messiah.id/
https://messiah.id/js/script.js

**Comment by collinbarrett** [comment]
Is there a filter list here that can be subscribed to? I'm not sure what this site is or what you are suggesting we add/change on FilterLists.com.

**Comment by collinbarrett** [comment]
FilterLists doesn't maintain any rules. You'll need to contact an individual list author.

See here: https://github.com/collinbarrett/FilterLists#adding-or-updating-rules
