### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Kees1958** [collinbarrett/FilterLists#2551]
Small but effective adblockplus format blocklist based on the (annal) W3tech and Cookiebot surveys - Top 500

https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/Top500

is replaced by

EU US most prevalent ads & trackers ABP format

https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_ABP

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
