### ISSUE TITLE
filterlists.com api seems to be down.

### ISSUE THREAD

**Issue by eolme** [collinbarrett/FilterLists#2568]
![image](https://user-images.githubusercontent.com/11076888/135713570-660d6a36-7553-42c1-8b1c-299e6cb2e011.png)

**Comment by collinbarrett** [comment]
Thanks. I think this is now resolved. The server needed a RAM boost. Docker is RAM hungry.

**Comment by collinbarrett** [comment]
welp. hmm. maybe not _quite_ yet resolved...
