### ISSUE TITLE
new lists -> blocklists-malware-traffic

### ISSUE THREAD

**Issue by scafroglia93** [collinbarrett/FilterLists#2578]
Source -> 
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-malware-traffic.txt

**Comment by DandelionSprout** [comment]
I'll take care of adding this one this afternoon.

#2577 on the other hand would need to be added manually by you, since I'm personally not prioritising subcomponent lists (e.g. those of `blocklists-main.txt`) so far in 2021.
