### ISSUE TITLE
PopUp Block

### ISSUE THREAD

**Issue by kano1** [collinbarrett/FilterLists#264]
Block Treed party Pop ads and ads that repeat spam and malicious sites

https://raw.githubusercontent.com/kano1/I/master/popup.txt

**Comment by collinbarrett** [comment]
related to #176

**Comment by collinbarrett** [comment]
closing as dup of #176.

**Comment by kano1** [comment]
ok thank you maybe this little find the similarity with garuda speed up and it is the filter that i made
