### ISSUE TITLE
general v3 grid and modal/expander UI discussion thread

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#265]
Descriptions of lists should be exposed in the main grid, at least on desktop-width viewports.

On mobile, I think there is just no clean way to display them. Horizontal space in the grid is valuable, especially since there are several more columns that I have in the roadmap to add. Maybe descriptions can be added to hover tooltips on the lists so they do not acquire additional horizontal real estate.

**Comment by jawz101** [comment]
I would just think a description that rolls out below that list if you click on the details button instead of opening a new window.  Isn't that how it was before?

**Comment by collinbarrett** [comment]
For a brief period, I experimented with react-table's expander functionality (drop-down below the row). I ran into a couple issues with it, though, that pushed me to try the modal instead. I can't remember what those issues are, at the moment.

The new UI is all very new, and I'm certainly open to pivoting. Do you think the expander/dropdown right in the table is preferable to the modal that is currently live? If so, why?

Thanks!

**Comment by jawz101** [comment]
Less clicks and I would think it would look ok on mobile.

I keep your site as a favorite because it's the easiest way to add some of the lists on uBlock on Firefox for Android :)

Maybe it didn't look good on mobile?  I don't know if it would maybe support text wrapping so it could look ok regardless of screensize.  Maybe that was what you ran into?  Or it was more cumbersome to maintain?  Just guessing

**Comment by collinbarrett** [comment]
ok, thanks for the feedback. I think I am leaning back towards the slide-down over the modal. will play with that some more.

one of the things that I didn't like about it initially was that react-table's default implementation was to trigger the slide-down with a very small caret on the left side. it was too small to tap on mobile. but, it looks like that can easily be overridden:
https://react-table.js.org/#/story/custom-expander-position

glad that the site has been helpful for you.

**Comment by collinbarrett** [comment]
@https://github.com/IDKwhattoputhere [suggested](https://github.com/collinbarrett/FilterLists/issues/163#issuecomment-367590496) that having merge/filter by description (like is currently live for name) would be helpful.

**Comment by jawz101** [comment]
... one other thing I want to mention about the original on-hover suggestion is I'd never see them on mobile since I can't hover over things... at least I dont think I can.

**Comment by collinbarrett** [comment]
Possibly put checkboxes across top or bottom to let users dynamically hide and show columns that they want to view. [This thread](https://github.com/react-tools/react-table/issues/150) could be useful in implementing.

**Comment by collinbarrett** [comment]
closing since bulk of this issue is now solved via expander details instead of modal. any additional issues can be created anew.
