### ISSUE TITLE
expose syntax and/or software support in main list grid

### ISSUE THREAD

**Issue by jawz101** [collinbarrett/FilterLists#268]
I would think, in the least, 3 categories of lists are out there: IP blocklists, DNS blocklists, and ABP/Ublock/adguard formatted lists (I don't know what to call that.)

If the lists were categorized then add a filter button on the home page that would help quite a bit.  Also filter buttons for language.

**Comment by collinbarrett** [comment]
This is certainly in the near-term roadmap at some point. The data-layer is fleshed out (see #7), but the UI functionality is definitely not there yet. I'm going to tweak the title of the issue a tad, and use this this issue to track that.

Thanks.

**Comment by collinbarrett** [comment]
Basic support for filtering by software that supports the list just added. It may take a few hours to propagate through the caching layers. Will work on cleaning up and improving over time, but I hope this new feature is helpful to users.
