### ISSUE TITLE
fix footer links in Chromium browsers

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#2682]
The footer links in Chrome/Edge do not seem to be clickable. They are in Firefox.

**Comment by gwarser** [comment]
> They are in Firefox.

Not for me. It's because they are covered by pagination widget.

**Comment by collinbarrett** [comment]
Ah, thanks. Yeah, need to get that fixed... Front-end work is my least favorite... :)

**Comment by collinbarrett** [comment]
I _think_ it's fixed. Cleaned up some CSS a bit. Still could use love, but it's usable for now.
