### ISSUE TITLE
new list -> Anti-Q

### ISSUE THREAD

**Issue by ThePirateNerd** [collinbarrett/FilterLists#2687]
https://raw.githubusercontent.com/ThePirateNerd/Anti-Q/main/Anti-Q.txt
My home made anti Qanon list.

**Comment by collinbarrett** [comment]
Feel free to open a PR with this change if you feel so inclined. If not, another volunteer will get to it eventually.

More info:
https://github.com/collinbarrett/FilterLists#adding-or-updating-lists
