### ISSUE TITLE
add "New to FilterLists" indicator or date added

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#271]
Either show a "New" badge for new lists or show the date it was added to FilterLists. Would this be useful? It is definitely lower on my priority list, but might be nice to have.

related to #84

**Comment by somedevreally** [comment]
this feature is important to have.

**Comment by DandelionSprout** [comment]
While it sounds to me like a good idea, it'd be even better if it was then possible to sort by these dates or to have a category dedicated to new lists.

**Comment by collinbarrett** [comment]
Indeed. I think we'd add a whole data field for the date it was added that would be sortable.

**Comment by collinbarrett** [comment]
added new "Added" column with the date it was added to the latest version of FilterLists.

**Comment by collinbarrett** [comment]
Consider removing Added Date from main grid since it is pretty low value per #326

**Comment by collinbarrett** [comment]
removing the added date column, but keeping this open. the added date still displays in the details. maybe add a badge or something. the added date column provides very little value and a lot of unneeded clutter.

**Comment by collinbarrett** [comment]
Closing as duplicate into both #65 and #336
