### ISSUE TITLE
fix 1 Hosts Complete 404 viewUrl

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#2724]
https://filterlists.com/lists/1hosts-complete
https://raw.githubusercontent.com/badmojr/1Hosts/master/complete/hosts.txt

via @iam-py-test

**Comment by iam-py-test** [comment]
Thanks for the quick response @collinbarrett

**Comment by iam-py-test** [comment]
The following other urls appear to be affected:
https://filterlists.com/lists/1hosts-complete-adblockers
https://filterlists.com/lists/1hosts-complete-dnsmasq
https://filterlists.com/lists/1hosts-complete-domains-with-wildcards (just redirects to https://github.com/badmojr/1Hosts/ but mirror returns 404)
https://filterlists.com/lists/1hosts-complete-domains
1Hosts Mini does not appear affected

**Comment by iam-py-test** [comment]
I don't think there is a 1 Hosts complete anymore, based on their README anyway

**Comment by badmojr** [comment]
related: #2260

**Comment by collinbarrett** [comment]
Closing as duplicate of #2260
