### ISSUE TITLE
support filtering lists by Language ISO code(s)

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#276]
![2018-02-24-filterlists _ protect privacy be secure customize your web](https://user-images.githubusercontent.com/5884000/36633204-b3525e70-1991-11e8-8c6a-acff9d3d12fb.png)

https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by collinbarrett** [comment]
are you suggesting that we just enable filter by the ISO code in the languages column? if so, that shouldn't be too difficult. we already have the data for all the codes:

https://github.com/collinbarrett/FilterLists/blob/master/data/Language.json

**Comment by KonoromiHimaries** [comment]
@Atavic yes, alpha-2 and alpha-3
