### ISSUE TITLE
[Sugestion] Add "Last Modified or Last Updated Time" Tags or equalient feature...

### ISSUE THREAD

**Issue by t0ny54** [collinbarrett/FilterLists#2768]
[Sugestion] Add "Last Modified or Last Updated Time" Tags or equalient feature...

With that function/filter on web, user can know which filter is up to date.

Thank You

**Comment by gwarser** [comment]
https://github.com/collinbarrett/FilterLists/issues/1557

**Comment by t0ny54** [comment]
> #1557

Thank you to let me know it.
I hope it can be fixed ASAP.

Close this issue please...
