### ISSUE TITLE
remove Official Polish Filters for AdBlock, uBlock Origin & AdGuard - Test Supplement

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#277]
Created from [this](https://github.com/collinbarrett/FilterLists/issues/241#issuecomment-368262095).

> tan you remove "Official Polish Filters for AdBlock, uBlock Origin & AdGuard - Test Supplement" it's test file and have many mistakes.

@MajkiIT we do include test/experimental lists from many other maintainers as well. The goal is to index all lists available, so test/experimental are fine. That being said, if you really want it removed, I can certainly honor that request. Please confirm. Thanks!

**Comment by MajkiIT** [comment]
@collinbarrett Ok, if test/experimental filters are for you Ok, for me it's Ok. Thank you for this information.

**Comment by collinbarrett** [comment]
Cool. Thanks for maintaining all the great lists!

**Comment by MajkiIT** [comment]
@collinbarrett thanks ... you also do a great work
