### ISSUE TITLE
improve SEO of react app (sitemap.xml, etc.)

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#279]
Currently, from what I can tell in Google Search Console, googlebot does not wait around long enough to crawl the contents of the rendered react-table. This is a huge detriment to SEO, but not sure if there is a way around it.

**Comment by Atavic** [comment]
Test Page: http://www.webpagetest.org/result/180302_M1_e86aa5fc501149129cc94d8d3d42b482/

**Comment by collinbarrett** [comment]
Thanks, yeah, Webpagetest is great. However, I'm referring to how the googlebot itself renders. See screenshot below.

![image](https://user-images.githubusercontent.com/6483057/36936091-5d8c3d96-1ef8-11e8-8893-6366f92621eb.png)

**Comment by Atavic** [comment]
Ok, you did the fetch as google test. The load times are into acceptable ranges, but the culprit are the JS Scripts are big. I don't know if the limit of 101 KB still applies to googlebot, if so 

>Vendor.css
Bytes In (downloaded): 106.8 KB

may be the issue...

**Comment by Atavic** [comment]
Ok, you did the fetch as google test. The load times are into acceptable ranges.
I don't know if the limit of 101 KB still applies to googlebot, if so

    Vendor.css
    Bytes In (downloaded): 106.8 KB

may be the issue...

**Comment by collinbarrett** [comment]
Hmm, ok, thanks. Will look into that.

Because the app is React with an AJAX fetch to get the data from the API, I have also read that googlebot doesn't always wait for AJAX calls to complete. One solution is to server-side render the React components, but that seems like it is difficult to do.

**Comment by Atavic** [comment]
I'll just put a welcome page with a relevant description and a list of most known subscrpitions...
then a links to pages that actually get the data.

This project doesn't fit a single page. https://github.com/collinbarrett/FilterLists/issues/266

**Comment by collinbarrett** [comment]
Yeah, would love to have some sort of pseudo-support for clients that do not have js support. If we could just kick out a flat html table for non-js, that would be good for both Google and accessibility.

**Comment by collinbarrett** [comment]
closing. Googlebot seems to be able to crawl just fine now according to Search Console
