### ISSUE TITLE
new list -> TenCent QQ malicious URL feed

### ISSUE THREAD

**Issue by elliotwutingfeng** [collinbarrett/FilterLists#2806]
**List download link**
`https://urlsec.qq.com/cgi/risk/getlist` (JSON response)

**The above link can be found on this page:**
`https://github.com/flowerdown/tencent_url_safe_dump/blob/master/tencent_Dangerous_web.py`

**Description**
Tencent QQ, also known as QQ, is an instant messaging software service and web portal developed by the Chinese technology company Tencent. 

The above appears to be a public feed of malicious URLs, which is not publicly documented to my knowledge.

The feed is updated by TenCent at least once a day and usually has exactly `100` URLs at any given time.

As described by the `.py` source file above, each URL is categorised by threat type with the parameter `evilclass`; translations below
```
# evilclass
{
	'1' : '社工欺诈', # Phishing
	'2' : '信息诈骗', # Scam
	'3' : '虚假广告', # False Advertising
	'4' : '恶意文件', # Malicious Files
	'5' : '博彩网站', # Gambling
	'6' : '色情内容', # Pornographic content
	'7' : '垃圾信息', # Spam
	'8' : '非法内容' # Illegal content (likely to contain politically censored websites)
}
```
More information (in chinese) on the parameter `evilclass` can be found at
`https://urlsec.qq.com/eviltype.html` and `https://urlsec.qq.com/wiki/#!md/SafeQueryHttp.md`

**Comment by collinbarrett** [comment]
Still pending as we don't have a precedent for json-formatted lists, I don't think. 🤔

**Comment by elliotwutingfeng** [comment]
The list is dead!
