### ISSUE TITLE
AntiAPKMirrorCountdown 

### ISSUE THREAD

**Issue by Chaprnks** [collinbarrett/FilterLists#2812]
Unfortunately this stopped working recently. It seems APKMirror changed the detection method.

**Comment by kowith337** [comment]
I'm a maintainer of that, unfortunately, I'm rarely to use that site long time ago because almost all of my apps in mobile are mainly obtained from F-Droid and another public repos, e.g. Izzy, Bromite, etc.

I'll noted it and update later.

**Comment by collinbarrett** [comment]
Closing as it sounds like this list might not be working/active any more? Feel free to re-open if I am misunderstanding.
