### ISSUE TITLE
Add mypdns.org blocklists

### ISSUE THREAD

**Issue by Rexadev** [collinbarrett/FilterLists#2819]
https://bitbucket.org/mypdns/matrix/raw/c5d6aadd13bb4ac0c2e42c568f10962805af664b/source/adware/domains.list

**Comment by porn-records** [comment]
Hey @collinbarrett is there anyway we can help you processing this suggestion to obtain parts of our projects into your project? Like having any questions?

Ping @spirillen

**Comment by porn-records** [comment]
I know all about the time issue :) 

I'm parsing the PR to @Rexadev or @spirillen

**Comment by spirillen** [comment]
The adult part should be added, the other categories comes later, once we have control on the PR as the docs lacks some aspects about multiply contributors (maintainers) to a project there are also missing the multiply profile urls

```json
  {
    "id": 168,
    "name": "spirillen",
    "url": [
      "https://mypdns.org/spirillen",
      "https://archive.mypdns.org/p/Spirillen/",
      "https: //github.com/spirillen",
      "https://bitbucket.org/spirillen/"
    ]
  }
```

**Comment by collinbarrett** [comment]
Thanks. Looks like you figured out how to add multiple maintainers correctly. Sorry the docs might have been a bit out of date.

**Comment by spirillen** [comment]
Hey @collinbarrett Can you please reopen this issue as it is subject for changes as I'm moving my code to bitbucket / jira

**Comment by Rexadev** [comment]
https://gitlab.com/my-privacy-dns/matrix/matrix
https://bitbucket.org/mypdns/matrix/src/master/

@iam-py-test

**Comment by spirillen** [comment]
Gitlab and bitbucket are not receiving updates

**Comment by collinbarrett** [comment]
> I do believe this issue is solved with @iam-py-test PR https://github.com/collinbarrett/FilterLists/pull/3505
Closing per @spirillen . Let me know if I misunderstood and we need to reopen.
