### ISSUE TITLE
Need new facebook annoyances filters for mobile

### ISSUE THREAD

**Issue by learner007** [collinbarrett/FilterLists#282]
## Adding or Updating Lists?

I tried all of the current facebook lists on firefox mobile ublock origin. None of them removed the  "suggested groups" and some other annoyances from my feed. Then I tried the filters in this reddit post https://np.reddit.com/r/uBlockOrigin/comments/77a4je/a_couple_of_useful_filters_for_facebook/. They worked! May be they could be added to some lists.

```
! Mobile
m.facebook.com##:xpath(//div[contains(@id, 'pages_may_like_section')])
m.facebook.com##:xpath(//h3[contains(., 'Suggested Groups')]/parent::*/parent::*/parent::article)
m.facebook.com##:xpath(//span[contains(., 'Related')]/parent::*/parent::*/parent::*/parent::article)
m.facebook.com##:xpath(//h3[substring(., string-length(.) - string-length('on this.') + 1) = 'on this.']/parent::*/parent::*/parent::*/parent::*/parent::*/parent::article)
m.facebook.com##:xpath(//h3[substring(., string-length(.) - string-length('Timeline.') + 1) = 'Timeline.']/parent::*/parent::*/parent::*/parent::*/parent::*/parent::article)
m.facebook.com##:xpath(//h3[substring(., string-length(.) - string-length('liked this.') + 1) = 'liked this.']/parent::*/parent::*/parent::*/parent::*/parent::*/parent::article)
m.facebook.com##:xpath(//h3[substring(., string-length(.) - string-length('reacted to this.') + 1) = 'reacted to this.']/parent::*/parent::*/parent::*/parent::*/parent::*/parent::article)
m.facebook.com##:xpath(//h3[substring(., string-length(.) - string-length('is going to an event.') + 1) = 'is going to an event.']/parent::*/parent::*/parent::*/parent::*/parent::*/parent::*/parent::article)

```

**Comment by kowith337** [comment]
You need to report to filterlist maintainers, e.g. uAssets, EasyList, Fanboy, AdGuard, etc to update or request supports about this.

I'm agree that currently none of any filterlists handle the ads in mobile site of Facebook, perhaps almost every ppls who use android and have Facebook account(s) always use **That app**, include MESSenger.

For me, I've deleted it and keep stick to IceCatMobile or WaterFox with uBO Legacy (I'm not use FF57+ yet)

**Comment by learner007** [comment]
@kowith337 thanks, could you please link me to one of those list maintainers github? I found some but don't know if they are official or not. Thanks.

**Comment by kowith337** [comment]
As I know for common...
https://github.com/easylist/easylist
https://github.com/ryanbr/fanboy-adblock
https://github.com/uBlockOrigin/uAssets
https://github.com/AdguardTeam/AdguardFilters

**Comment by collinbarrett** [comment]
@learner007 , feel free to create your own list from that reddit thread as well, and we'll be happy to index it on FIlterLists. the bigger lists may or may not add those rules since suggested groups may not be technically advertisements or privacy violations, just annoyances.
