### ISSUE TITLE
add data change RSS feed

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#285]
you can create own list address for every list located in your base?
example.
```
redirect.filterlists.com/easylist.txt
redirect.filterlists.com/easyprivacy.txt
redirect.filterlists.com/easygermany.txt

and more..
```

to i can subscribe these address and not have to worry more about the changeability of the filter list address.

**Comment by collinbarrett** [comment]
Hmm, interesting idea. This could be interpreted two ways:

1. 301/302 redirects to the actual list URL.
Not sure off the top of my head if all of the ad-blocking software would handle this appropriately, but if they did, I don't see any problem with it. It could be kind of neat, but not sure how much real value it would provide.

2. Hosting mirrors of the lists on FilterLists.
I've thought about that in the context of #8 (hosting mirrors of custom combo lists), but hadn't seriously considered hosting mirrors of the lists themselves. The problem with this is licensing. The licenses of some lists would not permit this. In general, this might not be welcomed by some maintainers. Some maintainers, however, may welcome it as it would reduce bandwidth load for them. I don't know. I would think it would be a case-by-case basis whether the maintainers would want FilterLists to host a mirror, which might add more complexity than value.

Alternatively, maybe FilterLists could support a notification service by email or RSS for users who want to be updated when info about certain lists changes. So, if a URL of a list changes, it could send out email or RSS notifications to those who have subscribed telling them to update the URL in their ad-blocker.

**Comment by KonoromiHimaries** [comment]
> 301/302 redirects to the actual list URL.
Not sure off the top of my head if all of the ad-blocking software would handle this appropriately, but if they did, I don't see any problem with it. It could be kind of neat, but not sure how much real value it would provide.

yes this is the best option + you can use mirrors in case of troubles

> Alternatively, maybe FilterLists could support a notification service by email or RSS for users who want to be updated when info about certain lists changes. So, if a URL of a list changes, it could send out email or RSS notifications to those who have subscribed telling them to update the URL in their ad-blocker.

not everyone will be happy to follow changes, this assumption is to avoid it

**Comment by KonoromiHimaries** [comment]
if you want to create mirrors it is worth thinking about creating backups from many versions of the filter list

**Comment by Atavic** [comment]
To me the 3rd option, RSS Feed, is the best.

**Comment by KonoromiHimaries** [comment]
mayby is the best, anyway 60-85% people do not know what is it RSS and how to can use it.

**Comment by collinbarrett** [comment]
Yeah, I don't really want FilterLists to be in the business of breaking users setups if they subscribe to redirected/mirror URLs at the project goes offline. I also don't want to be in the business of collecting email addresses unless it provides real value, which I don't think it would in this case.

I think something like an RSS feed is the best option at this point. But, it is low priority and probably won't be addressed for awhile.

**Comment by collinbarrett** [comment]
The feature is very low priority, but will keep it open to maybe implement down the road. In the meantime, this is the feed to monitor to keep up with changes to data for now: https://github.com/collinbarrett/FilterLists/commits/master/data
