### ISSUE TITLE
support IE/TPL subscribe links

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#289]
For lists that target IE, change the subscribe link to match a pattern like:

`javascript:window.external.msAddTrackingProtectionList('https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl','Dandelion Sprouts norske filtre - IE-versjonen')`

Per: https://github.com/collinbarrett/FilterLists/pull/288#issue-181326721

**Comment by DandelionSprout** [comment]
My knowledge of Javascript is not particularly large (Read: not large at all), but could it have worked to turn the paragraph in src/FilterLists.Web/ClientApp/components/Home.tsx that is currently

```
function SubscribeUrl(props: any) {
    return <a href={`abp:subscribe?location=${encodeURIComponent(props.url)}&amp;title=${encodeURIComponent(props.name)}`}
              className="btn btn-primary btn-block"
              title={"Subscribe to list with browser extension supporting \"abp:\" protcool (e.g. uBlock Origin, AdBlock Plus)."}>
               Subscribe
           </a>;
}
```

into

```
function SubscribeUrl(props: any) {
 if syntaxId = "10"
    return <a href={`javascript:window.external.msAddTrackingProtectionList('${encodeURIComponent(props.url)}', '${encodeURIComponent(props.name)}')`}
              className="btn btn-primary btn-block"
              title={"Subscribe to list with Internet Explorer's Tracking Protection List system."}>
               Subscribe
 else return <a href={`abp:subscribe?location=${encodeURIComponent(props.url)}&amp;title=${encodeURIComponent(props.name)}`}
              className="btn btn-primary btn-block"
              title={"Subscribe to list with browser extension supporting \"abp:\" protcool (e.g. uBlock Origin, AdBlock Plus)."}>
               Subscribe
           </a>;
}
```

or to something similar?

**Comment by DandelionSprout** [comment]
As I have at last decided to buckle up and do some field testing with IE 11, there are a few obstacles that could make this a bit more complicated to achieve than I thought.

1) The required subscription link format is much more convoluted and narrow than I thought it would be, as it appears that the link has to be formatted á la `<a href="javascript:window.external.msAddTrackingProtectionList('https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl', 'Dandelion Sprouts norske filtre - IE-versjonen')">Subscribe</a>`, and I am not sure how easy it'd be to pack two cases of `${encodeURIComponent(props.(...))}` into such links or not. I'll attempt to edit my comment above on the assumption that it's easy enough.

2) It seems that Internet Explorer is not actually able to load FilterLists.com properly on my end, showing "Loading..." for a split-second and then a white screen.

**Comment by collinbarrett** [comment]
Hmm, ok, thanks for that. Honestly, since IE has been essentially discontinued in favor of Edge, I think adding this feature is probably super low priority. I just wanted to at least consider it.

**Comment by collinbarrett** [comment]
Closing as won't fix due to IE deprecation. Can still flag lists targeting IE per [proposed `browser` tag](https://github.com/collinbarrett/FilterLists/issues/65#issuecomment-277455952).

**Comment by collinbarrett** [comment]
re-opening per https://github.com/collinbarrett/FilterLists/pull/507#issue-217465713

**Comment by collinbarrett** [comment]
Combining into #28
