### ISSUE TITLE
add NSABlocklist by CHEF-KOCH

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#297]
please add

https://github.com/CHEF-KOCH/NSABlocklist

**Comment by CHEF-KOCH** [comment]
The list get merged together with other filters into the [CKs-FilterList repository](https://github.com/CHEF-KOCH/CKs-FilterList).

It would be better to pick my filters from there, cause this will be the repo which more often gets updates. 

Thanks for mention my list here.

**Comment by elypter** [comment]
i couldnt find the nsa list in there. did it really get merged? also i think it would be great to have this list individually as well

**Comment by CHEF-KOCH** [comment]
Well, I said 'get' merged, not that it is already, but yes I'm working on it. 

All lists I provide are also seperate avaible in their specific folders.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/commit/40fe6e058f99faa45b32a1cb318587038e85d5a5
