### ISSUE TITLE
add Energized lists and their upstream lists

### ISSUE THREAD

**Issue by AdroitAdorKhan** [collinbarrett/FilterLists#299]
Hey, would you mind adding [Energized - ad.porn.malware protection.](https://github.com/AdroitAdorKhan/Energized) to the Filterlists?

TIA!

**Comment by Atavic** [comment]
Good proposal that has various options, from heavy to light ones. I looked at the first one, called Energized Package:

Package | Sources |
---------------- |:------:|
**Energized** | *AdAway, add.2o7Net, add.Dead, Ador, AdZHosts, Anti-PopAds, Badd-Boyz-Hosts, Global Advert Server PE, Streaming Ads, hpHosts Ads, KADhosts, MoaAB, MVPS.ORG, NSABlocklist, R-A-Y Mobile Hosts, Shallalist Adv, Gamble, Drugs & Alcohol, someonewhocares, StevenBlack, UncheckyAds, YousList, YoYo.org, YTAds and YTVideoAds* |

Of [these sources](https://github.com/AdroitAdorKhan/Energized#thanks-to--) I can't find the following in FilterLists:

Ador, Badd-Boyz-Hosts, R-A-Y Mobile Hosts, Shallalist Adv, Gamble, Drugs & Alcohol
YTAds.

Moreover, I can't find the sources of *Gamble, Drugs & Alcohol*: https://github.com/AdroitAdorKhan/Energized/issues/31

**Comment by Atavic** [comment]
Good proposal that has various options, from heavy to light ones.
I looked at the first one, called Energized Package:

Package | Sources |
---------------- |:------:|
**Energized** | *AdAway, add.2o7Net, add.Dead, Ador, AdZHosts, Anti-PopAds, Badd-Boyz-Hosts, Global Advert Server PE, Streaming Ads, hpHosts Ads, KADhosts, MoaAB, MVPS.ORG, NSABlocklist, R-A-Y Mobile Hosts, Shallalist Adv, Gamble, Drugs & Alcohol, someonewhocares, StevenBlack, UncheckyAds, YousList, YoYo.org, YTAds and YTVideoAds* |

Of [these sources](https://github.com/AdroitAdorKhan/Energized#thanks-to--) I can't find the following in FilterLists:

Ador, Badd-Boyz-Hosts, R-A-Y Mobile Hosts, Shallalist Adv, Gamble, Drugs & Alcohol,
YTAds.

Moreover, I can't find the sources of *Gamble, Drugs & Alcohol*: https://github.com/AdroitAdorKhan/Energized/issues/31

**Comment by AdroitAdorKhan** [comment]
I have answered your question! ;)

Main reason was, unavailability of updated source. I will add them back, once I clear things up! Wait bit more! 

#Stay Energized!

**Comment by AdroitAdorKhan** [comment]
Do I need to provide anymore info, to get place in Filterlists?

**Comment by collinbarrett** [comment]
All of the data about lists that we index is available [here]((https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar). If you can provide as much of that info in this Issue that is available, that would be the most helpful. Feel free to even submit a Pull Request with your updates against [data](https://github.com/collinbarrett/FilterLists/tree/master/data) yourself if you can. Let me know if you have questions.

**Comment by r-a-y** [comment]
Glad to see my [HOSTS filters](https://github.com/r-a-y/mobile-hosts) being mentioned here.  I didn't advertise them anywhere, so I'm kind of surprised :slightly_smiling_face:

**Comment by AdroitAdorKhan** [comment]
@r-a-y yea! and, your script is amazingly, amazing! :D

**Comment by AdroitAdorKhan** [comment]
Name: **Energized Ad Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedAd/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Adware Blockings.

Name: **Energized Malware Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedMalware/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Malware Blockings.

Name: **Energized Porn Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedPorn/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Pornware Blockings.

Name: **Energized Blu **
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedBlu
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedBlu/master/energized/blu
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Lightweight Energized Protection.

Name: **Energized Blu **
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedBlu
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedBlu/master/energized/blu_go
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized GO!

Name: **Energized Lite Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedLite/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Adware & Malware Basic.

Name: **Energized Porn Lite Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedPornLite/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Pornware Basic.

Name: **Energized Ultimate Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedUltimate/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Adware & Malware Protection.

Name: **Energized Unified Protection**
Home Page: https://ador.chorompotro.com/energized
Source: https://github.com/EnergizedProtection/EnergizedHosts
Raw Source/ Download URL: https://raw.githubusercontent.com/EnergizedProtection/EnergizedHosts/master/EnergizedUnified/energized/hosts
Language: EN-US
Maintainer: AdroitAdorKhan
Maintainer Email: mail.energized@protonmail.com
License: MIT
First Published: May 1, 2018
Use Permission: Free to use for non-commercial purposes.
Description: Energized Adware, Malware & Pornware Protection.

**Comment by AdroitAdorKhan** [comment]
@collinbarrett hope previous comment covers all the info you need!

**Comment by collinbarrett** [comment]
Looks great. I'm on vacation, so it'll be a week at least before I can add them. Thanks.

-------- Original Message --------

**Comment by AdroitAdorKhan** [comment]
Sure! Take your time! and let me know if you need any more info! ;) 
And one more thing, Energized got multiple formats! Like, Hosts RAW, TXT, ANDROID FLASHABLE ZIP, MAGISK, WINDOWS BAT INSTALLER, DNSMASQ, DNSMASQ IPV6, and UNBOUND CONF as well!

**Comment by AdroitAdorKhan** [comment]
@collinbarrett any progress?

**Comment by collinbarrett** [comment]
Not yet, sorry. If you have time, feel free to submit a Pull Request. Take a look at #304 for an example.

**Comment by AdroitAdorKhan** [comment]
The info I provided, isn't enough? I don't have my pc with me, to perfectly do github things and pull a request. :pensive:

**Comment by collinbarrett** [comment]
what you provided is great, it'll just take copy/paste over into the json format. I'll try to get to it when I can.

**Comment by AdroitAdorKhan** [comment]
Sure! That would be so kind of you!

**Comment by AdroitAdorKhan** [comment]
Hey Energized Infos needs to be updated! Should I fork the repo and modify this [file](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json)?

**Comment by collinbarrett** [comment]
Yes, feel free to submit a PR [modifying any of these files](https://github.com/collinbarrett/FilterLists/tree/master/data). [Here are the docs](https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar).

**Comment by AdroitAdorKhan** [comment]
Alright, I'm on it! ;)

**Comment by AdroitAdorKhan** [comment]
Done!

**Comment by collinbarrett** [comment]
closed by #482
