### ISSUE TITLE
add PolishAnnoyanceFilters Modules

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#307]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/

**Comment by collinbarrett** [comment]
This issue is to index each module individually. The compiled list is already indexed as [list 30](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json).

**Comment by hawkeye116477** [comment]
New link to modules => `https://polishannoyancefilters.netlify.com/modules` .

**Comment by collinbarrett** [comment]
closing per https://github.com/collinbarrett/FilterLists/pull/564#issue-220883668
