### ISSUE TITLE
add Subscribe button column and support filtering by viewUrl

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#311]
![2018-06-30-filterlists _ subscriptions for ublock origin adblock plus adguard](https://user-images.githubusercontent.com/5884000/42129098-9c178676-7cbb-11e8-99af-5bce12f37b83.png)

**Comment by collinbarrett** [comment]
may be more easily supported after #336

**Comment by collinbarrett** [comment]
This could also be somewhat easily done as a filter over the "Subscribe" column. It wouldn't actually show the URL of the filtered results, but since the Subscribe button is based on the `viewUrl`, it could support filtering...
