### ISSUE TITLE
fix horizontal overflow on mobile

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#313]
The name column is not auto-resizing properly to allow the full table width to display on mobile without scrolling. There should be no horizontal scrolling on narrow viewports; the Name column should shrink as much as is needed to accomplish this.

![mobileoverflowbug_filterlists](https://user-images.githubusercontent.com/6483057/42247526-bb8f26ba-7f10-11e8-9249-cd704f0b5670.jpg)

**Comment by DandelionSprout** [comment]
The page elements _rt-thead -header_, _rt-head -filters_, and _rt-tbody_ are currently all set to have a minimum width (min-width) of 560px. Changing the _min-width_ value for all of them to e.g. 400px seems to fix the problem on extra narrow screens such as phones.

**Comment by DandelionSprout** [comment]
![image](https://user-images.githubusercontent.com/22780683/42425189-8c50c900-8319-11e8-860e-a65899d8ea40.png)

**Comment by collinbarrett** [comment]
thanks, @DandelionSprout . i'll have to see if I can tweak that. I'm using the https://github.com/react-tools/react-table and I think those widths are generated on the fly.

this is a fairly critical bug since the site is pretty unusable on mobile right now.

**Comment by collinbarrett** [comment]
Yes! That last commit seems to have finally solved it! I hate css...
