### ISSUE TITLE
Ublock Origin are consuming so much resource

### ISSUE THREAD

**Issue by mozkan007** [collinbarrett/FilterLists#314]
Hi, I am using your filterlist.com page for my  Ublock Origin but I have a problem about it. I added 191 custom filter subscription from your page into Ublock as the custom filters. So as of today, the total number of all filters are nearly 2.5000.000 and Ublock has started  to consume too much cpu and ram resource and also the web pages which I visit are loading too late because there is a information at the bottom of the screen saying that waiting for Ublock extension to load the site. I reported this  problem to the owner of Ublock and he said that you should decrease the number of the filter subscriptions becausyou have a huge subscription and they are making Ublock bulky. Actually I do not want to disable these filters because they are great filters. So what should I do? So I mean that is there a way to solve the problem without disable the filters? Thanks.

**Comment by collinbarrett** [comment]
It's really a trade-off between how much coverage you want (how many filter lists and therefore rules you want) and how much resources you want to commit to uBlock. FilterLists is merely a directory to provide folks with a place to find lists. I don't recommend subscribing to all or even a majority at the same time. My personal install of uBlock Origin only has a handful of custom lists outside of those shipped with UBO.

I hope to add more data to FilterLists at some point that shows which lists overlap each other (although UBO de-duplicates rules for you anyway) as well as which lists have a lot of obsolete rules (#303 ) which could be helpful.

Hope that helps.
