### ISSUE TITLE
support filtering grid by syntax and/or software support

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#316]
Background story: While working on #304, I discovered that there were a whole lot of domains lists that would've worked perfectly well in Personal Blocklist, presuming that it wouldn't have made that extension crash (I've honestly been too afraid of testing, as of at the time of writing), and it made me realise that there currently are limited methods on FilterLists.com to search by list syntax.

While uBO and Nano can use perhaps 98-99% of the lists on FilterLists, it's a different story for other extensions. For instance, Adblock Plus can only use Adblock Plus-formatted lists, AdAway and other hosts-file tools can only use hosts lists, Internet Explorer's TPL system can only use TPL, and Personal Blocklist can only use domains lists. I think that those who are looking for lists for such extensions and programs, would therefore have found it beneficial to be able to search by list syntaxes.

I am not particularly good at coding, and therefore don't consider myself able to do a proper pull request to add such a category, but I presume there'd be needed to tie short keywords that'd be easy to search for, to the entries in either Syntax.js or Software.js, such as "abp", "ublock", "hosts", "tpl", "adblock", or whatever else you see fit.

I have been somewhat able to filter syntaxes on the website through searching by name, such as with "hosts" and "tpl", but it's not an ideal solution, since it omits a fair few lists that incidentally don't have such words in their names.

**Comment by jawz101** [comment]
I'd just do categories based on syntax rather than categorize by tool.  There are a million tools out there and not listing the one you do use would make it annoying to think it doesn't apply to you.

**Comment by elypter** [comment]
i would provide the list of formats and allow the user to check each one. above that could be a combobox with popular tools. once you select one it automatically ticks all the correct boxes for you.

**Comment by collinbarrett** [comment]
may be more easily supported after #336

**Comment by collinbarrett** [comment]
rudimentary support for this now implemented. will cleanup/improve over time.
