### ISSUE TITLE
add hblock hosts and its upstream lists

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#319]
https://hblock.molinero.xyz/

**Comment by DandelionSprout** [comment]
Almost all of the lists that it credits in its [Sources](https://github.com/hectorm/hblock#sources) section are already on FilterLists.com by themselves. So as far as I am personally concerned, the focus should be on adding those of the credited lists that aren't on FilterLists.com yet (for instance Badd Boyz Hosts).
