### ISSUE TITLE
if I was the webmaster of filterlists.com...

### ISSUE THREAD

**Issue by dialexg91** [collinbarrett/FilterLists#3375]
... I'd delete this filter:

https://filterlists.com/lists/stop-autoplay-on-video-sites

because it definitely doesn't work

**Comment by gwarser** [comment]
It prevents autoplaying next video. Works fine on YT.

@DandelionSprout ?

**Comment by DandelionSprout** [comment]
I know the list has been struggling on many sites, but it indeed works most of the time on YouTube from what I've observed over the past year or two.

To dialexg91: If you wish to do so, could you fill out a report of what doesn't work about that list at https://github.com/DandelionSprout/adfilt/issues/new?assignees=&labels=Problem+report&template=problem-report-form.yml, and I'll see how easy it'd be to fix it?

**Comment by collinbarrett** [comment]
Closing as won't change for now.
