### ISSUE TITLE
is there a filter that really blocks ads??

### ISSUE THREAD

**Issue by dialexg91** [collinbarrett/FilterLists#3376]
I'm using a browser called Midori for Android and I tried manually adding uBlock filters, AdGuard filters, Adblock Plus Filters, Dandelion Sprout, Web Annoyances Ultralist and I still see banners, pop-ups and ads on videos (even YouTube), and even a filter called "Block Everything!" but nothing (that last one should be renamed because of that), is there a filter that can block ALL the ads and annoyances or blocking all of them it's really impossible??

**Comment by gwarser** [comment]
This Midori? https://www.reddit.com/r/androidapps/comments/iqztdm/midori_browser_for_android/

From how it looks, it can inject these ads by itself. Looks outdated, and I doubt it supports EasyList syntax.

**Comment by collinbarrett** [comment]
Closing as off topic. FilterLists.com doesn't recommend any particular list(s). It is purely a directory.
