### ISSUE TITLE
Remove deprecated lists and add new one

### ISSUE THREAD

**Issue by ammnt** [collinbarrett/FilterLists#3498]
Hi!

Please remove my old deprecated lists:
https://filterlists.com/lists/ammonitefilter
https://filterlists.com/lists/trilobitefilter

And add this one:
https://github.com/ammnt/DeadEnd
Direct URL here:
https://raw.githubusercontent.com/ammnt/DeadEnd/main/filter.txt
Tags: tracking, privacy, protection, filter, advertisement, blocking, ads, hosts, adblock, counters, advertising, adware, trackers, banners, adguard etc.
Syntax: adblock
License: GPL-3.0
Software: AdGuard Home
Home: https://github.com/ammnt/DeadEnd

Thank you.
Best regards👏🏼

**Comment by skyboi1233** [comment]
I want to keep my accounts 


Sent from Yahoo Mail for iPhone


On Sunday, April 2, 2023, 2:58 AM, ammnt ***@***.***> wrote:




Hi!

Please remove my old deprecated lists:
https://filterlists.com/lists/ammonitefilter
https://filterlists.com/lists/trilobitefilter

And add this one:
https://github.com/ammnt/DeadEnd
Direct URL here:
https://raw.githubusercontent.com/ammnt/DeadEnd/main/filter.txt
Tags: tracking, privacy, protection, filter, advertisement, blocking, ads, hosts, adblock, counters, advertising, adware, trackers, banners, adguard etc.
Syntax: adblock
License: GPL-3.0
Software: AdGuard Home
Home: https://github.com/ammnt/DeadEnd

Thank you.
Best regards👏🏼

**Comment by skyboi1233** [comment]
I won't to erase all my accounts from github. Someone else is using it to take over my account. So it's easier to get ready of this site..  Y'all can't secure my information so why stay with y'all I losing everything Skyler Williams 


Sent from Yahoo Mail for iPhone


On Sunday, April 2, 2023, 3:10 AM, Skyler Williams ***@***.***> wrote:



I want to keep my accounts 


Sent from Yahoo Mail for iPhone


On Sunday, April 2, 2023, 2:58 AM, ammnt ***@***.***> wrote:




Hi!

Please remove my old deprecated lists:
https://filterlists.com/lists/ammonitefilter
https://filterlists.com/lists/trilobitefilter

And add this one:
https://github.com/ammnt/DeadEnd
Direct URL here:
https://raw.githubusercontent.com/ammnt/DeadEnd/main/filter.txt
Tags: tracking, privacy, protection, filter, advertisement, blocking, ads, hosts, adblock, counters, advertising, adware, trackers, banners, adguard etc.
Syntax: adblock
License: GPL-3.0
Software: AdGuard Home
Home: https://github.com/ammnt/DeadEnd

Thank you.
Best regards👏🏼
