### ISSUE TITLE
support viewUrl mirrors

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#355]
There are a few lists for whom there exists mirrors (Both official and unofficial ones) or alternate links, so I figured that it could've been convenient to become technically able to add extra links to those lists for users who have connection problems or technical problems.

Significant examples:

- [X] MVPS Hosts — Manually updated unofficial HTTPS mirror by Steven Black — https://raw.githubusercontent.com/StevenBlack/hosts/master/data/mvps.org/hosts
- [X] ~~Malware Domain Hosts List — Auto-updated mirror by a jspenguin2017-designed bot — https://cdn.rawgit.com/NanoMeow/MDLMirror/master/hosts.txt~~ [fork (separate entry in FilterList.json), not a mirror, as it is a different syntax]
- [X] ~~Malware Domain Hosts List — An ABP-formatted version from the same mirror — https://cdn.rawgit.com/NanoMeow/MDLMirror/master/filter.txt~~ [fork (separate entry in FilterList.json), not a mirror, as it is a different syntax]
- [X] ~~Dan Pollock's Hosts — A version that adds IPv6 entries by default — https://someonewhocares.org/hosts/ipv6/hosts~~ [fork (separate entry in FilterList.json), not a mirror, as it is a different syntax]
- [X] Google Hosts — Official mirror — https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts-files/hosts
- [X] DNS-BH Malware Domains — Presumably official mirror — https://mirror.cedia.org.ec/malwaredomains/justdomains
- [X] ~~EasyList Lithuania — HTTP backup link, as I randomly discovered that Tor Browser does not recognise margevicius.lt's SSH certificate, despite it being recognised by both Chrome and Firefox — http://margevicius.lt/easylistlithuania.txt~~ [hesitating on this one, since it's the same url, just a different protocol... not really a mirror. not sure how to best capture this]

There are other examples as well, but these examples sums up the gist of it. This idea was also inspired in no small part by how I discovered that [uBlock Origin's asset list](https://github.com/gorhill/uBlock/blob/master/assets/assets.json) supports multiple links per list (In one case as many as six).

Oh, and I do also appreciate all the compliments you've given me for my pull requests, but I simply had no idea what to reply to them with, nor were there any good emotes among GitHub's 6 reaction emotes that were befitting for it.

**Comment by collinbarrett** [comment]
added forth-coming 2x mirrors to wiki: https://github.com/collinbarrett/FilterLists/wiki/FilterList

**Comment by collinbarrett** [comment]
Infrastructure now in place, and added some of the samples in the OP in https://github.com/collinbarrett/FilterLists/commit/a91ac0b433545f3f3967a7caac4030bd6ae8243a. Mirrors should really be a true mirror. If the list is a variant (different syntax, for example), we should capture it as a separate list and link them as a `fork`.

**Comment by collinbarrett** [comment]
opened #467 for the UI work, but PRs can now be submitted for mirrors.
