### ISSUE TITLE
new filter: Ukrainian Security Filter

### ISSUE THREAD

**Issue by serhiyguryev** [collinbarrett/FilterLists#3596]
Our team (NGO "Social Innovators", Kyiv, Ukraine) is maintaining Ukrainian Security Filter — filter of malicious web resources (phishing, online fraud, malware, etc.) targeting Ukrainian citizens (these web resources are not available in other filters): https://github.com/braveinnovators/ukrainian-security-filter

We use the following sources of reliable information: our own monitoring team, Computer Emergency Response Team of Ukraine (CERT-UA), EMA BlackList (Ukrainian Interbank Payment Systems Member Association "EMA").

Below I provide the information according to the data model:

Ukrainian Security Filter (Adblock-style syntax): https://raw.githubusercontent.com/braveinnovators/ukrainian-security-filter/main/lists/adblock.txt

**FilterList.json**:
name: Ukrainian Security Filter (Adblock-style syntax)
description: Filter of malicious web resources (phishing, online fraud, malware, etc.) targeting Ukrainian citizens
homeUrl: https://github.com/braveinnovators/ukrainian-security-filter
issuesUrl: https://github.com/braveinnovators/ukrainian-security-filter/issues
licenseId: 4

**FilterListTag.json**:
"tagId": 7 (phishing)

**Comment by serhiyguryev** [comment]
@LambLeeg, could you explain the motivation for choosing this emoji?

![Screenshot_20230812_112043](https://github.com/collinbarrett/FilterLists/assets/59440343/a12f475b-80a4-4df8-9254-b20ad5bbcaf7)

**Comment by LambLeeg** [comment]
> @LambLeeg, could you explain the motivation for choosing this emoji?
> 
> ![Screenshot_20230812_112043](https://github.com/collinbarrett/FilterLists/assets/59440343/a12f475b-80a4-4df8-9254-b20ad5bbcaf7)

Sure, it had a couple of false positives. Currently it has no problems. Hence, I unchecked it.

**Comment by serhiyguryev** [comment]
@LambLeeg,
> Sure, it had a couple of false positives. Currently it has no problems. Hence, I unchecked it.

I'm curious, which sites did you have problems with?

In any case, I believe that reporting problems (https://github.com/braveinnovators/url-blocklist/issues) is much more effective than putting negative emoji without any explanation.

**Comment by serhiyguryev** [comment]
Today I opened a pull request ( #4111), so this issue is no actual
