### ISSUE TITLE
my Filterlist

### ISSUE THREAD

**Issue by www-k9** [collinbarrett/FilterLists#3597]
Arabic Filterlist

download :
https://raw.githubusercontent.com/www-k9/hosts/master/hosts

repository :
https://github.com/www-k9/hosts

**Comment by iam-py-test** [comment]
I'm working on a PR to add this, but I have a few questions
- What should it be called? (the name has the be unique, but there aren't a ton of other restrictions, as far as I am aware of)
- What description should I add?

**Comment by www-k9** [comment]
> I'm working on a PR to add this, but I have a few questions
> 
Thank you for that

>     * What should it be called? (the name has the be unique, but there aren't a ton of other restrictions, as far as I am aware of)
> 
may we call it " WWW-K9 " ?

>     * What description should I add?

We Are Targeting Arabic Content And Sites Not Listed In StevenBlack/hosts

Porn - Gambling - Social and Dating - Illegal - Phishing

ـــــــــــــ

نحن نسعى لتنقيح المحتوى العربى ، بالاضافى الى المواقع الغير مدرجة فى مشروع StevenBlack/hosts

الاباحية - المقامرة - التواصل و المواعدة - الغير قانونية - التصايد و الاحتيال

**Comment by iam-py-test** [comment]
There aren't categories for dating websites or "illegal" content (illegal varies from area to area, making this a hard-to-define and subjective category).

**Comment by www-k9** [comment]
Thank You

**Comment by collinbarrett** [comment]
closed by #3601
