### ISSUE TITLE
auto-connect E-mail addresses to maintainer IDs

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#373]
I got an idea. 

If a filterlist in FilterList.json has both an E-mail address and is listed in FilterListMaintainer.json, then all other lists with the same E-mail address would be auto-assigned the same maintainer ID. This will help with avoiding cases where lists occasionally aren't accredited to specific maintainers, when most of their other lists are.

This can to a smaller degree also be done with the existing `emailAddress` field in Maintainer.json.

**Comment by DandelionSprout** [comment]
Alternately, maintainer IDs could be generated based on E-mail addresses. It'd save the hassle of dealing with `Maintainer.json` and `FilterListMaintainer.json`, although it'd mean that lists would be accredited to E-mail addresses (i.e. "More lists by example@example.com:") until proper names are added to those maintainer IDs later on.

**Comment by collinbarrett** [comment]
I like the idea, but should probably be addressed as part of #372 . Not sure it carries priority enough to warrant custom dev time outside of that.
