### ISSUE TITLE
Rakuten (formerly Ebates) link update

### ISSUE THREAD

**Issue by snhv** [collinbarrett/FilterLists#3794]
Hi, Ebates is now Rakuten. The current subscription for Ebates (https://filterlists.com/lists/ebates-cash-back-shopping) is no longer working. It is now at:
https://www.rakuten.ca/static/cashback-shopping-whitelist?title=Rakuten%20Cash%20Back%20Shopping

Thanks!

**Comment by iam-py-test** [comment]
In my opinion, this filterlist should not be listed at all.
This list was blocklisted in uBlock Origin - and for good reason. It's sole purpose is to trick users into opening themselves up to tracking and ads.

**Comment by snhv** [comment]
Without the whitelist, the cashback does not work. The users must know full well of their intention, which is to collect cash back, when they THEMSELVES MANUALLY add the whitelist. I say have the list there and let people decide.

**Comment by iam-py-test** [comment]
I understand, but I fail to see how doubleclick is needed for a cash back extension. I'm not saying there isn't a need, I just think this list goes above and beyond in allowlisting redirect trackers.
At least this list is better than their old ones, as it seems to only

**Comment by stephenhawk8054** [comment]
If you want to use the cashback, it's better to turn off uBO or use another browser profile without uBO for it. Adding these cashback lists to uBO defeats the whole goal of uBO and just makes it useless because they opens up trackers and ads connections **everywhere**.

**Comment by collinbarrett** [comment]
closed by #4349
