### ISSUE TITLE
Website not opening. 😭

### ISSUE THREAD

**Issue by ghost** [collinbarrett/FilterLists#3835]
Sir, last 48 hours this website not opening. Kindly resolve the issue. 🙏

**Comment by Thomashighbaugh** [comment]
Yeah I am getting the same here. It just shows the loading spinner indefinitely for me on Linux+Firefox (most recent version)

**Comment by collinbarrett** [comment]
And, we're back. Thanks for reporting! Sorry, all. We were bit by #3316 again. I need to get that fixed.
