### ISSUE TITLE
support Id ranges in JSON files

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#384]
For the purposes of saving small bits of time and space when dealing with `FilterListMaintainer.json`, `FilterListLanguage.json` and `FilterListTag.json`, would it be possible to add support for number ranges in ID values?

So that instead of writing (in this example):
```
  {
    "filterListId": 356,
    "tagId": 9
  },
  {
    "filterListId": 357,
    "tagId": 9
  },
  {
    "filterListId": 358,
    "tagId": 9
  },
  {
    "filterListId": 359,
    "tagId": 9
  },
```

...it could be written as:

```
  {
    "filterListId": 356-359,
    "tagId": 9
  },
```

I have no real idea if it's even possible to do so in a JSON file, however.

**Comment by collinbarrett** [comment]
Hmm... It could be possible, but I think it may take more work than it's worth. And, as it stands now, the json is a replicated model of the RDBMS used in the production application. This feature would de-normalize the data to some extent...

But, will think on it for a bit.

**Comment by collinbarrett** [comment]
While I certainly see the desire, I think focusing more on something like a #372 is a better use of our time, and would obsolete these changes.

Thanks for the suggestion, though.
