### ISSUE TITLE
add "topical" tag

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#385]
I see that you've settled on [a set of tags](https://github.com/collinbarrett/FilterLists/blob/master/data/Tag.json) for now, and I chose to fully conform tonight's pull request to within that set, and to not create any new tags.

But even with that in mind, there is one tag that I'd want to be able to use, and that I suppose that I'll have to ask you for permission to include: _topic block_ (or _topical block_), with the possible description of "Blocks specific topics/things."

The entries in that category would be:
Anti-FіМ List
Anti-IMDB List
I Don't Care About Emojis
Message "Seen" Remover for Facebook
Lead Generator
Polish RSS Filters
Rickroll Blacklist
I Hate Overpromoted Games
YouTube: Remove Youtube Suggestions

**Comment by collinbarrett** [comment]
I like it. Let's do it. They are certainly not set in stone, and I think we should add more that are useful. If you feel so inclined, feel free to add it in a PR like you've been doing. If not, we'll leave this open until myself or somebody else adds it.

related to #65

**Comment by collinbarrett** [comment]
Let's go with just `topical` for the name, for brevity.

**Comment by DandelionSprout** [comment]
Ah, thanks, and okay. I'll get around to adding the "topical" tag and possibly one or two other ones.

**Comment by collinbarrett** [comment]
closed by #383
