### ISSUE TITLE
add indexes to rules.Raw

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#395]
We are using MariaDB (fork of MySQL) as the RDBMS.

I am thinking we'll want a `FULLTEXT` index on `rules`.`Raw` to support #33 . I think we'll also want a normal index with a fixed prefix size on `rules`.`Raw` for ongoing support of [SnapshotService](https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Services/Snapshot). Both of these indexes should be added once the initial ingestion into `rules` is complete and stable.

But, I am new to indexing, so I am certainly open to feedback on this.

**Comment by Atavic** [comment]
What's this rules.raw thing?

**Comment by collinbarrett** [comment]
`rules` is the name of the table in the RDBMS modeled like [this](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Data/Entities/Rule.cs). `Raw` is the column name that contains each unique line from a FilterList (could be an actual rule, could be a comment, could be metadata - #202).

For example:
![rulesraw](https://user-images.githubusercontent.com/6483057/45266229-40583380-b447-11e8-997a-60e2d519ec68.png)
