### ISSUE TITLE
handle offline lists with no Wayback Machine archive

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#404]
List Id 16 (https://raw.githubusercontent.com/SlowMemory/List-KR/master/filter.txt) is both offline and does not have a Wayback Machine archive (unlike its sibling list 15). Should we remove the list altogether? My thinking is probably yes, unless we find an alternate archive provider.

Keeping a list in the index that is no longer available in any form or fashion provides essentially no value to users.

**Comment by DandelionSprout** [comment]
After comparing various forks of it, it seems to me that the fork by _andromedarabbit_ continues to be decently well maintained. https://github.com/andromedarabbit/List-KR

**Comment by collinbarrett** [comment]
Good idea, I didn't think to consider forks...

Hmm, will need to think about how to capture that if we do. If it's a fork, we should maybe treat it like a separate list (with a Fork relationship back to the original (that we are considering removing)).

I just wouldn't want to present it as the original when it is actually a fork by another maintainer.

**Comment by collinbarrett** [comment]
I think we'll handle these on a case-by-case basis. For now, I like the idea of changing the list to a fork. I went with the base fork to keep it as pure to the original as possible. And, I'm comfortable with replacing it because it is a real fork (with the original authors commits).
