### ISSUE TITLE
add direct URL links for tags (and languages?)

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#406]
Hypothetical scenario: Let's say I receive an issue report for my list(s), by an enthusiast who desperately wants me to add filters for cookie notifications, which is a topic that my lists only partially aim to deal with.

As it stands now, I'd have directed him/her to check out the _I Don't Care About Cookies_ list. But to pre-emptively help prevent further complaints from him/her that the list doesn't work or something like that, then it could've been convenient if I could've linked to all cookie lists at the same time, i.e. all of FilterLists' cookie-tagged lists.

So I propose to make it possible to add extra values at the end of the site URL, e.g. `https://filterlists.com/?tag=cookies` or `https://filterlists.com/?lang=pl`.

**Comment by collinbarrett** [comment]
Nice. I like it. I'm going to expand the scope of #263 and close this issue into that one. It's not really a duplicate, per se, but they are closes related that we can tackle them all at once in theory.
