### ISSUE TITLE
add Shalla's Blacklists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#410]
http://www.shallalist.de/index.html

**Comment by Atavic** [comment]
74 categories.

**Comment by Atavic** [comment]
You can see it [here](https://github.com/cbuijs/shallalist).

**Comment by collinbarrett** [comment]
Agreed. I just didn't have the huge amount of time it'll take to add these. But, will keep it open. Hopefully someday we can get #372 implemented to make it easier.
