### ISSUE TITLE
Bypass Paywalls Clean filter: change of url

### ISSUE THREAD

**Issue by bpc-clone** [collinbarrett/FilterLists#4274]
https://filterlists.com/lists/bypass-paywalls-clean-filter has moved to:

https://github.com/bpc-clone/bypass-paywalls-clean-filters/raw/main/bpc-paywall-filter.txt

**Comment by collinbarrett** [comment]
FilterLists currently relies on someone creating a pull request to apply data changes. We'll keep this Issue open until a volunteer (that could be you, another volunteer, or myself) takes the time to create a PR.

https://github.com/collinbarrett/FilterLists?tab=readme-ov-file#adding-or-updating-lists
