### ISSUE TITLE
support multi-select in filters

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#428]
This should be supported in Software, Languages, Tags, License, and Maintainers columns.

**Comment by hawkeye116477** [comment]
Also multiple selection of tags should be possible and maybe some icons for categories/tags. 
Example from my page:
![screenshot_20180907_115304](https://user-images.githubusercontent.com/19818572/45212216-9df84e80-b294-11e8-914e-f91546724a43.png)
I used bootstrap-select to that cool dropdown :smile:

**Comment by collinbarrett** [comment]
@hawkeye116477 what's the url for that site? I'm trying to figure out how to implement the multi-select with the react-table grid we're using on FilterLists. I am not much of a front-end developer. :)

**Comment by hawkeye116477** [comment]
@collinbarrett `https://polishannoyancefilters.netlify.com/otherfiltersforadblockers/`

**Comment by collinbarrett** [comment]
I think this is now supported in the new UI. Let me know if you have further enhancement requests on this feature.
