### ISSUE TITLE
user rating

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#43]
Collect user ratings (upvote/downvote, five-star, etc.) so that higher rated lists should receive a boost in FilScore.

As much as is feasible, we would want to prevent the same user from voting many times for the same list. But, the system should be friction-less and private (no accounts/logins).

**Weight:** Medium

**Comment by elypter** [comment]
i think the most valuable information users could give are false positives. this is what harms usability the most. maybe count how often people click on the issue tracker link and weight with list size and download numbers.

**Comment by collinbarrett** [comment]
closing into master issue #371
