### ISSUE TITLE
My anti-anti-adblock filter lists

### ISSUE THREAD

**Issue by ghost** [collinbarrett/FilterLists#4406]
Hello!

I have created 3 new filter lists:

- https://raw.githubusercontent.com/AdCrunchSoftware/AdblockingFilters/main/antiantiadblock.txt - works with AdBlock/Adblock Plus
- https://raw.githubusercontent.com/AdCrunchSoftware/AdblockingFilters/main/foruBO.txt - for uBlock Origin
- https://raw.githubusercontent.com/AdCrunchSoftware/AdblockingFilters/main/foradguard.txt - for AdGuard

**Comment by SeamlessRelaxation** [comment]
AdGuard deliberately doesn't fix anti-adblock on certain sites. uBO plays cat-and-mouse with some sites, so just disabling elemhide makes sense for a small filter list.

**Comment by Permanently** [comment]
User's been deleted, along with the lists submitted :/

**Comment by collinbarrett** [comment]
Hmm. Ok, thanks, @Permanently.
