### ISSUE TITLE
new list: Phish Fillet

### ISSUE THREAD

**Issue by Permanently** [collinbarrett/FilterLists#4419]
Hello, just submitting this list for the website.

https://codeberg.org/Morishima/PhishFillet/raw/branch/main/Filter.txt - "This is a list of phishing sites (especially posing as Microsoft and using CAPTCHAs)."

[main page here](https://codeberg.org/Morishima/PhishFillet)

**Comment by elliotwutingfeng** [comment]
It is a dead link now.

**Comment by collinbarrett** [comment]
thanks, @elliotwutingfeng 

closing for now unless we get a new working link
