### ISSUE TITLE
review all AdzHosts lists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#445]
Project seems to have ended. I removed the primary list (https://github.com/collinbarrett/FilterLists/commit/9fdf218c7d8e900a532528f24a7b93863ff1a873), but other lists should either be pointing to Wayback Machine backups, a high quality fork of the project, or be removed.

**Comment by Atavic** [comment]
Last activity 7 months ago, [here](https://sourceforge.net/projects/adzhosts/)

**Comment by collinbarrett** [comment]
Yeah, and the lists themselves seem to now be offline. Unless we can find an archive or high-quality fork of them, we'll probably just want to remove them from FilterLists.

**Comment by collinbarrett** [comment]
Possible mirror: http://getwebb.org/d/eYhonMxN
