### ISSUE TITLE
mark deprecated/outdated SSL config as insecure

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#449]
`viewUrl`s like that of list `id`=402 that have an invalid/outdated SSL config should have their view/subscribe buttons marked as red/insecure like those lists accessible only over HTTP.

**Comment by DandelionSprout** [comment]
As long as it becomes blue again once the SSL config has been sorted out, then I'm all for it.

This is particularly important for me and for #467, as the site that hosts the mirror of my lists will only be sorting out its SSH certificate config in about four weeks' time.

**Comment by collinbarrett** [comment]
blocked by #940

**Comment by collinbarrett** [comment]
closing into #21
