### ISSUE TITLE
add any missing lists from hermanjustinm's gist

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#453]
https://gist.github.com/hermanjustinm/0adfa216b87b7f1105971cb2c8db81b9

The list below, specifically, may be new. But, we should double-check the entire gist.

- https://smokingwheels.github.io/Pi-hole/allhosts
- https://github.com/HenningVanRaumle/pihole-ytadblock/blob/master/ytadblock.txt
- https://github.com/HenningVanRaumle/pihole-ytadblock/blob/master/ytadblock.txt
- https://raw.githubusercontent.com/nathanaccidentally/SystemHostsBlocker/master/hosts
- https://raw.githubusercontent.com/TakoYachty/Gift-Card-Killer/master/giftcardkiller.txt

**Comment by DandelionSprout** [comment]
By using some tweaks and tricks in Sublime Text, it claimed that these lists were not duplicates of existing lists on FilterLists.com, or at least not as the main viewUrl.

However, there may be some duplicates here nevertheless, as I didn't have time to check all list links for missing/extra backslashes or the presence/absence of `www.`

http://optimate.dl.sourceforge.net/project/adzhosts/HOSTS.txt".
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
http://securemecca.com/Downloads/hosts.txt
http://www.networksec.org/grabbho/block.txt
https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
https://gist.githubusercontent.com/anudeepND/adac7982307fec6ee23605e281a57f1a/raw/5b8582b906a9497624c3f3187a49ebc23a9cf2fb/Test.txt
https://github.com/HenningVanRaumle/pihole-ytadblock/blob/master/ytadblock.txt
https://isc.sans.edu/feeds/suspiciousdomains_Medium.txt
https://jansal.googlecode.com/svn/trunk/adblock/hosts
https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
https://raw.githubusercontent.com/CHEF-KOCH/Audio-fingerprint-pages/master/AudioFp.txt
https://raw.githubusercontent.com/CHEF-KOCH/BarbBlock-filter-list/master/HOSTS.txt
https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt
https://raw.githubusercontent.com/CHEF-KOCH/Canvas-Font-Fingerprinting-pages/master/Canvas.txt
https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotifynulled.txt
https://raw.githubusercontent.com/CHEF-KOCH/WebRTC-tracking/master/WebRTC.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt
https://raw.githubusercontent.com/martinsauter/Mobile-Block-Hosts-List/master/hosts.blocked
https://raw.githubusercontent.com/nathanaccidentally/SystemHostsBlocker/master/hosts
https://raw.githubusercontent.com/piwik/referrer-spam-blacklist/master/spammers.txt
https://raw.githubusercontent.com/quidsup/notrack/master/malicious-sites.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/tyzbit/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
https://raw.githubusercontent.com/TakoYachty/Gift-Card-Killer/master/giftcardkiller.txt
https://raw.githubusercontent.com/vokins/yhosts/master/hosts
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts
https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt 
https://sites.google.com/site/logroid/files/hosts.txt?attredirects=0
https://smokingwheels.github.io/Pi-hole/allhosts
https://v.firebog.net/hosts/AdguardDNS.txt
https://v.firebog.net/hosts/Airelle-hrsk.txt
https://v.firebog.net/hosts/Airelle-trc.txt
https://v.firebog.net/hosts/Kowabit.txt
https://v.firebog.net/hosts/Prigent-Phishing.txt
https://v.firebog.net/hosts/static/SamsungSmart.txt

**Comment by collinbarrett** [comment]
closing per https://github.com/collinbarrett/FilterLists/pull/564#issue-220883668
