### ISSUE TITLE
add new button for support mirrors

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#461]
## Bug or Feature Request?

![2018-09-09-window](https://user-images.githubusercontent.com/5884000/45260035-1ae21000-b3dc-11e8-8847-0a27024cd3ba.png)

#### example mirrors for github
```
https://rawgit.com/
https://gitcdn.xyz/
https://gitcdn.link/
```

**Comment by collinbarrett** [comment]
great mockup!

combining into #355
