### ISSUE TITLE
Add the capability of filtering lists based date of most recent update

### ISSUE THREAD

**Issue by samuelerickson977** [collinbarrett/FilterLists#4634]
First and foremost thank you for this project. It is great and very useful. 

It would be nice to be able to filter the lists in the ui based on when the list was most recently updated.

This is because I am mostly interested in lists that are actively maintained. I think others as well. I don't want to include a list that hasn't been updated in years.

**Comment by collinbarrett** [comment]
I completely agree. This would be a huge benefit.

I haven't found much time to work on FilterLists in recent years. I'd love to do so, just need to prioritize the time.

For now, I'm closing this request as its also captured in #371 

Thanks for the feedback!
