### ISSUE TITLE
[FEATURE REQUEST] Filter/sort by update date.

### ISSUE THREAD

**Issue by grappas** [collinbarrett/FilterLists#4659]
Some of filter lists are very, very deprecated. Not updated for years. It would be awesome if I could at least sort them lists by date of update (desc) and determine this way if they are maintained.

**Comment by gwarser** [comment]
https://github.com/collinbarrett/FilterLists/issues/4634  
https://github.com/collinbarrett/FilterLists/issues/371

**Comment by collinbarrett** [comment]
Definitely a needed feature. I just haven't personally had time to work on this much in recent years. I'd still love to. Thanks for the feedback.

Closing as duplicate
