### ISSUE TITLE
add NoMoreIPLogger

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#476]
https://github.com/RikoDEV/NoMoreIPLogger-adblock-list

**Comment by hawkeye116477** [comment]
It's discontinued, so maybe not worth.

**Comment by collinbarrett** [comment]
Yeah, in general we still index them for posterity, but just give them a `discontinuedDate` (see https://github.com/collinbarrett/FilterLists/wiki/FilterList). Low value, sure, but maybe not zero value. Eventually, #371 will help surface the most relevant lists, hopefully.

**Comment by Atavic** [comment]
For me it has some new info, like:
```
spötify.com
yoütübe.com
```

The first one redirects to `grabify.link`, an IP logger. 

Never seen big sites URL with phishing characters like:
```ţ
ò
ì
ṃ
ġ
ģ
```

**Comment by collinbarrett** [comment]
closing per https://github.com/collinbarrett/FilterLists/pull/564#issue-220883668
