### ISSUE TITLE
determine difference between two AdguardTeam repos

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#479]
AdguardTeam has the following two repos:

- https://github.com/AdguardTeam/FiltersRegistry
- https://github.com/AdguardTeam/AdguardFilters

I am a bit confused as to what the difference/target is between the two. Should any of our [URLs on FilterLists](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json) be revised?

**Comment by collinbarrett** [comment]
Maybe @ameshkov can assist?

**Comment by ameshkov** [comment]
Hi!

* AdguardFilters -- repo where the AdGuard filters development takes place.
* FiltersRegistry -- a registry with known filters subscriptions (something similar to yours FilterLists) where known filters are periodically downloaded & validated. This is not a home for filter subscriptions, all the work is done in AdguardFilters.

**Comment by collinbarrett** [comment]
Thanks, @ameshkov !

**Comment by collinbarrett** [comment]
Therefore, no change needed.
