### ISSUE TITLE
add iploggerfilter

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#483]
https://github.com/piperun/iploggerfilter

Related to https://github.com/collinbarrett/FilterLists/issues/476 as it lists the same phishing technique:
```
hackfȯrums.com
imgúr.com
battlė.net
```

**Comment by collinbarrett** [comment]
https://github.com/collinbarrett/FilterLists/blob/6c609310aa7da837b2cf5d7aaa04efcb21568c77/data/FilterList.json#L1388

**Comment by Atavic** [comment]
I did a search, I swear.

**Comment by collinbarrett** [comment]
lol, no worries at all. hopefully something like this https://github.com/collinbarrett/FilterLists/issues/311 will help FilterLists contributors in the future.
