### ISSUE TITLE
incorrect Software linked to filterListIds 223 and 615

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#492]
## Bug
On some lists there are wrong softwares, for example `Polish Annoyance Filters - Unlocking Right Click` isn't compatible with AdGuard, it's only compatible with uBO and Nano Adblocker, cuz I mostly only use `script:inject` rules, which AdGuard doesn't support. Also `Official Polish Filters for AdBlock, uBlock Origin & AdGuard` rather aren't compatible with DNS66, just like another lists for adblockers :smile:.

**Comment by collinbarrett** [comment]
Each list is assigned a syntax, and there is a many-to-many relationship between syntaxes and software. So, for example:

`Polish Annoyance Filters - Unlocking Right Click` currently has a [`syntaxId` = 4](https://github.com/collinbarrett/FilterLists/blob/7303a283dc7d174438e5af13e5a4f5f51d0c19d4/data/FilterList.json#L12240) ([`uBlock Origin Static`](https://github.com/collinbarrett/FilterLists/blob/7303a283dc7d174438e5af13e5a4f5f51d0c19d4/data/Syntax.json#L18)). This syntax is currently configured as being supported by a list of software per the [`SoftwareSyntax`](https://github.com/collinbarrett/FilterLists/blob/master/data/SoftwareSyntax.json) model.

So, to correct these bugs, we need to determine if the `syntaxId` for the list is incorrect, if the `softwareSyntax` link is incorrect, etc.

We'll have to correct these issues one-at-a-time. Do you have any suggestions what are wrong with these too lists?

Docs: https://github.com/collinbarrett/FilterLists/wiki

**Comment by hawkeye116477** [comment]
@collinbarrett I see that for DNS66 is assigned Adblock Syntax, so you should change that to hosts syntax. For Polish Annoyance Filters - Unlocking Right Click, probably you should create new syntax, maybe call it **uBlock Origin's scriptlet injection** or something like that and that should apply only to uBO.

**Comment by collinbarrett** [comment]
Ok, sounds reasonable to me. If you have time to submit a PR, that'd be great. If not, I'll get to it when I can.

**Comment by collinbarrett** [comment]
Feedback wanted: https://github.com/collinbarrett/FilterLists/pull/493#pullrequestreview-156144265
