### ISSUE TITLE
change the 'View' button to 'Download' for download-only lists

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#498]
One thing I've noticed during my frequent scouring of FilterLists.com, I've noticed that the `View` links for some lists are actually downloading the lists to one's PC, instead of simply opening them in a browser tab.

Off the top of my head, this applies to Airelle's lists, *DNS-BH Malware Domains*, and *CAMELEON Hosts*.

So to avoid confusing users who may be wary of unexpected downloads, would it possible to change the `View` buttons that lead to file downloads into `Download`? Or whatever else you see would fit?

**Comment by collinbarrett** [comment]
Yeah, I need to research what triggers viewing and what triggers downloading. I think it has to do with the server's response. Maybe it's mime type? I think implementing this feature would require FilterLists `SnapshotService` storing what type of response the server of each `viewUrl` provides, and then adjusting the button text accordingly.

I'm certainly open to doing this. If you have any other insight as to how to determine if a link will download or be viewed in-browser, let me know.

**Comment by DandelionSprout** [comment]
There's sadly few common traits among the download links, compared to the view links. The only things I can currently tell for sure, is that:
* `.txt` and `.php`, as well as all *Githubusercontent* and *GitLab* links, are always view links.
* `.7z` are always download links.
* This unfortunately leaves some ambiguity regarding `/hosts` and suffix-less links.

**Comment by collinbarrett** [comment]
Yeah, I suspect it's not something we can determine by the URL itself. It is probably something in the response headers from the server? If we can figure out what that is, we can have SnapshotService capture that in the db to use for adjusting the UI.

**Comment by collinbarrett** [comment]
I'm not sure it makes sense to support this, as the behavior is controlled by the browser. See [here](http://kb.mozillazine.org/Changing_media_handling_behaviour), for example. It seems to be completely up to the browser to handle whether a resources is previewed or downloaded. I think the best solution we could do as rename the button to something less specific than "View" (that would also apply to downloaded files). Maybe we could just call it "List" ?
