### ISSUE TITLE
AdGuard lists compatibility

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#500]
## Bug/Feature Request
These AdGuard lists which are on FilterLists, they are only for AdGuard extension for Chromium. AdGuard have another lists for AdGuard for Firefox, Edge, Safari and for uBlock. But if I subscribe version from Chromium on Firefox, then AdGuard turn on version for Firefox, so maybe it's not that problem. Hovewer for uBlock there is another version => `https://filters.adtidy.org/extension/ublock/filters/14.txt`, so maybe it should be added, cuz if I click subscribe, then uBO doesn't subscribe/enable (cuz it's on uBO list) version for uBO, but for AdGuard. Also I think that in case, version for AdGuard maybe should be only for AdGuard and there is another list **Official Polish Filters for AdBlock, uBlock Origin & AdGuard - Supplement for AdGuard**, which is rather considered only for AdGuard and is also another **Official Polish Filters for AdBlock, uBlock Origin & AdGuard -  Supplement for uBlock** and Supplement for AdGuard is also marked as uBO-compatible, so users can be confused. 
I know that uBO also supports AdGuard syntax, but not fully, just like AdGuard not fully supports uBO syntax :smile:.

**Comment by collinbarrett** [comment]
Related to #103 , #202 , #496

**Comment by hawkeye116477** [comment]
I have another suggestion. Maybe make another button called Subscribe (uBlock) and View (uBlock). You can also remove **Official Polish Filters for AdBlock, uBlock Origin & AdGuard - Supplement for AdGuard** and add view AdGuard supplement button into **Official Polish Filters for AdBlock, uBlock Origin & AdGuard**, cuz subscribe isn't needed for AdGuard Supplement, cuz it's included by directive on AdGuard on main **Official Polish Filters for AdBlock, uBlock Origin & AdGuard** list.

**Comment by collinbarrett** [comment]
Related to #28

**Comment by collinbarrett** [comment]
I think this issue will be captured between #28 and #496 . Closing for now, but please feel free to provide any additional feedback.
