### ISSUE TITLE
support data model for multi-part lists

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#503]
I am in the process of adding [Little Snitch](https://www.obdev.at/products/littlesnitch) and related lists and syntaxes, and came across https://github.com/naveednajam/Little-Snitch---Rule-Groups during the process.

This appears to be a full conversion of *Unified Hosts + Fakenews + Gambling + Porn + Social* into Little Snitch's format... but because Little Snitch seems to have a limit of 10,000 entries per list (according to [this forum thread](https://forums.obdev.at/viewtopic.php?t=11386)), he has chose to split it up into eight smaller lists.

So that leaves me wondering what to do in a situation like this. I feel it'd be unfair (and slightly cluttering) to list them all individually on FilterLists.com in a *Unified Hosts for Little Snitch, Part 3*-style. And the ability to use multiple view links was not made with scenarios like these in mind.

**Comment by collinbarrett** [comment]
Good question. So, the different sections aren't separated by categories at all, it is purely based on a max number of rules per file?

Hmm... First, have we seen this with any other lists? Or is this a first? I know we have some lists that have categorical modules and then a master list combining them all. But, categorical modules have a basis for being listed as a standalone list on its own merit, and the master list can be marked as a `Merge` of the modules...

Will think on it...

**Comment by DandelionSprout** [comment]
>So, the different sections aren't separated by categories at all, it is purely based on a max number of rules per file?

From what I can determine, that is correct. Each section has a seemingly random combination of e.g. malware domains, gambling domains, porn domains, and other domains.

>First, have we seen this with any other lists? Or is this a first?

This is the first time I have seen it be done in such a way that each section is solely and outright meant to form one "complete" list.

**Comment by collinbarrett** [comment]
similar (but not identical) to #769

**Comment by collinbarrett** [comment]
Closing as this is now supported in the data model. See "segmentNumber" [here](https://github.com/collinbarrett/FilterLists/wiki/FilterListViewUrl).

**Comment by porn-records** [comment]
What is the correct formatting for `segmentNumber` ?? It seems like we have a issue on that in the build, as our combined NSFW for RFC:952 Is a compilation of 4 file with each 3 mirrors.

https://github.com/collinbarrett/FilterLists/pull/2844

**Comment by collinbarrett** [comment]
@porn-records I think you did it right in the PR. The `id` values in `FilterListViewUrl.json` just need to be unique.
