### ISSUE TITLE
eliminate .join(",").split(",") pattern in react-table filterMethod

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#511]
In order to call `.includes()` in a react-table `filterMethod()`, I currently have something like:

`r[f.id].join(",").split(",").includes(f.value)`

The `.join(",").split(",")` is obviously wasteful, but removing it causes the filters not to work properly. This is undoubtedly just due to my lack of ts/js knowledge.

Like here: https://github.com/collinbarrett/FilterLists/blob/73c792486a002fb8da31f6f1b19bced1ff4257d5/src/FilterLists.Web/ClientApp/modules/home/components/listsTable/ListsTable.tsx#L45

**Comment by claustromaniac** [comment]
Wild guess: could it be related to this, somehow?
`https://github.com/Microsoft/TypeScript/issues/2340`

A possible alternative:
```JS
f.value === "any" || r[f.id].indexOf(f.value) > -1, 
```
or shorter:
```JS
f.value === "any" || ~r[f.id].indexOf(f.value), 
```

**Comment by claustromaniac** [comment]
Eh... I was going to edit the comment and deleted it by accident. :man_facepalming: Good thing it was short.

Wild guess: could it be related to this, somehow?
`https://github.com/Microsoft/TypeScript/issues/2340`

A possible alternative:
```JS
f.value === "any" || r[f.id].indexOf(f.value) > -1, 
```
or shorter (not sure this one works as is in TS)
```JS
f.value === "any" || ~r[f.id].indexOf(f.value), 
```

**Comment by collinbarrett** [comment]
Deprecated by new UI.
