### ISSUE TITLE
Re-design "About" page

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#53]
Re-design the "Start" page mimicking the template/features of the WordPress theme. Like [this](http://my.studiopress.com/themes/atmosphere/#demo-full).

**Comment by Piter432** [comment]
That theme is awful :/ The previous one was better (especially that current one is designed for MOBILE not PC).

**Comment by collinbarrett** [comment]
Hi @Piter432 , this issue is strictly related to re-designing the [About](https://filterlists.com/about/) page, not the entire theme of the site. If you think the entire theme is a poor choice/design, please open a new issue and describe in more detail what could be improved. Thanks!

**Comment by collinbarrett** [comment]
Won't fix on current site, but will be sure to implement properly on v3 currently under construction.
