### ISSUE TITLE
enable on-demand fresh data fetch

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#545]
Due to performance issues, FilterLists API endpoints are currently cached both in-memory and using cache headers (at the CDN and in clients browsers) for 1 hour. For developers or power users, it would be great to provide a way to get the latest data on-demand. Not sure what the implementation would look like.

Ideally, resolve #330 and then dropping the cache down even more is a better solution. But, this could provide an interim fix for making fresh data always available.

**Comment by collinbarrett** [comment]
actually, rather than going down this path, @DandelionSprout , just let me know in the PR comments if you plan to keep working right away. If I am able to merge your PR quickly, I can trigger a manual cache purge on my end so the data will be fresh shortly after I merge.

**Comment by collinbarrett** [comment]
P.S. : I just triggered a purge, so data should now be fresh. If it's not, your browser may have cached it, and you'll need to purge your browser's cache.

**Comment by DandelionSprout** [comment]
Ah, thanks for the purge. I'll continue my work right away, in that case.
