### ISSUE TITLE
expose rules count of each list

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#55]
Use the number of filters in the list to calculate the FilScore.

Should likely be a lower weight, as the number of filters does not determine its quality, but it does provide an indicator.

**Comment by elypter** [comment]
i dont think it is an indicator at all. there can be special use filters that are just 1-5 lines that work very well for what they are designed for and some that are kilobytes worth of garbage

**Comment by collinbarrett** [comment]
I agree. It's a number that I'd kind of like to track and display on the site, but not incorporate it really into the quality score of a list.
