### ISSUE TITLE
Change filter URL to the original author - Filtros Nauscopicos

### ISSUE THREAD

**Issue by MS-PC** [collinbarrett/FilterLists#560]
## Adding or Updating Lists?

Could update the URL of the filter:
Current:
https://raw.githubusercontent.com/mozillahispano/nauscopio-filtros/master/filtros.txt

Changed:
http://abp.mozilla-hispano.org/nauscopio/filtros.txt

You could put the current one as a "mirror" and change to the author's official link. It should be noted that this filter is discontinued since the date: 10/26/2013.

**Comment by DandelionSprout** [comment]
I'll attempt to take care of that and the uMatrix stuff in a pull that I'm currently building, meaning that this'll likely be fixed within a few hours.
