### ISSUE TITLE
Add uMatrix in the software list

### ISSUE THREAD

**Issue by MS-PC** [collinbarrett/FilterLists#561]
## Bug or Feature Request?

As a suggestion you could also add uMatrix in the software list, and tag the filter lists Hosts compatible with uMatrix.

**Comment by DandelionSprout** [comment]
There is an existing syntax entry called "uBlock Origin/uMatrix Dynamic" that I've tagged as being compatible with uMatrix, at least.

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/aa3bc90c83bf66369ad1cdacdd3312974c45ce95#diff-28909fe1053845c7845477d2d64d7a4d
