### ISSUE TITLE
add new tag "unsupported"

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#566]
## Bug or Feature Request?

for filters with no updates

**Comment by collinbarrett** [comment]
I recently flipped `discontinuedDate` to `updatedDate`. Maintaining whether or not a list is discontinued/unsupported or not is an ongoing manual process that is expensive.

In addition to still being able to manually set the `updatedDate` in FilterList.json, we have built in a couple of ways to automatically estimate when the list was last updated. (Comparing hashes every few days and pulling the exact commit date for lists hosted on GitHub.) This work is still ongoing/in "beta", but users can sort on the `Updated` column to view only those that have been updated most recently first. When #378 is implemented, you'll be able to accomplish filtering by this proposed tag by the `Updated` column instead.

My inclination is to close as `won't fix` for the above reasons, but will leave open for a bit for feedback. @DandelionSprout , any thoughts on this one?

I totally get the use case for filtering out unsupported lists, but I think using the `Updated` column is a better approach than maintainers having to manually maintain which lists get the tag or not indefinitely.

**Comment by collinbarrett** [comment]
Going to close in favor of sorting by and filtering (pending #378) the Updated column. Maintaining manually whether a list is discontinued/unsupported is too labor intensive at this point in time.

Currently, the Updated column is hidden by default. Should that maybe be visible by default to make this solution more obvious? (The tradeoff is chopping off the end of List names that are long.)
