### ISSUE TITLE
display number of filtered rows

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#567]
## Bug or Feature Request?

![2018-10-07-filterlists _ subscriptions for ublock origin adblock plus adguard](https://user-images.githubusercontent.com/5884000/46581220-235a5480-ca35-11e8-8773-cf8e1183b6ab.png)

**Comment by collinbarrett** [comment]
This is in place to some extent in the current ui. If you filter a column, you can see in the filter dropdown how many lists are currently visible based on that filter. Closing for now.
