### ISSUE TITLE
remove bogachenko's Personal Filters

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#572]
## Adding or Updating Lists?

![2018-10-10-page not found github](https://user-images.githubusercontent.com/5884000/46708737-7a804500-cc40-11e8-808f-185b863218da.png)
`https://github.com/bogachenko`

**Comment by Atavic** [comment]
It's back:
https://github.com/bogachenko/presstheattack

**Comment by Atavic** [comment]
Request: https://github.com/collinbarrett/FilterLists/issues/607

**Comment by collinbarrett** [comment]
Resolved in #607
