### ISSUE TITLE
add support for NSABlocklist

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#574]
## Adding or Updating Lists?

https://github.com/CHEF-KOCH/NSABlocklist/blob/master/test/AdBlock/Adblock.txt

**Comment by CHEF-KOCH** [comment]
https://github.com/collinbarrett/FilterLists/issues/297

**Comment by collinbarrett** [comment]
We've already got this one:

https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/NSABlocklist/CK's-NSABlocklist-FilterList.txt

How does this one differ from that one?

https://github.com/CHEF-KOCH/NSABlocklist/blob/master/test/AdBlock/Adblock.txt

**Comment by CHEF-KOCH** [comment]
It doesn't differ, I decided to create my own blocking list and both repos getting the same entries.

**Comment by Atavic** [comment]
Anything from CK is gone, for a total of 9 lists.
