### ISSUE TITLE
add support for TheUltimateADblocker hosts

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#576]
## Adding or Updating Lists?

https://github.com/AlexRabbit/TheUltimateADblocker/blob/master/hosts/hosts

**Comment by collinbarrett** [comment]
Closing as won't fix. Seems to be a merge list of other primary sources. Merges are fine, but this one seems to have no community (personal use only). Not worth adding. Feel free to comment if you disagree.
