### ISSUE TITLE
replace read-only GitHub personal access token with secret

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#589]
Recently, I committed a read-only personal access token for GitHub in plain text to the repo. Because it only has public read-only permissions, it's not a large security threat.

Ultimately, though, this should be removed (and token revoked and replaced) and instead be retrieved from a proper secrets management such as .NET config file. Because it is used by unit tests, though, it also has to be accessible by the CI server (Travis, currently). So, at this point, I'm not sure how to properly allow the xunit test runner to access the secret in Travis.

**Comment by X1011** [comment]
I believe the standard way is to use encrypted environment variables via .travis.yml, which it looks like you already have set up. Or at least that's what I've used for this purpose.

**Comment by collinbarrett** [comment]
No longer valid since launching the new version of the Agent.
