### ISSUE TITLE
Update .pl-host-file

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#596]
## Adding or Updating Lists?

https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-pihole-filters/hostfile.txt
https://github.com/MajkiIT/polish-ads-filter/tree/master/polish-pihole-filters#readme

**Comment by collinbarrett** [comment]
We have this list indexed [here](https://github.com/collinbarrett/FilterLists/blob/master/data/FilterList.json#L4313). Can you explain what you are suggesting to update?

Closing for now, but feel free to provide more info and I will re-open.
