### ISSUE TITLE
compress FilterLists logo and icon

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#602]
## Bug or Feature Request?

https://github.com/collinbarrett/FilterLists/tree/master/imgs

`https://compressor.io/compress`

<details><summary>imgs</summary>

![icon_filterlists](https://user-images.githubusercontent.com/5884000/47405397-9d871a80-d751-11e8-8f73-e58aff8e7002.png)
![logo_filterlists](https://user-images.githubusercontent.com/5884000/47405398-9d871a80-d751-11e8-858c-f0c844a1fce6.png)
![logo_lg_filterlists](https://user-images.githubusercontent.com/5884000/47405399-9d871a80-d751-11e8-9ae4-6b0537711066.png)

</details>

**Comment by collinbarrett** [comment]
Thanks. The directory you linked to are the originals stored in the repo for reference. The actual images loaded on the website are stored at the directory below and I believe are already compressed pretty well. Let me know if I am misunderstanding your suggestion.

https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Web/wwwroot

**Comment by KonoromiHimaries** [comment]
@collinbarrett still not compressed enough
![2018-10-24-compressor io - optimize and compress jpeg photos and png images](https://user-images.githubusercontent.com/5884000/47431123-781efe80-d79b-11e8-8acd-3e82b415f6d5.png)

**Comment by collinbarrett** [comment]
Yep, you were right. Thanks. I choose to use kraken.io 's lossless compression because I have more familiarity with that tool and I didn't want to sacrifice any quality on hidpi clients by using a lossy algorithm.
