### ISSUE TITLE
consider removing FIN-0 list (if we have it) 

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#604]
per https://github.com/NanoAdblocker/NanoCore/pull/223#issuecomment-432728917

**Comment by gwarser** [comment]
It's "Adblock List for Finland" and returns 404 for me right now.

FIN-0 is uBO internal ID.

**Comment by msrn** [comment]
> 
> 
> It's "Adblock List for Finland" and returns 404 for me right now.
> 
> FIN-0 is uBO internal ID.

The original maintainer removed the list after the backslash. It's obsolete now.
