### ISSUE TITLE
add property for browser support

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#61]
Reminded by [this Issue](https://github.com/uBlockOrigin/uAssets/issues/272#issuecomment-274232629) that some lists only support certain browsers. Should we include a property for that? We will already show which software (uBlock Origin, AdBlock Plus, etc.) each list can be used in (see #7). I think the vast majority of lists are not browser-specific.

Possibly share implementation with #65 .

**Comment by Atavic** [comment]
>I think the vast majority of lists are not browser-specific.

There's that Safari (Mac OS) case and [NanoAdblocker](https://github.com/NanoAdblocker/NanoCore) which has its own [filters](https://github.com/NanoAdblocker/NanoFilters/tree/master/NanoFilters) which are extended beyond uBo format.

Then ome lists are focused on mobile, I think.

**Comment by collinbarrett** [comment]
Yeah, I'm thinking this is so rare that it might piggyback on #65 's implementation rather than giving it its own unique property.

**Comment by collinbarrett** [comment]
Closing as duplicate into #65
