### ISSUE TITLE
How to subscribe to a list in AdGuard?

### ISSUE THREAD

**Issue by computer777** [collinbarrett/FilterLists#614]
I've browsed the software tool list and adguard is supported. How exactly do I access this list ? Can you provide a link in the readme?

**Comment by collinbarrett** [comment]
I don't personally have a lot of experiencing using AdGuard. I'm not sure that the FilterLists "Subscribe" buttons work with it. You may need to consult the AdGuard documentation and use the FilterLists "View" links in AdGuard somehow. Will keep this question open for a bit to see if any AdGuard users can help you out further.

**Comment by collinbarrett** [comment]
Also, please specify which AdGuard tool you are using. I know they have a few. Browser extension? Mobile app? etc.

**Comment by gwarser** [comment]
AdGuard extension have large list of known filter lists that can be just enabled when subscribed. Unknown filter lists are not really subscribed, but added (once) to one large user editable list (sort of "My filters" from uBO).

**Comment by DandelionSprout** [comment]
The desktop version allows custom subscriptions, whereas the browser versions *don't* seem to me to allow it, for some ungodly reason.
