### ISSUE TITLE
re-add CHEF-KOCH's lists

### ISSUE THREAD

**Issue by bogachenko** [collinbarrett/FilterLists#618]
unlocked chef-koch

re-add?
![default](https://user-images.githubusercontent.com/8535285/48520791-d0f92880-e869-11e8-82ba-632324b27aa1.png)

**Comment by collinbarrett** [comment]
Oof.. I dunno. So much drama around this maintainer. I'm open to it, but I don't want to support maintainers who steal other people's work (claims have been made as such for CK, I am not saying they are true or not).

https://github.com/collinbarrett/FilterLists/issues/584

**Comment by bogachenko** [comment]
okay no problems. just asked

**Comment by bogachenko** [comment]
what he is accused of is a serious accusation (but we are all not perfect).
So or otherwise in his (or not his?) lists a lot of good, but the site belongs - "collinbarrett" and this is his decision.

**Comment by Atavic** [comment]
He explained the bans [here](https://github.com/CHEF-KOCH/GitHub-censorship). Now he's back after having removed the bad gist. About re-adding:

I like the *Android* filter list and the various *Corporations* lists, although they aren't very fresh (not a big problem personally).  

> So much drama around this maintainer.

Sure.

> I don't want to support maintainers who steal other people's work.

That started from ghacks-user.js discussions. CK surely got some piece of code from others
and lacked a proper credits reference sometimes, but the angst against him seem far too excessive. Discussion went into a sinkhole, with license references (a useless endeavour, most of the original code was under MIT License) and a lot of bias.

**Comment by collinbarrett** [comment]
Thanks for all the feedback. I'm certainly up for re-adding any lists that are not known to be copies/forks of other lists without credits to the original maintainer (a policy we should try to apply to all lists on FilterLists).

I've been pretty swamped with other work lately, and will likely not have time to contribute to this. But, certainly open to any PRs.

Here's the commit where I stripped them out. We'd want to essentially revert it. https://github.com/collinbarrett/FilterLists/commit/f9d16e5dc03a4ed6a842a7cd92b1ff2bb55d208a
