### ISSUE TITLE
Add the new finnish list

### ISSUE THREAD

**Issue by peace2000** [collinbarrett/FilterLists#620]
Some time ago the finnish list was removed because of the actions of it's author  #604 

However that list has been forked and it's being authored by another person now. (And all the political stuff removed from it of course!)

description
Finnish adblock list

dependentFilterListId
easylist

descriptionSourceUrl
https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/Finland_adb.txt

homeUrl
https://github.com/finnish-easylist-addition/finnish-easylist-addition

issuesUrl
https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues

licenseId
unlicense

name
Adblock List for Finland

publishedDate
2 November 2018

viewUrl
https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/Finland_adb.txt

languageId
fi

**Comment by DandelionSprout** [comment]
Should hopefully be dealt with in #628.

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/939271c182136e7f2e452113bd6503f24ecfb441 per @DandelionSprout
