### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by bogachenko** [collinbarrett/FilterLists#624]
**wait (and hope) that this will fix the admin of this site**

![opera _2018-11-17_131815_notabug org](https://user-images.githubusercontent.com/8535285/48655483-2884c900-ea0f-11e8-974a-8b1feea3d450.png)

mirror 2 Dandelion Sprout's list for Google Hit Hider by Domain - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/List%20for%20Chrome%20Personal%20Blocklist

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianList.txt

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites (Domains) - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltreDomains.txt

mirror 2  Dandelion Sprout's Norwegian Filters for Tidier Websites (Hosts version) https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/AdawayHosts

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites (Internet Explor) = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/DandelionSproutsNorskeFiltre.tpl

mirror 2 Dandelion Sprout's Norwegian Filters for Tidier Websites (Little Snitch) - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/NorwegianExperimentalList%20alternate%20versions/LittleSnitchNorwegianList.lsrules

mirror 2 Dandelion Sprout's Redirector List - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/DandelionSproutRedirectorList.json

mirror 2 Dandelion Sprout's Tidy Sami-languages Internet List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/S%C3%A1megiella-interneahttalisttu.txt

mirror 2 Dandelion Sprout's Very Thorough Website Cleaner = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/VeryThoroughWebsiteCleaner.txt

mirror 2 Dandelion Sprout's Website Stretcher - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Dandelion%20Sprout%27s%20Website%20Stretcher.txt

mirror 2 Evidon Unbreaker https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/EvidonUnbreaker.txt

**Comment by bogachenko** [comment]
morror 2 gmbkslist (ABP) - https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/AncientLibrary/gmbkslist.txt

**Comment by bogachenko** [comment]
this is a normal? Last Day on Earth Scam Sites = https://raw.githubusercontent.com/AegisTeam/Discord-Resources/master/Domain%20Filters/Malicious/scam/Last%20Day%20on%20Earth
![default](https://user-images.githubusercontent.com/8535285/48669295-8988cb80-eaf9-11e8-8a6d-a69867510375.png)

**Comment by collinbarrett** [comment]
lol. probably not a ton of value indexing a list that only has one entry. if it's a list that is new and will have more in the future, maybe.

**Comment by bogachenko** [comment]
> maybe

**Comment by bogachenko** [comment]
Removes "Download Our App" banners from mobile website versions, for those who prefer their phone web browsers instead of apps." = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/stayingonbrowser/Staying%20On%20The%20Phone%20Browser
Norwegian Extensions For UBO & Nano = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/masterNorwegianExtensionsForUBO&Nano.txt
Username Hider for Compilation Creators = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Username%20Hider%20for%20Compilation%20Creators.txt
Browsing websites without logging in = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/BrowseWebsitesWithoutLoggingIn.txt
Anti-FіМ List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Anti-F%D1%96%D0%9C%20List.txt
Anti-IMDB List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Anti-IMDB%20List.txt
Anti-'Christmas carols' list = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Anti-'Christmas%20carols'%20List.txt
Anti-Futa List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Anti-Futa%20List.txt
Tor Redirector List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/TorRedirectorList.json
Pro-LED List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Pro-LED%20List.txt
MeWe Pink Theme = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/MeWe%20Pink%20Theme.txt
YouTube: Yet Even More Pure Video Experience = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/YouTubeYetEvenMorePureVideoExperience.txt
Wikia: Pure Browsing Experience = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/WikiaPureBrowsingExperience.txt
Anti-'Abuse porn' list for Pixiv = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/AntiAbusePorn.txt
Twitch: Pure Viewing Experience = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/TwitchPureViewingExperience.txt
YouTube: Even More Pure Video Experience = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/YouTubeEvenMorePureVideoExperience.txt
Adblocking Open Filter JP = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/AncientLibrary/AncientLibrary/gmbkslist.txt
TamilFriends List = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/AncientLibrary/TamilFriends%20List.txt
Snaevar87's Icelandic filter = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/AncientLibrary/Snaevar87%27s%20Icelandic%20filter.txt
Liste DZ = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/AncientLibrary/Liste%20DZ.txt
Anti-Elsagate List for YouTube = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Anti-Elsagate%20List.txt
Adblock List Template (Novice) = https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Adblock%20list%20templates/Adblock%20list%20template%20-Novice-.txt

https://notabug.org/DandelionSprout/FilterMirrorRepo2/raw/master/Adblock%20list%20templates/Adblock%20list%20template%20-Beginner-.txt

**Comment by bogachenko** [comment]
what is it?

https://repo.or.cz/FilterMirrorRepo.git/blob_plain/refs/heads/master:/Adblock%20list%20templates/Adblock%20list%20template%20-Beginner-.txt
https://repo.or.cz/FilterMirrorRepo.git/blob_plain/refs/heads/master:/Adblock%20list%20templates/Adblock%20list%20template%20-Novice-.txt

**Comment by DandelionSprout** [comment]
I was unaware of this issue, and I can see that it's pretty lame on NotABug's part that they haven't resolved this issue in possibly a week. At least it seems to be a server issue of theirs (https://notabug.org/hp/gogs/issues/193#issuecomment-11108).

But come on, mate. Instead of contacting me (or even just @-ing me) to make me aware of the issue, you (bogachenko) decide to try to remove them unilaterally without even checking up with me if I still intend to maintain that mirror or not. You're better than this.

**Comment by bogachenko** [comment]
@DandelionSprout damn it your links ... honestly speaking I did not notice your nickname
my fool

pss: in justification, I will say that I did not immediately delete (although this does not justify me).
I am sorry again
pss: damn it in a cube

**Comment by DandelionSprout** [comment]
Ah, okay. I accept your apology. 🙂

**Comment by bogachenko** [comment]
And yet, this is not a server problem .. I have these open normally
https://notabug.org/latvian-list/adblock-latvian
this is strange

**Comment by DandelionSprout** [comment]
It appears that the issue is limited to mirrored repos, which the Latvian list's repo isn't.
