### ISSUE TITLE
add little snitch rules

### ISSUE THREAD

**Issue by publicarray** [collinbarrett/FilterLists#626]
* FilterList
  * description - Little Snitch rules for Mac apps.
  * homeUrl - https://github.com/koenrh/little-snitch-rules
  * issuesUrl - https://github.com/koenrh/little-snitch-rules/issues
  * name - Little Snitch Rules
  * viewUrl - https://raw.githubusercontent.com/koenrh/little-snitch-rules/master/apps.lsrules
  * licenseId - 5

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/ef1b46b26378ed5e2c220d8fc065ce3026e7d1dd
