### ISSUE TITLE
add QR Code buttons

### ISSUE THREAD

**Issue by kowith337** [collinbarrett/FilterLists#629]
## Bug or Feature Request?
I just only open this idea (and this maybe low priority)

#### Main Idea about this
- Generate QR Code image from 'View' URLs, include mirror.

#### Pros
- Scan with QR Reader App will copy URL to clipboard and also save history into the app itself (if supported, e.g. [Barcode Scanner](https://f-droid.org/packages/com.google.zxing.client.android) / [SecScanQR](https://f-droid.org/packages/de.t_dankworth.secscanqr))
- Help a little bit for non ABP/UBO users (esp. AdGuard and hosts file blocking apps, e.g. [AdAway](https://f-droid.org/packages/org.adaway) / [Blokada](https://f-droid.org/packages/org.blokada.alarm) / [DNS66](https://f-droid.org/packages/org.jak_linux.dns66) / [NetGuard](https://f-droid.org/packages/eu.faircode.netguard), include Firefox for Android and related forks that have internal QR code reader)

#### Cons
- Maybe take more time than directly copy URL from 'View' button in Filterlists site.

**Comment by collinbarrett** [comment]
Hey, very cool. I love the idea.

I'm not super well-versed in QR codes.

Have we done any research to see if there are any libraries/plugins that we could add to the app that would auto-generate the images from the urls? That seems like it would be ideal over manually creating them.

Or, maybe what you are generating are custom/hand-crafted and wouldn't really be supported by an auto-generation tool?

**Comment by DNSCrypt-Lists** [comment]
Actually Apple created a workflow app that used to be called Workflow, but now it's called Shortcuts. I set up a flow for this; though it is one at a time, I like it. Weird, yes. But I do. However, I'm sure my Arch install could pump em out really fast. To me that's somewhat boring but in this case faster is better. 🙂

***
* ### `FilterLists.com`

![](https://raw.githubusercontent.com/DNSCrypt-Lists/FilterLists.com-QR-Codes/master/sample-codes/38C210CC-433A-467D-9C13-869856ADBF4F.jpeg)

**Comment by collinbarrett** [comment]
Awesome, ok, thanks. As we look at rolling them into filterlists.com, I may look around and see what I can find to automate it. I just don't want you to waste a bunch of time doing them manually if we find a good automated solution.

**Comment by DNSCrypt-Lists** [comment]
Arch Linux has it, I'm sure. I just never looked, though I'll do so after dinner. I'll let you know what I find. I wonder if gimp does QR. Hmm. Set up a macro with it if so.

**Comment by collinbarrett** [comment]
gotchya. yeah, since we are using react/webpack on the front-end, maybe this guy: https://github.com/soldair/node-qrcode

**Comment by DNSCrypt-Lists** [comment]
Looks good. However, on a whim I ran a search for firefox extensions that generate them. There are literally between 15-20 of them. Not all are suitable, but some look interesting. Thinking easier the better.

**Comment by collinbarrett** [comment]
Not a high priority in my opinion, and not a feature I plan to build personally anytime soon. But, if somebody wants it and submits a PR, I'd certainly consider it. Closing for now.
