### ISSUE TITLE
update MrBukLau's lists

### ISSUE THREAD

**Issue by MrBukLau** [collinbarrett/FilterLists#635]
## Updating Lists

**Your site contains six filter lists that I am maintaining, which are listed below:**
Minimalist Cryptocurrency Filter List (**id:** 737)
Music Filter List (**id:** 738)
Resources Filter List (**id:** 739)
Social Filter List (**id:** 740)
Sports Filter List (**id:** 741)
Streaming Filter List (**id:** 742)

**Change the syntaxId from 3 [Adblock Plus (Latest/Unspecified Version)] to 4 [uBlock Origin Static] for these lists:**
Minimalist Cryptocurrency Filter List
Resources Filter List
Sports Filter List

**Adding another tag to Minimalist Cryptocurrency Filter List:** 
**tagId** 9 (annoyances)

**Adding me as the maintainer for these six filter lists:**
**homeUrl:** https://github.com/MrBukLau
**name:** MrBukLau

I am not sure where the section is for the Rule Count part, but all of the filter lists I am maintaining have been updated recently.

Thanks!

**Comment by Atavic** [comment]
All data to submit is indexed [here](https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar)

> the Rule Count part

Maybe you are referring to:

> updatedDate: Date of most recent published revision

If so, it's listed [here](https://github.com/collinbarrett/FilterLists/wiki/FilterList)

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/ef1b46b26378ed5e2c220d8fc065ce3026e7d1dd
