### ISSUE TITLE
Update and relocate CHEF-KOCH's lists

### ISSUE THREAD

**Issue by kowith337** [collinbarrett/FilterLists#637]
## Adding or Updating Lists?
Checklist for CHEF-KOCH's filters for adding, updating and relocating file location.

I'm just note down, will be update, edit and make pull later.

_From now on, marked below is mean updated in the forked repo._

### [ABP/uBO Filterlist](https://github.com/CHEF-KOCH/CKs-FilterList/tree/master/filters)
- [x] [Adobe](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Adobe/CK's-Adobe-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/adobe.txt))
- [x] [Ads & Tracker](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Ad%20&%20Tracker/CK's-Ad%20&%20Tracker-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/ads-tracker.txt))
- [x] [Android List](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Android/CK's-Android-FilterList.txt) ([relocated](https://github.com/CHEF-KOCH/CKs-FilterList/raw/master/filters/android.txt)) \*missed check\*
- [x] [Apple](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Apple/CK's-Apple-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/apple.txt))
- [x] [CCleaner](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/CCleaner/CK's-CCleaner-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/ccleaner.txt))
- [x] [Canvas Pixel](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/canvaspixel.txt) (new)
- [x] [CloudFlare](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Cloudflare/CK's-Cloudflare-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/cloudflare.txt))
- [x] [CloudFront](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/cloudfront.txt) (new)
- [x] [CoinMiner](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/coinminer.txt) (new)
- [x] [Cookie](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/cookies.txt) (new)
- [x] [Div+Ins](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/div%2Bins.txt) (new)
- [x] [ESET](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/eset.txt) (new)
- [x] [Emoji](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/emoji.txt) (new)
- [x] [Facebook](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Facebook/CK's-Facebook-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/facebook.txt))
- [x] [Fonts List](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Fonts/CK's-Fonts-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/fonts.txt))
- [x] [Generic](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/generic.txt) (new)
- [x] [Google](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Google/CK's-Google-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/google.txt))
- [x] [His own filter list](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/CK's-FilterList.txt) (location not changed)
- [x] [iFrame](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/iframe.txt) (new)
- [x] [Instagram](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Instagram/CK's-Instagram-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/instagram.txt))
- [x] [Lucky Patcher](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/luckypatcher.txt) (new)
- [x] [Malware](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Malware/CK's-Malware-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/malware.txt))
- [x] [Microsoft](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Microsoft/CK's-Microsoft-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/microsoft.txt))
- [x] [Modal](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/modal.txt) (new)
- [x] [Mozilla](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Mozilla/CK's-Mozilla-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/mozilla.txt))
- [x] [NSA Blocklist](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/NSABlocklist/CK's-NSABlocklist-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/nsablocklist.txt))
- [x] [News](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/news.txt) (new)
- [x] [Onion (TOR) List](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/I2P%20%26%20Onion/CK's-Onion-FilterList.txt)\* ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Onion/Onion-FilterList.txt))
- [x] [Pinterest](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Pinterest/CK's-Pinterest-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/pinterest.txt))
- [x] [PopAds](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/popads.txt) (new)
- [ ] erm...!? (skipped, sorry!)
- [x] [Reddit](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/reddit.txt) (new)
- [x] [Share Button](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/share-buttons.txt) (new)
- [x] [Skype](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Skype%20Ad-Free/CK's-Skype-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/skype.txt))
- [x] [Spotify](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Corporations/Spotify%20Ad-Free/CK's-Spotify-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Spotify/Spotify-AdBlock.txt))
- [x] [Third Party](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/third-party.txt) (WIP)
- [x] [Torrent Tracker](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Torrent/CK's-Torrent-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/torrent-tracker.txt))
- [x] [Twitch](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/twitch.txt) (new)
- [x] [URL Shortener](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/urlshortener.txt) (new)
- [x] [WebSocket](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/websocket.txt) (new)
- [x] [Yahoo](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/yahoo.txt) (new)
- [x] [Yandex](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/yandex.txt) (new)

> Note that onion list use the `!` to comments, so I cannot call it to use as hosts file because the hosts file comments should begin with `#`.

### [Hosts File](https://github.com/CHEF-KOCH/CKs-FilterList/tree/master/HOSTS)
- [x] [AdGuard](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Adguard-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/AdGuard.txt))
- [x] [Adobe](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Adobe-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Adobe.txt))
- [x] [Ads & Tracker](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Ad-Tracker-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Ads-tracker.txt))
- [x] [Apple](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Apple-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Apple.txt))
- [x] [CCleaner](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-CCleaner-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CCleaner.txt))
- [x] [CloudFlare](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Cloudflare-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Cloudflare.txt))
- [x] [CoinMiner](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/coinminer.txt) (new)
- [x] [ESET](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Eset.txt) (new)
- [x] [Facebook](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Facebook-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Facebook.txt))
- [x] [Game](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Game-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Game.txt))
- [x] [Google](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Google-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Google.txt))
- [x] [Instagram](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Instagram-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Instagram.txt))
- [x] [Internet Download Manager](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Internet%20Download%20Manager.txt) (new)
- [x] [Lucky Patcher](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/LuckyPatcher.txt) (new)
- [x] [Malware](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Malware.txt) (new)
- [x] [Microsoft](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Microsoft-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Microsoft.txt))
- [x] [Mozilla](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Mozilla-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Mozilla.txt))
- [x] [NSA Blocklist](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/NSABlocklist.txt) (new)
- [x] [Pinterest](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Pinterest.txt) (new)
- [x] [PopAds](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Popads.txt) (new)
- [x] [Skype](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Skype-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Skype.txt))
- [x] [Spotify](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Spotify-HOSTS-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Spotify/Spotify-HOSTS.txt))
- [x] [TechSmith](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Techsmith.txt) (new)

### [Whitelist](https://github.com/CHEF-KOCH/CKs-FilterList/tree/master/Not%20blocked)
- [x] [CK's Won't block](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Not%20blocked/CK's-Wontblock-FilterList.txt) ([relocated](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/Not%20blocked/Wontblock.txt), rename to "CHEF-KOCH's Unblock")

> ### Template Only
> ```
> - [x] [name]() ([status]())
> - [ ] [name]() (new)
> - [ ] [name](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/.txt) (new)
> - [ ] [name](https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/.txt) (new)
> ```

**Comment by kowith337** [comment]
Need #636 to be fixed before make new pull?

**Comment by collinbarrett** [comment]
My bad... See https://github.com/collinbarrett/FilterLists/issues/636#issuecomment-445492557 . Feel free to submit PRs against master now.

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/ef1b46b26378ed5e2c220d8fc065ce3026e7d1dd
