### ISSUE TITLE
Add/review ---> Farrokhi's Adblock-Iran

### ISSUE THREAD

**Issue by Atavic** [collinbarrett/FilterLists#641]
## Feature Request: Add *adblock-iran*

https://github.com/farrokhi/adblock-iran

Ad blocking rules for iranian/persian websites.
https://github.com/farrokhi/adblock-iran/blob/master/README.md

donateUrl N/A

emailAddress can be found on: https://github.com/farrokhi

homeUrl: https://github.com/farrokhi/adblock-iran

issuesUrl: https://github.com/farrokhi/adblock-iran/issues

name: Adblock Iran 

policyUrl: N/A

publishedDate: 2017-08-16T00:00:00

submissionUrl: N/A

syntaxId: 3,4

updatedDate: 2018-12-9T00:00:00

viewUrl
https://raw.githubusercontent.com/farrokhi/adblock-iran/master/filter.txt

viewUrlMirror1
https://gitcdn.xyz/repo/farrokhi/adblock-iran/master/filter.txt

viewUrlMirror2 N/A

languageId iranian

License descriptionUrl: https://github.com/farrokhi/adblock-iran/blob/master/LICENSE		
License name: BSD Simplified

Its permissions allow Commercial use and Modification. 

Maintainer: Babak Farrokhi
http://farrokhi.net/

Merge N/A

*isAbpSubscribable?* Don't know, it says [how to install](https://github.com/farrokhi/adblock-iran#installation) on homepage.

*Tag name:* ads

**Comment by DandelionSprout** [comment]
Forgive me if I'm wrong, but isn't this list already on FilterLists.com, under the name of *Adblock Iran*?

**Comment by Atavic** [comment]
That's the one, I searched here on the repo but got no results.
