### ISSUE TITLE
I cannot load API page

### ISSUE THREAD

**Issue by gwarser** [collinbarrett/FilterLists#645]
## Bug or Feature Request?

https://filterlists.com/api/docs/index.html does not load for me.

https://filterlists.com/api/docs/swagger-ui-bundle.js is not fully loaded.

Even using wget i only get: "Read error at byte 271960" in loop.

Chromium Version 71.0.3578.98 (Official Build) Manjaro Linux (64-bit)
Firefox Nightly

**Comment by collinbarrett** [comment]
Seems to be resolved for now by [this](https://github.com/collinbarrett/FilterLists/issues/651#issuecomment-452937966). My guess is it's related to updating to dotnet core 2.2 (which I just reverted. Will make sure to test this in #636 when it is resolved.

**Comment by wesinator** [comment]
https://filterlists.com/api/docs/ is still blank page

**Comment by collinbarrett** [comment]
yeah, Swagger (docs-generator) isn't really working. related to #554 . it's on the to-do list, but no ETA on when I'll have a chance to look at it.
