### ISSUE TITLE
white and black frame on the black thema

### ISSUE THREAD

**Issue by KonoromiHimaries** [collinbarrett/FilterLists#646]
## Bug or Feature Request?

![2018-12-24-window](https://user-images.githubusercontent.com/5884000/50396461-9341c680-076a-11e9-9ae4-5b2034b48729.png)

**Comment by collinbarrett** [comment]
Not officially supported yet. Closing as duplicate of #466 . If/when it is officially supported, we'll be sure to clean those up.
