### ISSUE TITLE
Add SteamScamSite

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [collinbarrett/FilterLists#647]
- Dependent = https://raw.githubusercontent.com/PoorPocketsMcNewHold/steamscamsite/master/steamscamsite.txt
- FilterList = SteamScamSite
- FilterListLanguage = EN
- FilterListMaintainer = PoorPocketMcNewHold 
- FilterListTag = Malware Scam
- Fork = https://github.com/wishihab/steamscamsite
- Language = French, English
- License = CC-BY
- Maintainer = wishihab
- Merge 
- Software 
- SoftwareSyntax
- Syntax
- Tag
I've tried to complete the most of the asked requirements. Still a begineer in this type of things.

**Comment by collinbarrett** [comment]
closed by #648
