### ISSUE TITLE
accept Liberapay donations

### ISSUE THREAD

**Issue by elypter** [collinbarrett/FilterLists#649]

**Comment by collinbarrett** [comment]
Hey @elypter , are you suggesting we add this to donate to list maintainers? Or to the FilterLists project itself? If to the maintainers, I think we can probably add links in the `donateUrl` field to Liberapay.

**Comment by collinbarrett** [comment]
Closing for now. Feel free to open my question above and we can re-open.

**Comment by elypter** [comment]
sorry that i forgot to reply. i actually meant donations for this project. i didnt't know that you support donation links for maintainers which is nice.

**Comment by collinbarrett** [comment]
Ah, ok. I have a beerpay option in the README. I have received a couple "wished" features, but no donations. I'm not really expecting much (and that's fine). It's a labor of love and learning project for me. Is Liberapay one of the most popular tools for collecting donations? If so, I may add it.

Thanks for the suggestion.
