### ISSUE TITLE
ID1286 Request to change the compatible softwares.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [collinbarrett/FilterLists#657]
Since it's an addition to the Filter list, This list has switched to a domain only format, Making it compatible with Pi-Hole (From my own use of it on my Raspberry DNS server).
As suppose it's also compatible with Samsung Knox and Personal blocklist according to other samely formatted lists, but I didn't test on those to be honest.

**Comment by DandelionSprout** [comment]
Sounds perfectly reasonable.

Normally, this can be done very easily by simply changing its `"syntaxId"` value from 8 to 2 in a pull request.

**Comment by PoorPocketsMcNewHold** [comment]
I've actually been searching trought those fikes to send a pull request myself, but that's was one of the only few elements i didn't really understood how it worked.

**Comment by DandelionSprout** [comment]
That's understandable, given the sheer scope of the involved JSON files.

`syntaxID` values are based on https://github.com/collinbarrett/FilterLists/blob/master/data/Syntax.json, where each number corresponds to a specific list format.

**Comment by collinbarrett** [comment]
I've tried to document the data model in the wiki sidebar [here](https://github.com/collinbarrett/FilterLists/wiki) as well, but I certainly know that there is much room for improvement on the data maintenance processes... Thanks!

**Comment by collinbarrett** [comment]
closed by #659
