### ISSUE TITLE
Web Annoyances Ultralist - Additional Sub Filter List (module) Added: CSS Style Modifying Filters

### ISSUE THREAD

**Issue by yourduskquibbles** [collinbarrett/FilterLists#662]
@collinbarrett I just added a new sublist to [Web Annoyances Ultralist](https://github.com/yourduskquibbles/webannoyances) to break out the CSS modifying filters from the main [ultralist.txt](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt). 

The new sublist is located at https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt - Are you able to add as a sublist under Web Annoyances? This should be valid with uBlock Origin & Nano Blocker, and I believe Adguard converts the uBO syntax I use, but have not tested full compatibility with Adguard. Happy to do so if you'd like me to though.

I think the JSON data you would need is below, hopefully you can just copy & paste with minimal cleanup needed.

`"id":` `1294`,
`"dependentFilterListId":` `102`,
`"chatUrl":` `"https://discord.me/yourduskquibbles"`,
`"description":` `"Block annoying web elements and reclaim lost screen real estate - Unsuck the web and make it more user friendly!"`,
`"homeUrl":` `"https://github.com/yourduskquibbles/webannoyances"`,
`"issuesUrl":` `"https://github.com/yourduskquibbles/webannoyances/issues"`,
`"licenseId":` `8`,
`"name":` `"Web Annoyances Ultralist - CSS Style Modifying Filters"`,
`"publishedDate":` `"2019-01-13T00:00:00"`,
`"syntaxId":` `4`,
`"updatedDate":` `"2019-01-13T00:00:00"`,
`"viewUrl":` `"https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt"`

Relates to #475  & #94

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/aea827e2767e199311d014cb5d510d27612087c0
