### ISSUE TITLE
Add "Even cleaner news sites" list

### ISSUE THREAD

**Issue by theel0ja** [collinbarrett/FilterLists#663]
URL: `https://crapblock.theel0ja.info/even-cleaner-news-sites.txt`

repo https://github.com/theel0ja/crapblock

**Comment by bogachenko** [comment]
@collinbarrett close

**Comment by collinbarrett** [comment]
Closed by https://github.com/collinbarrett/FilterLists/commit/57f56d7b601d721f371487848b5bfad836cd3f29
