### ISSUE TITLE
remove CHEF-KOCH modal list - stolen with no attribution

### ISSUE THREAD

**Issue by yourduskquibbles** [collinbarrett/FilterLists#666]
@collinbarrett Requesting that you remove @CHEF-KOCH's [modal list](https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/filters/modal.txt) from your index as it is a 100% copied list with no attribution provided per the terms of the Creative Commons Attribution Share Alike 4.0 International license I use.

I tried opening an issue asking for attribution on his issue tracker but he immediately deleted the issue where I asked for him to attribute the work. 

Evidence of stolen material is below: 
@CHEF-KOCH's modal filter list on day of list creation at [commit 5ecf7ee on Dec 2, 2018](https://github.com/CHEF-KOCH/CKs-FilterList/blob/5ecf7ee992e1df92d03fc99c24dec762c7687d1f/filters/modal.txt) is 100% copied line-for-line from my modal filter list provided at [commit 8d57b6b on Nov 30, 2018](https://github.com/yourduskquibbles/webannoyances/blob/8d57b6bb4c0ae6aa635a527f9cff540c6689208d/filters/modal_filters.txt)

**Comment by claustromaniac** [comment]
issue #666... :fearful:

**Comment by DandelionSprout** [comment]
Although I did vote in favour of restoring his lists to FilterLists two-months-ish ago, it was with the condition that I'd take evidence of individual stolen lists seriously.

So indeed I can make a quick pull to remove Modal List and (if I'm interpreting https://github.com/ghacksuserjs/ghacks-user.js/issues/323#issuecomment-364908927 correctly) BarbBlock List.

**Comment by yourduskquibbles** [comment]
Thank you @collinbarrett and @DandelionSprout

**Comment by DandelionSprout** [comment]
So, let's see if I understand this two-word comment of yours right:

Because FilterLists.com's userbase decided to remove two of your lists, you've reported this repo to GitHub to try to get them to take action against us for some very unclear reasons, despite how you're still listed with 68 other lists on that site, and despite how I'm not aware of any legislation in any country or web service in the world that requires this website to list all of your lists.

**Comment by collinbarrett** [comment]
Regarding [this](https://github.com/collinbarrett/FilterLists/issues/666#issuecomment-457631431) and [this](https://github.com/collinbarrett/FilterLists/issues/670#issuecomment-457691987):

FilterLists is a labor of love (not monetized, paid for out of my pocket and the time of myself and others). Open source is about sharing freely. However, we do not want duplicate lists on FilterLists as it is un-useful for users and discouraging to the original maintainers who work so hard to maintain them.

We appreciate your original lists, CK. But, we choose not to point users of FilterLists to your lists that are exact copies of others with no attribution or unique value. It's not defamatory when the proof of timestamped commits seems pretty clear. It's just a decision to steer the direction of the project.

**Comment by yourduskquibbles** [comment]
@CHEF-KOCH isn't even worth engaging in. He is delusional and a liar/scammer and if it was my project would be blacklisted from the entire project.
