### ISSUE TITLE
remove CHEF-KOCH social list - stolen with no attribution

### ISSUE THREAD

**Issue by yourduskquibbles** [collinbarrett/FilterLists#670]
@collinbarrett @DandelionSprout Requesting that you remove @CHEF-KOCH's [social list](https://github.com/CHEF-KOCH/CKs-FilterList/blob/master/filters/social.txt) from your index as it is a 100% copied list with no attribution provided per the terms of the Creative Commons Attribution Share Alike 4.0 International license I use.

Evidence of stolen material is below:
@CHEF-KOCH's social filter list on day of list creation at commit [5ecf7ee on Dec 2, 2018](https://github.com/CHEF-KOCH/CKs-FilterList/blob/5ecf7ee992e1df92d03fc99c24dec762c7687d1f/filters/social.txt) is 100% copied line-for-line (1670 lines) from my social filter list provided at commit [8d57b6b on Nov 30, 2018](https://github.com/yourduskquibbles/webannoyances/blob/8d57b6bb4c0ae6aa635a527f9cff540c6689208d/filters/social_filters.txt)

**Comment by bogachenko** [comment]
Is he there? I can not find it on filterlists.com

**Comment by DandelionSprout** [comment]
I can't find it either, not even when searching for broad terms like `/filters/social.txt`. So I can presume that this makes this one fewer problem to be concerned about.

**Comment by yourduskquibbles** [comment]
@collinbarrett @DandelionSprout Apologies for false report! I just assumed this one was also on [filterlists.com](https://filterlists.com/) after seeing the stolen without attribution [generic](https://github.com/collinbarrett/FilterLists/issues/669) and [modal](https://github.com/collinbarrett/FilterLists/issues/666) lists and didn't perform my due diligence to confirm this one was also posted to [filterlists.com](https://filterlists.com/)

**Comment by collinbarrett** [comment]
it's all good. no worries. thanks for contributing!

**Comment by CHEF-KOCH** [comment]
Nothing is stolen, if you continue to distort the reality then you will get a permanent ban from GitHub, everything is alive and running.

https://help.github.com/articles/github-terms-of-service/#c-acceptable-use

> is libelous, defamatory, or fraudulent;
> is discriminatory or abusive toward any individual or group;

Conduct Restrictions

> harass, abuse, threaten, or incite violence towards any individual or group, including GitHub employees, officers, and agents, or other GitHub Users;
