### ISSUE TITLE
Remove changelog and guide links

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#68]
Changelog and guide links are not really that useful. Remove for simplicity.

**Comment by Piter432** [comment]
I liked changelog a lot...

**Comment by collinbarrett** [comment]
Hi @Piter432 , this issue was not related to the [Changelog](https://v1.filterlists.com/changelog/) page on the old version of the site. If your comment was in reference to the old Changelog page, please open a new issue expressing your interest in bringing that back to the new site.

This issue was referring to initially including links to the "changelog" for each individual list. These links were not particularly useful and added extra clutter and bloat to the page. If you disagree, and find that the links were useful, please let me know.
