### ISSUE TITLE
Is this too much to add 3 more software (and their icons) ?

### ISSUE THREAD

**Issue by kowith337** [collinbarrett/FilterLists#693]
## Bug or Feature Request

I use 2 of 3 programs that listed below for blocking ads and tracking hosts via hosts file

#### hostsmgr
- Platform: Windows (since XP SP3 and above)
- Syntax support: Hosts File (localhost), Domain Name
- License: GPL v3
- Language: C/C++
- WebSite: https://www.henrypp.org/product/hostsmgr
- Source Code: https://github.com/henrypp/hostsmgr
  > Icon image inside the executable
  > ![image](https://user-images.githubusercontent.com/16535467/52806713-491af880-30bc-11e9-986b-38b65c40ab1d.png)

#### personalDNSFilter
- Platform: Windows (JRE) / Android (4.0 and above)
- Syntax support: Hosts File (localhost), Domain Name
- License: GPL v2
- Language: Java
- Website: https://zenz-solutions.de/personaldnsfilter
- Source Code: https://github.com/IngoZenz/personaldnsfilter 
  > You can see icon image from website

#### Blokada
- Platform: Android (5.0 and above)
- Syntax support: Hosts File (localhost)
  > Not sure it's also support domain name or not
- License: GPL v3
- Language: Kotlin / Java
- Website: https://blokada.org
- Source Code: https://github.com/blokadaorg/blokada 
  > You can see icon image from website

**Comment by DandelionSprout** [comment]
Off the top of my head, Blokada is *not* something that could be added as of at the time of writing, because it only supports DNS filtering to the best of my knowledge.

I suppose I could add a to-do to the issue tracker about supporting DNS addresses as filter-"lists", and adding some of the most prominent ones to FilterLists (e.g. AdGuard DNS).

I'll look into the other two suggestions soon enough.

**Comment by collinbarrett** [comment]
I'd be find with expanding FilterLists to support DNS lists.

**Comment by DandelionSprout** [comment]
The main barrier to doing so, and which I think will have to be resolved, is that many DNS servers may not even have any immediately obvious links that could be used for `viewUrl`, as DNS subscription addresses practically never have webbrowser-readable text on their root(?)/front pages.

I was meaning to spin this off into a separate issue, but I've been busy in another repo in the past hour.

**Comment by DandelionSprout** [comment]
Adding *hostsmgr* to the software list should be easy peasy, by writing a new paragraph for it in [software.json](https://github.com/collinbarrett/FilterLists/blob/master/data/Software.json), followed up by adding:

```
{
    "softwareId": 26,
    "syntaxId": 1
},
```

...to [SoftwareSyntax.json](https://github.com/collinbarrett/FilterLists/blob/master/data/SoftwareSyntax.json), but adding its software icon may take slightly more work.

The official documentation of *personalDNSFilter* is lackluster, so I need your (Presumably kowith337) confirmation about which lists it supports. Is it a hosts-file-only tool, or is at a DNS address accumulator like Blokada, or is it neither of those things?

**Comment by DandelionSprout** [comment]
And apparently it's only now that I saw in the OP that you've answered that question already. 😅

However, I've had a long and fairly active day today, so I may or may not have enough energy to take care of this tonight.

**Comment by DandelionSprout** [comment]
Installing Blokada again to double-check its functionality, as I thought that it was a DNS accumulator only, I see now that it supports hosts files as well.

While there's nothing stopping any of us from adding these 3 tools, I think it's time to think about whether we need to add *three* mostly-Android, combined hosts-and-DNS filtering tools, on top of DNS66 which also works like that. While Blokada seems to me to have strong merits for inclusion, are personalDNSFilter and hostsmgr reasonably well updated, feature-strong, and/or popular?

**Comment by kowith337** [comment]
https://github.com/collinbarrett/FilterLists/issues/693#issuecomment-464139320
For my usage.
- **hostsmgr** also support _domain name_ lists because it will re-parse rules to hosts file rules during generate (auto add `0.0.0.0` or `127.0.0.1`)
- about **personalDNSFilter**, I've tested  with [LeeCh-List](https://raw.githubusercontent.com/pureexe/LeeCh-List/master/anime.txt) and seems the domain name list also compatible as well (domains get blocked and report `ERR_CONNECTION_REFUSED`)
  and you can also config additional hosts without adding hosts file prefix, just domain names, however.
  added domain name in the additional hosts section will also block rest of FQDN that matched, for example, if I put `google.co.th` to blocklist, the `www.google.co.th` also get blocked.

**Comment by DandelionSprout** [comment]
Duly noted. I'll see if I have time to make a basic pull to add these three softwares sometime within the next 2 days (I have and have had a fair few other things on my to-do list this week, you see), presuming that no one else were to want to do so.
