### ISSUE TITLE
How often does the indexed list description data get refreshed?

### ISSUE THREAD

**Issue by yourduskquibbles** [collinbarrett/FilterLists#694]
Hello,

I've [updated the purpose section](https://github.com/yourduskquibbles/webannoyances/commit/8539ec14155412fb56af025bc0918125cd91d239) for each of my lists  to be more descriptive of what the specific list purpose is that are indexed on filterlists.com and am wondering how often that data gets automatically re-indexed into the site, if at all? 

Is it an automatic process or something I have to initiate? 

I did a quick search of the issue tracker and didn't see anyone else asking a similar question so hopefully this is OK to open an issue for.

If the process is manual, I am happy to create my own PR if that is what you would prefer.

## Adding or Updating Lists?

Updated the Purpose Section for the following lists:

1. [Web Annoyances Ultralist](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt)
2. [Web Annoyances Ultralist - CSS Style Modifying Filters](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt) 
 3. [Web Annoyances Ultralist - Generic Filters](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/generic_filters.txt)
 4. [Web Annoyances Ultralist - Modal Overlay Filters](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/modal_filters.txt) 
 5. [Web Annoyances Ultralist - Newsletter Subscription Filters](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/newsletter_filters.txt) 
 6. [Web Annoyances Ultralist - Social Filters](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/social_filters.txt)

**Comment by DandelionSprout** [comment]
Having made more than 60 pulls to FilterLists.com, my personal understanding is that it has varied wildly during the past 9 months, ranging from 3 to 24 hours. Additionally, a refresh has on some occasions been done manually, such as during days with very high commit activity.

**Comment by DandelionSprout** [comment]
However, the description fields are *not* automatically refreshed, if that was specifically what you were wondering about. They're treated as a manual text field in the .JSON file.

That gives me an idea, by the way. Give me 5-10min.

**Comment by collinbarrett** [comment]
Yep, it's not automatic yet. See #202 . Thanks.
