### ISSUE TITLE
add homeUrlMirror or similar

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#697]
This one will likely be a *very* narrowly applying issue report, but it's worth a shot. Most likely contingent on #696 being resolved first.

CloudFlare's 1.1.1.1 DNS service, seems like a very probable candidate to be added to FilterLists.com once DNS addresses become eligible to be added as "lists" to the site. However, that service is notable in that it's the only FilterLists-desirable site to currently also have an .onion domain: https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion. As I used [Tor Browser](https://www.torproject.org/projects/torbrowser.html) for a few months last autumn to do tests for [Tor Redirector List](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout-s%20Redirector%20Assistant%20List/TorRedirectorList.json), I can confirm that their .onion domain does work.

As it currently stands, only one URL may be added as `homeUrl` in `filterlist.json`. This means that only https://1.1.1.1/ (which is their homepage as well as their DNS server, a rare double-duty among DNS servers) could've been used as `homeUrl`, and not also https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion.

The application of `homeUrlMirror` (or `homeUrlAlternateDomain` or something like that) doesn't have to be limited to .onion addresses. If another filterlist server turns out to e.g. mirror its non-raw content across two domains, then `homeUrlMirror` could very well be used for that too.

**Comment by collinbarrett** [comment]
Hmm, in general, I would say we should decide on a single declarative home url if there seems to be more than one. But, a `.onion` version definitely seems deserving of it's own spot. I agree.

**Comment by existential-fallacy** [comment]
Yes! FilterLists.com’s very own .onion address - ❤️❤️❤️

**Comment by DandelionSprout** [comment]
@existential-fallacy Now that you mention it, I have been able to not only apply DomainVoider's .onion address as a regular viewUrlMirror, but also to make its subscription button green (since green seems to be one of Tor's signature buttons).

On the other hand, the .onion address for iVOID doesn't seem to work, my best guess for why being that its 0xacab project seems to currently be a private project. FIY.

**Comment by existential-fallacy** [comment]
The iVOID repo is currently non-existent. Also they's got SSL going now so https: links function

**Comment by collinbarrett** [comment]
If we added a new field like `homeUrlOnion` or similar, would we then want an onion version of all of the other URL types? Trying to think about the best way to apply this without adding a bunch of extra rarely used fields...

**Comment by DandelionSprout** [comment]
If that's a major concern of yours, it is of course also possible to just use `homeUrl2` instead.

**Comment by collinbarrett** [comment]
We now have a db field for `onionUrl` for FilterLists. See [here](https://github.com/collinbarrett/FilterLists/wiki/FilterList).
