### ISSUE TITLE
Updated Information for Filters

### ISSUE THREAD

**Issue by DNSCrypt-Lists** [collinbarrett/FilterLists#704]
## Adding or Updating Lists?
- [x] Updating.

1. iVOID.hosts
````
# Title: iVOID.hosts
# Expires: 14 days
# Last Modified: 2019-03-05T19:39:00+00:00
# Checksum (SHA384): c19723aa41aa0e69f67f3693b0cb95e5277997c7f55b74589628b4f19379abe795316069e6cdabf2103dccd4a6d91fbf
# License: GNU GPLv2
# Maintainer: intr0
# Homepage: https://intr0.com
# Source: https://gitlab.com/intr0/iVOID.GitLab.io/raw/master/iVOID.hosts
````
2. DomainVoider
````
[AdBlock 2.0]
! Title: DomainVoider
! Expires: 14 days
! Last Modified: 2019-03-01T14:20:54+00:00
! Checksum (SHA384): a2e2a416110bc81a58ad4ab52b0629131840e3ece884c12c237346eb61703aae878c970c38d1389f6160ff8fa50f61a0
! License: GNU GPLv2
! Maintainer: intr0
! Homepage: https://intr0.com
! Source: https://gitlab.com/intr0/DomainVoider/raw/master/DomainVoider.txt
! Description: DomainVoider is dedicated to providing AdGuard Pro for iOS users with custom built, privacy and security focused filters using a simplified adblocking format.
````
—-
Thank-you very much.
- intr0

**Comment by DNSCrypt-Lists** [comment]
Thanks for this; it’s helpful. I was unable to locate each within the latter scope of FilterLists.json & therefore unable to use the proper json format with each field properly defined. I’ve now stored this info for future use as I’ve still a few changes/additions for each. I’ll be submitting these for a future release. Again, thank-you.
- intr0

**Comment by collinbarrett** [comment]
Cool, yeah, also check out the [wiki](https://github.com/collinbarrett/FilterLists/wiki) if you haven't yet for further documentation on what all the fields represent.
