### ISSUE TITLE
DMCA Takedown Of CHEF-KOCH Lists

### ISSUE THREAD

**Issue by DNSCrypt-Lists** [collinbarrett/FilterLists#710]
## Bug or Feature Request?

- [x] Bug of sorts / legal issue
***
[DMCA Takedown Notice](
https://github.com/github/dmca/blob/master/2019/03/2019-03-05-WindowsSpyBlocker.md)

## Adding or Updating Lists?
- [x] Neither / Notification
***
As of 6 hours of this issue, the entirety of CHEG-KOCH’s filter repository is pointed here:
[DMCA Notice Page](
https://github.com/CHEF-KOCH/CKs-FilterList)
***
Being unsure of your own responsibility in listing License-Violating lists that have reached GitHub’s DMCA listings, I thought it best to advise you of this situation.

**Comment by bogachenko** [comment]
lol

**Comment by dimqua** [comment]
LOL

**Comment by collinbarrett** [comment]
I hate pulling all of his lists down again. We've played that game before, and they came back up. Considering adding a boolean enabled/disabled flag that hides lists from the site without removing them from the database (in case they come back on).

**Comment by DNSCrypt-Lists** [comment]
The Boolean idea is awesome. 1 or 0, e.g. as representative of true or false / enabled or disabled. I’m unsure of the impact on your workload of incorporating said logic, but if it’s a tag you can add in FilterLists.com JSON then perhaps it’s worthy of incorporation into every list’s JSON. Obviously, it’s a switch that only you and your team may access if necessary.

**Comment by DandelionSprout** [comment]
Considering the popularity of the Windows Spy Blocker repository (★987 and ʘ167), I would be pretty surprised if `CHEF-KOCH` comes out on top in this situation.

Given how sensitive `CHEF-KOCH` can be, I am weighing my words carefully-esque here, as I am not one to tempt fate. But I personally doubt he'd get his lists back online now, and I'd recommend taking action in some or another way based on that assumption.

**Comment by DNSCrypt-Lists** [comment]
True. Also as I notified @Crazy-Max earlier **[here](
https://github.com/crazy-max/WindowsSpyBlocker/issues/142)**, `CHEF-KOCH` has a mirror on GitLab & here on GitHub. The humorous part of this is his [README file on GitLab](
https://gitlab.com/fsdlxq/CHEF-KOCH/blob/master/Readme.md) - it's a must read.

**Comment by collinbarrett** [comment]
Closed by #711

**Comment by crazy-max** [comment]
Thanks for your involvement guys :handshake:

**Comment by DNSCrypt-Lists** [comment]
@crazy-max , I’ve submitted information to GitHub regarding the so-called mirror here on GitHub which now includes slander against you. Since I myself do not contribute to the work you do, perhaps considering submitting your own, first-person, version of exactly what you read at 
https://github.com/CHEF-KOCH/CKs-FilterList-Mirror.

- @DNSCrypt-Lists

**Comment by crazy-max** [comment]
Has been taken down : https://github.com/CHEF-KOCH/CKs-FilterList-Mirror
