### ISSUE TITLE
soft delete

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#713]
Related to #710 (to hide lists from the website), but is now (in my eyes) to be approached as a general idea and not as a person-dependent one.

Additionally, #496 proposes boolean values for software syntax support.

**Comment by collinbarrett** [comment]
re-opening. after the major API refactor a couple of weeks ago, I forgot to re-add this.

tagging https://github.com/collinbarrett/FilterLists/pull/2003 . lists will still be visible until I fix this.

**Comment by collinbarrett** [comment]
tech to consider: https://github.com/JonPSmith/EfCore.SoftDeleteServices

**Comment by collinbarrett** [comment]
this will be supported again once I finish the API work for #372 . however, I do not plan to add support back for the current json PR method of updating data. soft delete will be implemented at the API update layer.
