### ISSUE TITLE
kano list scrip 

### ISSUE THREAD

**Issue by kano1** [collinbarrett/FilterLists#720]
i make this filter lighter by not filtering domains that might be very high

popup ads & ads malware list
https://raw.githubusercontent.com/kano1/I/master/adware_Scrip.txt
privacy & phising malware list
https://raw.githubusercontent.com/kano1/Kano/master/Spyware_Scrip.txt

**Comment by bogachenko** [comment]
Maybe I'm wrong, but shouldn't the mirror have the same domain?

Well, as if, github will be unavailable you using another domain, but not the same ...

**Comment by collinbarrett** [comment]
A "mirror" in the sense of FilterLists should be the exact same document hosted somewhere else. If you make a lighter version of a list, we should treat that as a new list and link it back to the original as a "fork" relationship of the original.

Thanks!

**Comment by kano1** [comment]
thank you for the instructions

**Comment by tsugami1** [comment]
will this block all malware?

**Comment by kano1** [comment]
not all this is just extra protection by random antivirus detec
this only covers a small part of what I scan through https://www.virustotal.com/gui/home/url
will help you protect you against what is not blocked by antivirus 
extra protection by random  block popup and spam , phising , hacking and bad sofware

**Comment by tsugami1** [comment]
whether all popups are malware?

**Comment by kano1** [comment]
on a number of Torren sites or a movie watching site all detec ass malware by virus total
My notes when using Malbyte all spam sites are detected as malware , phising , spam
maybe because they offer a lot of fraud and some of them insert something dangerous
