### ISSUE TITLE
add SNAFU (privacy/adblock) list

### ISSUE THREAD

**Issue by RooneyMcNibNug** [collinbarrett/FilterLists#735]
https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
    
    FilterListLanguage = EN
    FilterListMaintainer = RooneyMcNibNug
    FilterListTag = Ads Privacy
    Fork = https://github.com/RooneyMcNibNug/pihole-stuff
    Language = English
    License =  WTFPL (http://www.wtfpl.net/)
    Maintainer = rooneymcnibnug

Let me know if you need anything else from my end for this.

**Comment by Atavic** [comment]
*Syntax Name: Domains*

Hi, hope you see the progressive values in address lists as:

```gigya.com
exacttarget.com```

or the scripting engines behind: 

```ads.tremorhub.com
perimeterx.net
t.eloqua.com```

...maybe ignoring the subdomain may help, as they will definitely change.

**Comment by Atavic** [comment]
*Syntax Name: Domains*

Hi, hope you see the progressive values in address lists as:

```marketo.com
exacttarget.com```

...or the scripting engines behind: 

```ads.tremorhub.com
collect.igodigital.com
perimeterx.net
t.eloqua.com```

maybe ignoring the subdomains may help, as they will definitely change.

**Comment by Atavic** [comment]
*Syntax Name: Domains*

Hi, hope you see the progressive values in address lists as:

```
marketo.com
exacttarget.com
```

...or the scripting engines behind: 

```
ads.tremorhub.com
collect.igodigital.com
perimeterx.net
t.eloqua.com
```

maybe ignoring the subdomains may help, as they will definitely change.
