### ISSUE TITLE
Filters_updating

### ISSUE THREAD

**Issue by existential-fallacy** [collinbarrett/FilterLists#736]
{
        "id": 1295,
        "emailAddress": "intr0@intr0.com",
        "description": "iVOID.hosts is dedicated to providing AdGuard Pro for iOS users with custom built, privacy & security focused hosts files. Also for use with Linux workstations & uBlock Origin for Firefox.",
        "homeUrl": "https://intr0.com/",
        "issuesUrl": "https://gitlab.com/intr0/iVOID.GitLab.io/issues",
        "licenseId": 19,
        "name": "iVOID.hosts",
        "publishedDate": "2018-07-09",
        "syntaxId": 1,
        "updatedDate": “2019-03-27T20:47:16+00:00",
        "viewUrl": "https://gitlab.com/intr0/iVOID.GitLab.io/raw/master/iVOID.hosts",
        "viewUrlMirror1": "https://notabug.org/-intr0/iVOID/raw/master/iVOID.hosts"
    },

    {
        "id": 1296,
        "emailAddress": "intr0@intr0.com",
        "description": "DomainVoider is dedicated to providing AdGuard Pro for iOS users with custom built, privacy and security focused filters using a simplified adblocking format. Also for use with uBlock Origin for Firefox.",
        "homeUrl": "https://intr0.com/",
        "issuesUrl": "https://gitlab.com/intr0/DomainVoider/issues",
        "licenseId": 19,
        "name": "DomainVoider",
        "publishedDate": "2017-11-11",
        "syntaxId": 3,
        "updatedDate": "2019-03-27T21:25:33+00:00",
        "viewUrl": "https://gitlab.com/intr0/DomainVoider/raw/master/DomainVoider.txt",
        "viewUrlMirror1": "https://notabug.org/-intr0/DomainVoider/raw/master/DomainVoider.txt"
    },

[FilterUpdates.txt](https://github.com/collinbarrett/FilterLists/files/3015484/FilterUpdates.txt)

**Comment by existential-fallacy** [comment]
Thank-you. I do have a question. The # count of each of my filters has remained @ 89,xxx since first being listed. Perhaps it was naïveté on my part, though I presumed there was a system in place to auto-count each filter-lists' # of filters, which would update on more or less of a regular timing / listing. Please advise.

**Comment by collinbarrett** [comment]
Hey, good question. FilterLists does crawl and estimate the number of rules in most of the lists. This count is not updated very frequently, though. A conservative estimate is once-a-month. I hope to speed this up in the future with improvements to the app's design, but that's what it is at the moment.

**Comment by existential-fallacy** [comment]
Thanks, Collin. And for all you do!
