### ISSUE TITLE
new FilterLists Hub launched at hub.filterlists.com

### ISSUE THREAD

**Issue by ameshkov** [collinbarrett/FilterLists#754]
Hi Collin, let me please share an idea with you, maybe you'll find it interesting.

Every filter list author possesses valuable knowledge about ad blocking, but at the moment there is no place where they can share this knowledge or ask questions. It'd be nice to have such a place. This could start as a chat or a discord community, and evolve into an MDN-like hub with all the necessary information collected and structured.

At first, I wanted to create something like this myself, but that seems wrong - I think it must belong to someone independent, or (ideally) be a community effort. And that's when I thought about you :)

At this point, I'd just like to ask what do you think about this idea in general? Does it make sense to you, and if it does, would you like to participate?

**Comment by collinbarrett** [comment]
Hey, that's a great idea.

I know there is https://forums.lanik.us/, but it is fairly tied to the EasyList lists. Some chatter on reddit and various GitHub repos. Is there not a general adblocking community space? hmm...

Outside of just building FilterLists, I am personally not super involved in the adblocking community (not for lack of interest, just lack of time). So, I am not sure I would be the right one to get the ball rolling on this. But, I'd be happy to support it for sure.

Will keep this open for discussion.

**Comment by DandelionSprout** [comment]
Such a thing actually exists to some degree already, in the form of https://github.com/DandelionSprout/adfilt/issues/7. However, it's merely a single-thread discussion place, whose userbase focuses almost entirely on uBO and Nano.

**Comment by ameshkov** [comment]
> Such a thing actually exists to some degree already, in the form of DandelionSprout/adfilt#7. However, it's merely a single-thread discussion place, whose userbase focuses almost entirely on uBO and Nano.

@DandelionSprout yes, that's exactly the kind of discussions and knowledge sharing I meant! It's just a github issue is not ideal when there are more participants, and it lacks structure.

Have you ever thought about expanding it into something like a Gitter or Discord community (here's an [example](https://github.com/chat-rooms))? I'd like to emphasize, that I can offer some serious help with establishing it and be a major contributor (content, coding, design, inviting filter list authors, etc), but I just want someone else to be in control to make sure there's no bias.

**Comment by DandelionSprout** [comment]
>Have you ever thought about expanding it into something like a Gitter or Discord community (…)?

That'd be weeks or months ahead in time at least, as I'm still pretty scared about social media after I had some pretty bad experiences on Twitter and cartoon forums from 2011-17.

**Comment by collinbarrett** [comment]
Do you think chat-based (like gitter / discord) is preferable to forum-based (like discourse)? I tend to lean towards forum-ish so conversations are a bit more long-term / searchable, but that's not a strong opinion.

**Comment by DandelionSprout** [comment]
I currently have no particular opinion either way, except that ***if*** the userbase is sufficiently large, then a Discord forum could be split into multiple channels that function as threads. One for problem reports, one to ask for technical/syntax help, one to discuss the wider adblocking community, and possibly one or two other channels as well.

**Comment by existential-fallacy** [comment]
What of a simple IRC?

**Comment by existential-fallacy** [comment]
@ameshkov intr0 here from the beta days...

**Comment by ameshkov** [comment]
Here's how I see it. Please correct me if I am wrong.

### Audience

1. Filter list authors and contributors
2. People who are trying to create their own filters (we all know it's not simple nowadays, filters syntax became quite complicated)

I'd like to emphasize that this is not for regular users. They have plenty of places where to report an issue already.

### Purpose

1. Asking questions
    * How to make a rule that will do this or that?
    * Why is this rule not working as intended?
    * Should this or that be blocked?
    * etc, etc
2. Sharing knowledge
	* Did you know that "something" can be done in a better way?
	* Suggesting new blocking techniques
    * Here's a complicated case with this or that 
    * etc, etc
3. Raising issues and communicating with developers
	* Ad blockers lack this or that feature, we'd like it to be changed
		(for instance, "You should let cosmetic rules target URLs, not just domains!")
	* Here's a case that cannot be tackled currently. Developers, do something and fix this
	* etc, etc

### Platform requirements

1. Easy to use:
	* Web-based, no additional software required.
	* If this is a chat: IRC-compatible.
2. Privacy-friendly:
	* Open and transparent.
	* Let people stay anonymous if they want.
	* Require as less as possible to login. Registering with a phone number is a no go.
	* Ideally, allow people to login with their Github or Gitlab account.
3. Structure:
	* Ideally: threads / topics / sections
	* If this is a chat: it should be complemented with something permanent to store important things. For instance, it could be a Github repo.

Have I missed anything important?

**Comment by DandelionSprout** [comment]
I don't have a whole lot of thoughts about all this, but regarding the **Audience** section, I'd dedicate at least one forum section to teaching interested laymen how to make their own adblock lists.

I think that it's highly unideal that less than 1,000 people worldwide currently know how to make adblock lists (For instance, there are only 2 people in the entirety of the Kingdom of Norway who currently know how to make a list), and it could be a huge adblock community revolution if more people learned how to make them.

**Comment by ameshkov** [comment]
> I don't have a whole lot of thoughts about all this, but regarding the Audience section, I'd dedicate at least one forum section to teaching interested laymen how to make their own adblock lists, thus it'd technically be for regular users per se.

That's who I meant by "people who are trying to create their own filters".
Rephrased it all a little bit, and added a "teaching" point there.

> I think that it's highly unideal that less than 1,000 people worldwide currently know how to make adblock lists (For instance, there are only 2 people in the entirety of the Kingdom of Norway who currently know how to make a list), and it could be a huge adblock community revolution if more people learned how to make them.

Yeah, that could improve things a lot if people were not just reporting issues, but were actually contributing to filters lists.

**Comment by collinbarrett** [comment]
I've been working on DevOps stuff as of late, trying to container-ize FilterLists as well as some other apps I host. Once I wrap that up, I'm not opposed to spinning up the platform for this just to see if it takes off. I think I am leaning towards a [Discourse](https://hub.docker.com/r/discourse/base/) instance at something like `filterlists.com/community`.

So, no promises on timeline (but, I'm thinking withing the next couple of months). But, if someone else wants to get on it sooner or discovers that in fact something like this already exists elsewhere, I'm happy to put a link to it on FilterLists.

**Comment by ameshkov** [comment]
@collinbarrett I've just read about Discourse and it seems to be the ideal forum-based solution. Once I am back from in May, I'll help you with it. What are your requirements? Would you like to run a docker image with it?

**Comment by collinbarrett** [comment]
Yeah, I can spin up a docker instance pretty easy. I'm happy hosting it. The biggest need will be assistance with moderating, answering questions, etc. I do not have much experience in online community-building. And, I am not particularly skilled and creating adblock rules myself (though I want to learn).

**Comment by DandelionSprout** [comment]
>And, I am not particularly skilled at creating adblock rules myself (though I want to learn).

I could've very well guided you through it, if you had some spare time and a specific type of website content you'd want to remove/edit.

Some resources to start out with.

* [How to make a list subscribable](https://sproutsluckycorner.wordpress.com/2018/07/21/how-to-create-your-own-adblock-list-for-dummies/)
* [A basic template with crucial metadata](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Adblock%20list%20templates/Adblock%20list%20template%20-Beginner-.txt)
* To create some entries to start out with, Nano, uBO, and most versions of ABP have element selector tools that try to create an entry for you.

**Comment by DandelionSprout** [comment]
I realised something.

So I presume that such a docker(?) would have the full support of the AdGuard team. And I could pull some strings to see if I can get the uBO and Nano teams interested.

On the other hand, how would we get the ABP and EasyList teams to even notice the very existence of such a decker?

**Comment by collinbarrett** [comment]
In my opinion, slow growth, at least to start, would be preferred. With a publicly-indexable forum like Discourse, over time I would expect growth to be driven organically from search engines. If it is useful for people, I think people will hear about it.

**Comment by collinbarrett** [comment]
Update:

I am preparing to convert the devops build/deployment process in the coming days over to Azure Pipelines and docker/docker-compose. Preview what this will look like [here](https://github.com/collinbarrett/FilterLists/tree/docker-devops#building-and-running-locally) in the docker-devops branch.

As soon as that's up and running, spinning up this community will be my next priority.

**Comment by mtxadmin** [comment]
My 2 cents about this.

1. https://forums.lanik.us/ looks good, but it is about EasyList only. It's a pity.
2. And PhpBB for a new resource is not very good solution. It lacks many features, at least comment trees, good antispam solution, autoupdate solution.
3. Chats are good only for the speed, but not for anything else. It is the worst way, as for me.
4. Registration are pain in the ass. People are not tend to register in some small resource :-(  I say it from experience with good friends and my former blog. Most people hate registrations.
5. On the other hand, many big social platforms like Facebook are not suitable for discussions. Except, maybe Reddit and such?
6. A friend of mine made a blog on Github Pages. It was very small and not feature-rich, but it was an interesting way to use Github engine.

**Comment by collinbarrett** [comment]
And, we're live! I literally just got it up and running with a bare bones configuration. Over the next few days, I'll be further exploring the settings and seeding some discussions and categories, etc. Feel free to check it out and share any more thoughts/feedback.

https://hub.filterlists.com/

**Comment by ameshkov** [comment]
@collinbarrett awesome! 

I've just brought some content there:)
https://hub.filterlists.com/t/this-might-be-the-end-of-filter-lists/14
