### ISSUE TITLE
Filter Break on facebook

### ISSUE THREAD

**Issue by kano1** [collinbarrett/FilterLists#757]
EasyPrivacy 
can't comment on facebook
![can't comment](https://user-images.githubusercontent.com/29359856/56078253-2f720500-5e10-11e9-93a8-165c482f8d86.png)

**Comment by kano1** [comment]
![foto](https://user-images.githubusercontent.com/29359856/56078301-b9ba6900-5e10-11e9-86c8-f62c384978a6.png)

**Comment by kano1** [comment]
I am worried that the number of paranoia will increase with Facebook and cause bad issues so that Facebook users are reduced

**Comment by kano1** [comment]
![asdsd2323](https://user-images.githubusercontent.com/29359856/56081324-3b70bd80-5e36-11e9-9718-9b921a1221c9.png)

**Comment by collinbarrett** [comment]
https://github.com/collinbarrett/FilterLists#adding-or-updating-rules

**Comment by bogachenko** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Won't be "fixed" because the filter isn't the issue.

**Comment by kano1** [comment]
Ajax is web-based programming to create interactive web applications so that web pages don't have to be reread in their entirety every time a user makes a change. This will increase interactivity, speed, and this is ajax fotos loging there is a possibility that Facebook updates will be hampered and require time

like the user needs their own white list so I ask the filter unbreak whether to add it to the white list

**Comment by ryanbr** [comment]
If there was an issue, more than one person would report it.

**Comment by ryanbr** [comment]
Also I've tested it, and it works fine. PEBKAC.

**Comment by kano1** [comment]
mybe that means I have to reinstall my adobe for easy privacy
