### ISSUE TITLE
I would like to add my list

### ISSUE THREAD

**Issue by DataMaster-2501** [collinbarrett/FilterLists#758]
I would like to add my list to the directory.
https://github.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts

**Comment by collinbarrett** [comment]
If you want to do so yourself, feel free to submit a PR. Alternatively, feel free to provide more of the details about the list in this issue and someone else can submit a PR when they can.

More info here: https://github.com/collinbarrett/FilterLists#adding-or-updating-lists

**Comment by DataMaster-2501** [comment]
Please  for give me but I'm not understanding everything in here-> https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar
So I will list what I do understand.
This is a /etc/hosts list that I made by hand of domains & subdomains.
it is for Linux & Android
it will work with adaway, Blokada, uBlock & AdClear if someone knows how to import it to that app🙄
& it will work with any app that works with /etc/hosts files.
This file is setup for both IPv4 & IPv6
This list blocks Ads, Analytics/Tracking Services
GNU AFFERO GENERAL PUBLIC LICENSE
Version 3, 19 November 2007
Is there anything more you need to know?
