### ISSUE TITLE
turkish hosts (compatible with adaway) 

### ISSUE THREAD

**Issue by xorcan** [collinbarrett/FilterLists#762]
https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt
https://raw.githubusercontent.com/bkrucarci/turk-adlist/master/hosts
https://raw.githubusercontent.com/biroloter/Mobile-Ad-Hosts/master/hosts

**Comment by DandelionSprout** [comment]
*turk-adlist* has already been added. I'll try to add the other two as well.
