### ISSUE TITLE
The Ransomware Tracker Domain Blocklist filter is not updated. Fails

### ISSUE THREAD

**Issue by Jose1971AB** [collinbarrett/FilterLists#770]
Hello friends ... good night.

> First of all, excuse the translation, I am with the help of the google translator.

I use Firefox 64 Bit uBlock origin and for some time I use a filter that I incorporate in Custom ->

**Ransomware Tracker Domain Blocklist whose** url is
**https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.tx**t

It's a filter to block Ransomware (or something like that). This filter is, correct me, as a compendium of others for the same purpose

**The problem is that for 3 days I can not update it. It throws me an error that says ... "a network error prevents resources from being updated".**

So, I do not know if this filter has become obsolete or without maintenance and has stopped working.

**What solution do you give me? ...**

And in the event that it no longer works ... **what other filter can you propose as an alternative? ... Obviously it should be for the same purpose, to block Ransomware.**

Thank you very much and greetings

**Comment by Atavic** [comment]
```
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
```

Works fine. Maybe there's something in your setup blocking the site due to the *tracker* word inside the URL?

**Comment by Jose1971AB** [comment]
Hello @Atavic ... thank you very much for answering friend.

I do not know what he's referring to, I'm a basic user. If what you want to say is that if I have the URL or not imported, the answer is yes, I have been using that filter for a long time.

**Anyway today I have purged cache of all the filters in general and it has been updated, it works, I do not know what could have happened.**

I do not know if you know that there are old filters that have already stopped working, then, in case https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt fails again or becomes obsolete, **would you know about another alternative filter that serves the same purpose? ...**

Thank you very much friend for replying and greetings.

**Comment by Atavic** [comment]
I don't know, but if you harden your system, then ransomware is blocked. On Windows, by
*disabling Windows Script Host* you prevent most common ransomware.

See: https://github.com/securitywithoutborders/hardentools

**Comment by Jose1971AB** [comment]
Hello @Atavic 
Thanks for the information, I will take into account the link you sent me.
Where can I ask in Github if there is an alternative to that filter? ... or who can know? ... I have been researching in Google and expressly in https://filterlists.com/ and I can not find anything

Greetings and thanks for the link

**Comment by Evanju1** [comment]
I have done a number of trials visiting a dark web site
ransomware is a very rare list so this may take a long time or it may appear that new malware is stronger than ransomeware
the last ransomware is 2018-08-12 but maybe you can still find ransomware with a list of the same domain that is still active

**Comment by collinbarrett** [comment]
Closing for now as not directly related to the FilterLists app, but please feel free to continue to discuss. I don't personally have any insight on the question.

**Comment by Jose1971AB** [comment]
Hello @ Evanju1, thank you very much for answering ...

You say...

> the last ransomware is 2018-08-12 but maybe you can still find ransomware with a list of the same domain that is still active

If you find out something, **I would appreciate it if you explained it in this post or in another section**, since I think the subject has been closed.

Anyway, thank you very much and greetings.

**Comment by Atavic** [comment]
Some of the ransomware blacklisted domains are included in more generic malware lists.
I looked for one random domain included in ransomwaretracker.abuse.ch and found that it's included into: *DShield.org-Suspicious-Domain-List*

So, if you have some of these malware lists, the ransomware domains were probably included and then they have been left out of the blacklist, once the malicious CC server has been taken down.

**Comment by Jose1971AB** [comment]
Hello everyone...

I come back to say that the filter https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt is still active and is being updated, at least so far. Maybe it was a momentary problem.

I wanted to communicate it in case there was someone that happened to me like me and was following this thread.

Regards and thank you all.
