### ISSUE TITLE
annotate list originality

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#775]
Okay, so here's the situation: Last week, gorhill added *Energized Blu Go Protection* to uBlock Origin.

Although [it was removed just two days later](https://github.com/uBlockOrigin/uBlock-issues/issues/553) because of severe licencing issues and lack of maintenance, and how it could be argued that gorhill wasn't doing enough research before he added that list, I also found it puzzling that he chose to natively include a list whose 120,000 of its entries (out of 140,000 total) were taken from 54 other third-party lists under inoptimal conditions.

So, on the unconfirmed assumption that he browsed through FilterLists.com to find such a list to add to uBO, I think it could be necessary for us to better mark which lists that are original work, and which ones that are just aggregates of other lists (The latter of which is a rampant problem for hosts-format lists in particular, due to the sheer prevalence and popularity of hosts file aggregate lists like 1hosts, Steven Black, hBlock, Energized, etc.), in order to better show which lists that contain unique content, and to help people avoid unintentionally subscribing to duplicate lists.

Option 1) Create an `original` tag. This could likely be implemented within days, but it'd require hours upon hours of work to apply it to the ≥700 filterlists that deserve it.

Option 2) Create a subheader in the list details that shows which lists an aggregator is based on, à la the *Maintained by (…)* subheader. This'll require considerably more work, both coding- and .json-wise.

Option 3) Both of the above.

Option 4) Create an `aggregate` tag. This requires the least amount of work by far, but does not give sufficient credit to the aggregates' source lists.

**Comment by collinbarrett** [comment]
Agreed 100%.

What you are describing is where I was going with the [`Forks`](https://github.com/collinbarrett/FilterLists/wiki/Fork) and [`Merges`](https://github.com/collinbarrett/FilterLists/wiki/Merge) relationships.

However, currently, these are not visible at all in the UI (#287). And, it would be nice to provide sorting mechanisms based on if the list is original or not such as auto-generating `original` tags like you suggest or rolling it into the idea of a "FilScore" (for lack of a better name) (#371).

So, I think the best way forward is to keep using the forks and merges models in the data, but we need to expose those relationships in a user-friendly way in the UI, for sure.

**Comment by collinbarrett** [comment]
closing into #371
