### ISSUE TITLE
Please update description of "id": 1525 in FilterList.json

### ISSUE THREAD

**Issue by bongochong** [collinbarrett/FilterLists#779]
It should now read as follows:

> Is a P2P-format IP block list suitable for use in torrent clients like qBitTorrent and Transmission under any OS. The list is merged from BlueTack levels 1 and 2, then deduped and sorted. This will also come in especially handy on public trackers. This file will be updated every two weeks.

Many thanks!

**Comment by bongochong** [comment]
done with description updates for a while by the way! sorry if i layed these on a bit too fast.

**Comment by bogachenko** [comment]
You could write them in one issue. not 3

**Comment by bongochong** [comment]
> 
> 
> You could write them in one issue. not 3

Oof. Really sorry about that! Will of-course do so in future updates.
