### ISSUE TITLE
Sorting by update time isn't available

### ISSUE THREAD

**Issue by adnage19** [collinbarrett/FilterLists#794]
Hello, there is no option to enable sorting by update time. It was always available, but not anymore.

**Comment by collinbarrett** [comment]
Thanks, @adnage19 . It has been temporarily disabled since the FilterLists service that updates the last updated date data has been disabled temporarily. It will be added back when #784 is completed.

**Comment by Laicure** [comment]
Hi @collinbarrett, will this be still implemented?
I don't want to look at and use out-dated filter sources.

Thanks and more powah!

**Comment by collinbarrett** [comment]
I certainly want to. But, no timeline estimate. It requires the server to continuously crawl the lists and monitor for updates. I need to re-engineer the bot to get that working again. Track #784 for updates on that.

**Comment by Laicure** [comment]
Thanks for the response, @collinbarrett!
I was just sad the "High Priority" tag was removed.
Anyway, no rush. I really like your list!
