### ISSUE TITLE
Order by filtercount missing??

### ISSUE THREAD

**Issue by 3k2** [collinbarrett/FilterLists#798]
I remember sometime ago there was option at the bottom of the page to order the list how many filters there and when it was last time updated. 

would it be possible to add these options back or am I remembering wrong they never existed in first place?

**Comment by collinbarrett** [comment]
It's disabled temporarily until #784 is resolved. I definitely plan to add it back, but the service that calculated rule counts needs to be rewritten as it was bringing my server to a crawl.
