### ISSUE TITLE
add or update lists

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#799]
Batch of lists from anonymous contributor to verify we have indexed or to add:

Sinfonietta  (4 categories)
https://github.com/Sinfonietta/hostfiles

UT1 (56 categories)
https://dsi.ut-capitole.fr/blacklists/index_en.php

UT1 (all)
ftp://ftp.ut-capitole.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz

AntiSocial Blacklist
https://theantisocialengineer.com/blacklist

Phishing Army (not extended)
https://phishing.army/download/phishing_army_blocklist.txt

PhishTank
https://www.phishtank.com/developer_info.php

Torrent Trackers
https://zackeryfretty.com/block-public-bittorrent-traffic-on-your-server-using-hosts/

Cryptojacking Campaign List
http://dehakkelaar.nl/lists/cryptojacking_campaign.list.txt

sjhgvr The Blocklist
https://dbl.oisd.nl

sjhgvr Hosts
http://hosts.oisd.nl/

sjhgvr The Blocklist mobile
https://dblmobile.oisd.nl/

sjhgvr Hosts mobile
https://hostsmobile.oisd.nl/

sjhgvr Mirror https://github.com/ookangzheng/dbl-oisd-nl

https://osint.bambenekconsulting.com/feeds/c2-dommasterlist.txt

**Comment by DandelionSprout** [comment]
* Already added: Sinfonietta
* Useless list format: UT1, PhishTank, Bambenek Consulting
* Lacks a raw file: Torrent Trackers
* Downright parodical due to being an aggregate of around **500** lists (but I'll add it still): sjhgvr

The other 3 I have no substantial objections to.
