### ISSUE TITLE
mandate specifying https version of URLs when available

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#804]
I know that it's probably a bad idea to create additional barriers for potential contributors, but in order to avoid situations where contributors add HTTP links to lists/homepages that actually do support HTTPS, I strongly recommend the use of https://github.com/ilGur1132/Smart-HTTPS, such that I wonder if the use of it could be declared a contributor guideline or not? In particular, https://github.com/collinbarrett/FilterLists/pull/801 taught me that such mislinking does occur from time to time by many (if not most) contributors (Even by me if I feel extra forgetful).

Note that while *HTTPS Everywhere* is a similar and far more popular extension, I'd consider it to be perfectly presumable that EFF hasn't added conversion entries for 100% of all list-hosting sites out there, also because many of the sites are pretty small.

**Comment by collinbarrett** [comment]
Agreed. Good idea.

Related to #21 (goal is to automatically update the data if a valid https url is found for an http link)

But, we could build that check right into the PR build gate and have the build pipeline verify that there is not a valid https version of any new http versions, and fail with a warning message if there are.

I like it.

**Comment by collinbarrett** [comment]
rather than putting the burden on contributors, I think it's better to have the url-validation bot that I'm hoping to rebuild in #21 handle this and notify or auto-update urls that are available via https. closing this issue and will address as a feature of #21
