### ISSUE TITLE
Clicking on "< Subscribe" or "< View" does not open submenu.

### ISSUE THREAD

**Issue by gwarser** [collinbarrett/FilterLists#884]
- search for EasyList
- click on "Details"
- click on "< Subscribe"
- button get focus but nothing more happens

I believe reported here: https://www.reddit.com/r/uBlockOrigin/comments/ciz7se/ublock_filters_plus_custom_filter_list_not/

Checked in Firefox Nightly and Chrome stable on Manjaro KDE

**Comment by collinbarrett** [comment]
I think it's resolved now after 7b7385f1e711d05f7378c79bc85ba2074a330e8d. Let me know if not, and I'll re-open.

Thanks for reporting!

**Comment by gwarser** [comment]
I don't think it's fixed. Don't see CSP errors in console.

**Comment by collinbarrett** [comment]
Ah. I was seeing the issue on some of the lists with a single subscribe URL, and the csp change resolved that. But, I can still reproduce the fact that the subscribe buttons with multiple subscribe urls are broken..

**Comment by collinbarrett** [comment]
They are somewhat usable again. CSS is still janky... I hate css. :)

**Comment by gwarser** [comment]
Ugly, but works :)

**Comment by collinbarrett** [comment]
lol, yep, I still need to cleanup the CSS. I'm going to reopen to ensure that happens. Hopefully tonight.

Thanks.

**Comment by collinbarrett** [comment]
Closing as irrelevant since launching new UI.
