### ISSUE TITLE
update 1Hosts

### ISSUE THREAD

**Issue by badmojr** [collinbarrett/FilterLists#886]
Greetings! 
I'm the maintainer, and here propose some changes/additions to the 1Hosts filterlists.
Please take a look! Thanks.

# Description
Protects your 'data' & eyeballs from being auctioned  to the highest bidder. 

# The Files
name: 1Hosts (Pro)
urls:
https://1hos.cf/Pro
https://1hos.cf/Pro.txt (domains only)

name: 1Hosts (complete)
urls:
https://1hos.cf
https://1hos.cf/complete
https://1hos.cf/complete.txt (domains only)

name: 1Hosts (mini)
urls:
https://1hos.cf/mini
https://1hos.cf/mini.txt (domains only)

# Information
homepage: https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360
License: Dandelicence, https://github.com/DandelionSprout/Dandelicence/blob/master/DandelicenceV1.md
Maintainer: badmojr
contact:
badmojr@gmail.com
https://t.me/badmojr
https://github.com/badmojr

Edit: Changed the urls.

**Comment by collinbarrett** [comment]
I think this is closed by #894 .
