### ISSUE TITLE
Add onion services counterparts to blocked URLs

### ISSUE THREAD

**Issue by rawuUuUuUuUul-GOAAAAAAAAAAAAL** [collinbarrett/FilterLists#90]
This is for example relevant here: https://github.com/uBlockOrigin/uAssets/issues/376

As an example `duckduckgo.com/t/` is blocked, but its onion service counterpart (`https://3g2upl4pq6kufc4m.onion/t/`) isn't.

**Comment by collinbarrett** [comment]
Hi @rawuUuUuUuUul-GOAAAAAAAAAAAAL , this is a great idea. But, it is outside the scope of this project. FilterLists is just an index of lists that already exist. This sounds like it requires creating a new list. If you or someone else decides to take up this task, we'll be happy to index it on FilterLists! But, creating and maintaining the onion list itself is not something that FilterLists will take on. Thanks.
