### ISSUE TITLE
Re-check EasyList Thailand list location

### ISSUE THREAD

**Issue by kowith337** [collinbarrett/FilterLists#91]
When I try to view or add [Easy List Thailand](https://github.com/easylist-thailand/easylist-thailand) list, it seems the list isn't found, maybe have something change (guess it's due to `/subscriptions/` directory name was changed to `/subscription/`)
![image](https://cloud.githubusercontent.com/assets/16535467/25747643/6255cc20-31d2-11e7-81d0-d55de6658900.png)
![image](https://cloud.githubusercontent.com/assets/16535467/25747646/654b3104-31d2-11e7-98a0-38ed916c8347.png)

**Comment by collinbarrett** [comment]
Thanks, @kowith337 !
