### ISSUE TITLE
fix Docker Hub credentials

### ISSUE THREAD

**Issue by collinbarrett** [collinbarrett/FilterLists#929]
Pushes to Docker Hub all of a sudden started failing. I can't logon to their site, either. Password reset emails aren't arriving.

Also, I've been really frustrated that Docker Hub [doesn't support 2FA](https://github.com/docker/hub-feedback/issues/358#issuecomment-524061949).

I signed up for the GitHub package registry beta, but still waiting for an invite...

Tried tweeting @Docker as well as emailing support@docker.com. We'll see if I hear anything.

Until some solution to this problem is implemented, production site won't be updated via CD.

**Comment by collinbarrett** [comment]
Resolved for now by creating a new Docker Hub account: `collinbarrett2`. Never heard anything from Docker support... annoying.

**Comment by shaneakr** [comment]
2FA was launched today
