### ISSUE TITLE
filterlists.com: Remove "Officially unsupported" Fanboy's lists

### ISSUE THREAD

**Issue by stanlane** [collinbarrett/FilterLists#93]
Can you please remove these filters from [https://filterlists.com/ filterlists.com]?:
* [https://www.fanboy.co.nz/fanboy-korean.txt KOR: Fanboy's Korean]
* [https://www.fanboy.co.nz/fanboy-swedish.txt SWE: Fanboy's Swedish]
* [https://www.fanboy.co.nz/fanboy-vietnam.txt VIE: Fanboy's Vietnamese]

All of they contain this text:
>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>!!!!!!!!!!!!!!!! Officially unsupported !!!!!!!!!!!!!!
>!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Can you please remove all these filters so someone else start working on them? Its counter productive to have them listed, they don't do their job.

**Comment by collinbarrett** [comment]
Thanks for the suggestion, @stanlane . The purpose of this site is to index all known filter lists, though, whether they are actively maintained or not.

I do have a feature in the queue that, once implemented, will make it easier to spot which lists are stale. See #6.

In the near-term, you can also look back at this commit before all lists were combined into one to spot "stale" lists: https://github.com/collinbarrett/FilterLists/blob/d739f88a79692089fb58c6a9b85a6ad73d2f51b5/json-data/stale.json

Closing as won't fix.
