### ISSUE TITLE
consider supporting polyfills for older browsers

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#938]
Welcome! Just like on title, page turns white after selecting software.

From console:
```
TypeError: r.filter(...).flatMap is not a function
Stack trace:
onFilter@https://filterlists.com/static/js/main.8781a07d.chunk.js:1:45833
value/</c</<@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:300472
value/</c<@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:300446
value/<@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:300418
value@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:300286
value@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:299542
t/n.renderComponent@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:294756
Ja@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1101057
Wa@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1083274
Fa@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1080294
ja@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1078854
yo/<@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1040869
t.unstable_runWithPriority@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1115321
po@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1040598
yo@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1040815
mo@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1040750
Aa@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1079281
Dn@https://filterlists.com/static/js/2.89bf0ff7.chunk.js:1:1030371
  2.89bf0ff7.chunk.js:1:1071059
TypeError: r.filter(...).flatMap is not a function
main.8781a07d.chunk.js:1:45833
```

Browser: Waterfox 56.2.13

Update: FlatMap is from FF 62, so I guess that's the problem.
`https://caniuse.com/#feat=array-flat`

**Comment by collinbarrett** [comment]
I built the new UI using `create-react-app`, and I thought that it had Webpack wired in a way that it would transpile to support older browsers. But, I guess magic has its limits... I'll look into this a bit to see if there is a feasible solution. Thanks.

**Comment by collinbarrett** [comment]
In addition to supporting the specific use case of the OP (`flatMap` unspported in a variant of an older Firefox version), polyfilling to support IE and other older/less popular browsers could be useful as well. I know IE especially could be useful since we index so many TPL lists.

More info on how we could do that:
https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md

**Comment by collinbarrett** [comment]
If we do add support for IE, reminder to drop [this](https://github.com/collinbarrett/FilterLists#internet-explorer) from README.

**Comment by DandelionSprout** [comment]
I distinctly remember experimenting with Polyfill for FilterLists.com for the sake IE 11 for a couple of weeks or so. Not only did it fail to make the site truly loadable, but we also had a privacy white-knight take issue with it (#751),

**Comment by collinbarrett** [comment]
Ah, yeah, good memory. I think their complaint was loading a script from a 3rd-party domain. But, yeah. I'm not going to spend much time on that, but I might give it a whirl again now that I've learned a bit more how things work.

**Comment by collinbarrett** [comment]
Closing as won't implement for now. While I like the idea of maintaining backwards compatibility with older, lesser-common browsers, I just don't have the time or the help to make that happen.

**Comment by hawkeye116477** [comment]
Ok, anyway for me it's not needed now, cuz fix will come when will be next release of Waterfox Classic :smile:
