### ISSUE TITLE
add Anti-AutoTranslation-List

### ISSUE THREAD

**Issue by Nebula-Mechanica** [collinbarrett/FilterLists#944]
### Adding or Updating Lists?

List, containing annoying auto-translated clones of Stackoverflow and similar websties.

https://github.com/Nebula-Mechanica/Anti-AutoTranslation-List

**Comment by collinbarrett** [comment]
Could you provide us with any of the information described [here](https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar) that you want listed on FilterLists? Thanks.

**Comment by Nebula-Mechanica** [comment]
"description": "List containing auto-translated site clones of StackOverflow and other services.",
    "descriptionSourceUrl": "https://github.com/Nebula-Mechanica/Anti-AutoTranslation-List",
    "homeUrl": "https://github.com/Nebula-Mechanica/Anti-AutoTranslation-List",
    "issuesUrl": "https://github.com/Nebula-Mechanica/Anti-AutoTranslation-List/issues",
    "licenseId": 11,
    "name": "Anti-AutoTranslation-List",
    "publishedDate": "2019-08-29T00:00:00",
    "syntaxId": 2,
    "viewUrl": "https://raw.githubusercontent.com/Nebula-Mechanica/Anti-AutoTranslation-List/master/anti-autotranslation-list.txt",
    "viewUrlMirror1": "https://gitcdn.xyz/repo/Nebula-Mechanica/Anti-AutoTranslation-List/master/anti-autotranslation-list.txt",
    "viewUrlMirror2": "https://rawcdn.githack.com/Nebula-Mechanica/Anti-AutoTranslation-List/master/anti-autotranslation-list.txt"

**Comment by Nebula-Mechanica** [comment]
Also I am unsure where tags are defined, but I think that "annoyances" fits well.

**Comment by collinbarrett** [comment]
Cool, thanks. Somebody will create a PR to add that when we can. The full data model that we index is [here](https://github.com/collinbarrett/FilterLists/wiki/Data-Model_sidebar). The tags are defined [here](https://github.com/collinbarrett/FilterLists/blob/master/data/Tag.json).
