### ISSUE TITLE
sorting many of the columns in descending order doesn't work

### ISSUE THREAD

**Issue by DandelionSprout** [collinbarrett/FilterLists#949]
To reproduce:

1) Go to FilterLists.com.
2) Click on the header of the *Software* column (or *Languages*/*Tags*).
3) See that it sorts by most first, and that the top arrow becomes orange.
4) Click anywhere on the same header again, incl. on the bottom arrow.
5) See that nothing changes, it still sorts by most first, and none of the arrows change colour.

(So far only tested in Chrome on Windows, and not on Android.)

**Comment by DandelionSprout** [comment]
Note that the bottom arrow seems to work for *Name* upon closer inspection, but not for the other three sortable column headers.

**Comment by collinbarrett** [comment]
Ah, good catch. That _was_working a week or so ago when I first implemented the sorting in the new UI, but somehow it broke...

**Comment by collinbarrett** [comment]
Related to the `onChange` callback [here](https://github.com/collinbarrett/FilterLists/blob/994106430fad0a1984abfa608e58b88a156cfca6/src/FilterLists.Web/src/components/listsTable/ListsTable.tsx#L52).
