### ISSUE TITLE
IDCAC Nano expansion doesn't exists

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#955]
Just like on title, I tried to view I Don't Care about Cookies Nano expansion and seems that was only plan and doesn't exists yet (maybe someone used time machine and forgot that he is in 2019, not 2020...) . So maybe it should be rather commented or removed and re-added when it will be available .

**Comment by collinbarrett** [comment]
@DandelionSprout can you remind us what's up with this list? Thanks.

**Comment by DandelionSprout** [comment]
I had made a fully functional blueprint for such a list, but for it to be able to use `##+js(nanop-easy-set-cookie.js)` by default, Jspenguin placed ever more stringent requirements on the list before allowing it to do so, until the point where I can only presume that he lost track of it as well (let alone that I lost track of it long ago).

https://github.com/NanoAdblocker/NanoFilters/pull/331 provides most of the details behind it.

**Comment by DandelionSprout** [comment]
I've added the removal of the list to https://github.com/collinbarrett/FilterLists/issues/851, but I've got far more busy with hobbies recently than what was previously the case, so the stuff I list in that thread from time to time is up for grabs for anyone to do.
