### ISSUE TITLE
Addware redirecting to qma0.fafa.gdn

### ISSUE THREAD

**Issue by olea** [collinbarrett/FilterLists#97]
A nasty addware infects my Chrome and launchs arbitrary redirects first to qma0.fafa.gdn and then to the final add URL.

**Comment by collinbarrett** [comment]
Hi @olea , can you provide any further information? Does this happen when you visit filterlists.com? Or when you click on a link on filterlists.com? If so, which one?

**Comment by olea** [comment]
Uff.

I'm very sorry I confused you. What I want is ask you is to add qma0.fafa.gdn in your lists of bad addware.

Sorry if this is not the correct procedure.

**Comment by collinbarrett** [comment]
Thanks, @olea . No worries. Thanks for clarifying. Unfortunately, that is outside the scope of the FilterLists project, however. This site aims to just be a directory of all existing filter lists. If you want to get a domain included on a list, you will need to contact the creators/maintainers of the list directly.
