### ISSUE TITLE
fix empty space between columns 

### ISSUE THREAD

**Issue by hawkeye116477** [collinbarrett/FilterLists#970]
I noticed that at same places there is empty space between columns . For example:
![Screenshot_20190918_105512](https://user-images.githubusercontent.com/19818572/65133391-cf0c7280-da02-11e9-864e-6e70ae043aa3.png)
![Screenshot_20190918_105659](https://user-images.githubusercontent.com/19818572/65133561-1abf1c00-da03-11e9-9d4e-4787ebd1332b.png)

Related: https://github.com/ant-design/ant-design/issues/14689

**Comment by collinbarrett** [comment]
related: #942

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/92caa2d02c9a95caabf4809691d0102e0082198d

**Comment by collinbarrett** [comment]
^those two commits make it a lot better, but the solution is super hacky. I can't figure out how to make the Description column auto-resize. I'd like all other column widths to be fixed, but the Description column to auto-expand based on viewport width. If anybody can help, let me know.

**Comment by collinbarrett** [comment]
@hawkeye116477 Does this seem to still be an issue? If so, can you give me a guide on how to reproduce it (what filters/sorts/page to scroll to)? It's been awhile, and I can't seem to reproduce it now. Maybe Ant has automatically fixed it.

**Comment by hawkeye116477** [comment]
@collinbarrett No.
