### ISSUE TITLE
add mkb2091's lists

### ISSUE THREAD

**Issue by mkb2091** [collinbarrett/FilterLists#972]
I'd like to have my filter lists added, if they are suitable. They are a (yet) another aggregate list, but it does weekly DNS checks to remove dead domains, merges multiples different lists in different formats to all work in a single format, (probably only semi-unique feature) uses bad/malicious IP blocklists to find more domains to block. It also uses its own whitelisted&blacklisted domain lists

License: GPLv3(I've tried to ensure that it only uses GPLv3 compatible lists, so shouldn't have any licensing issues)

It blocks: Malware/Phishing,Adverts,Trackers,Coin mining

github: https://github.com/mkb2091/blockconvert
issues: https://github.com/mkb2091/blockconvert/issues
language: mostly english

urls:
Adblock Plus(blocks same as domains.txt, but also blocks IP addresses): https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/adblock.txt

Hosts file format: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/hosts.txt

Domain list: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt

Blocked IP address list: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/ip_blocklist.txt

DNS Response Policy Zone(RPZ) format: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.rpz

Whitelisted domains: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/whitelist_domains.txt

Whitelist in AdBlock Plus format: https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/whitelist_adblock.txt

**Comment by collinbarrett** [comment]
Note to whoever completes this PR to include upstream [Forks](https://github.com/collinbarrett/FilterLists/wiki/Fork) and/or [Merges](https://github.com/collinbarrett/FilterLists/wiki/Merge).

**Comment by mkb2091** [comment]
Filter list ID and name according to API of lists incorporated into this list:

4: Hosts Blocking
21: Ransomware Tracker IP Blocklist
22: Ransomware Tracker Domain Blocklist
27: Privacy Filters
39: Latvian List
60: KADhosts
80: Unified Hosts
87: uAssets Unbreak
88: uAssets Privacy
89: uAssets Filters
91: uAssets Badware
115: The Hosts File Project Hosts
120: Ransomware Tracker URL Blocklist
140: Spam404
170: Adware Filters
198: ABPindo
202: ABP Japanese Paranoid Filters
203: ABP Japanese Filters
205: ABP Japanese 3rd Party SNS Filters
207: AakList (Anti-Adblock Killer)
215: Adblock Polska
222: AdBlockFarsi
226: AdAway
242: EasyPrivacy
252: Filtri DNS
272: Disconnect Tracking Filter List
274: Disconnect Malvertising Filter List
275: Disconnect Advertising Filter List
289: EasyList Italy
291: EasyList Hebrew
295: EasyList Dutch
300: EasyList China
301: EasyList
305: EasyList Czech and Slovak
308: NoCoin Hosts
317: Adserving and Tracking Domains
318: CoinMiner
321: Commonly Whitelisted Domains
325: Bjornstar's Hosts
348: VXVault
357: CoinBlocker Domains List
358: CoinBlocker Domains List Optional
364: Squid Blacklist Ad Servers and Trackers
366: Squid Blacklist Malicious
375: All-in-One Customized Adblock List
380: Toshiya's Filter List - Experimental
410: uAssets Resource Abuse
417: Referrer Spam Blacklist (Matomo)
422: Blocklist (ligyxy)
425: Semalt Blocked Domains
429: International List
438: PiHole Blocklist Session Replay
439: PiHole Blocklist SmartTV
440: PiHole Blocklist Android Tracking
442: Bill Stearns' Hosts
447: NoTrack Tracker Blocklist
448: NoTrack Malware Blocklist
449: WindowsSpyBlocker Hosts Spy
451: WindowsSpyBlocker Hosts Extra
512: MinerBlock Filters
514: Skeletal Blocker
595: Ads & Tracking
596: Tracking Aggressive
598: hostsVN
606: Goodbye Ads
618: Mandiant APT1 Report Appendix D
664: Adguard Mobile Ads (hosts)
666: Adguard Specific Apps (hosts)
667: Adguard DNS (hosts)
689: .pl-host-file
690: Suspicious Snooping Sniffing Hacking IP Addresses
691: Top Attacking IP Addresses Against Wordpress Sites
692: The Big List of Hacked Malware Web Sites
728: AdBlockID
733: Annoyance Mobile Ad hosts filter
817: Frellwit's Swedish Hosts File
858: abuse.ch URLhaus Malicious URL Blocklist (Domains)
861: Press the Attack
884: Adblock List for Finland
1278: Better content blocking rules
1474: Blah DNS Hosts whitelist
1475: hBlock Hosts
1490: Phishing Domain Database
1493: Greatis Anti-WebMiner
1498: Stop Google Analytics Ghost Spam Active List
1500: Cybercrime List
1557: DataMaster Android AdBlock Hosts
1665: abuse.ch URLhaus Malicious URL Blocklist (RPZ)

I'm not sure if they would be Forks or Merges and what the difference is

**Comment by collinbarrett** [comment]
Wow, that's helpful. I think we would classify your lists as "Merges". A "Fork" would be when somebody took a list and made a variant of it. A "Merge" is a list that combines/aggregates a collection of other lists. We don't do much with that data yet, but plan to. #287 , for example.

**Comment by collinbarrett** [comment]
Closed by #992. Won't be deployed to the production site until #1001 is resolved, however. I'll hopefully get that fixed soon.
