### ISSUE TITLE
htmlpreview.github.io or similar for TPL?

### ISSUE THREAD

**Issue by krystian3w** [collinbarrett/FilterLists#974]
<ul><li>

```
https://htmlpreview.github.io/?https://raw.githubusercontent.com/collinbarrett/FilterLists/master/data/TPLSubscriptionAssistant.html
```

<li>

```
https://raw.githack.com/collinbarrett/FilterLists/master/data/TPLSubscriptionAssistant.html
```

<li>

```
https://cdn.statically.io/gh/collinbarrett/FilterLists/master/data/TPLSubscriptionAssistant.html
```

</ul>

**Comment by DandelionSprout** [comment]
The latter two links work splendidly (The first one had IE's logger complain about absent element values)! I'll make a hotfix for it right away.

**Comment by krystian3w** [comment]
Maybe help add head for html file with meta tag:

https://www.w3schools.com/tags/att_meta_http_equiv.asp

**Comment by DandelionSprout** [comment]
That is a possibility, but at the time of writing the Githack (and Statically) link is 100% functional, so I went with that one for now.

**Comment by krystian3w** [comment]
As the backwards compatibility mode of IE5-7 doesn't borke any...?

https://en.wikipedia.org/wiki/Quirks_mode

**Comment by DandelionSprout** [comment]
Trying to use IE compatibility mode on non-intranet sites in 2019 would've been an extremely bad idea, so for one time's sake I'll have enough faith in the human species to assume they wouldn't do that.

**Comment by DandelionSprout** [comment]
That being said, even the Githack link seems to make the IE's logger recommend that I add `<!DOCTYPE html>` to the top of the file, though the absence of it doesn't seem to cause breakage.

**Comment by krystian3w** [comment]
You didn't understand me, this meta tag forces the html file with latest tribe to run.

Also https://www.w3schools.com/xml/xml_dtd_intro.asp should block run in Quirks_mode.

**Comment by DandelionSprout** [comment]
I can confirm that adding `<!DOCTYPE html>` did not cause any adverse effects as per https://raw.githack.com/DandelionSprout/FilterLists/patch-119/data/TPLSubscriptionAssistant.html, and that the use of Quirks Mode did not break the page in any known way.

So I'd say that #975 is ready for merging.

**Comment by krystian3w** [comment]
>  1) Save this file as an HTML file. (This can be done by e.g. right-clicking on the raw file and saving, or by pasting it into a notepad and saving it there.)

For this maybe add info about CDN or remove?

Title tag for better readable on tabs? https://www.w3schools.com/tags/tag_title.asp (in new line, under DTD, above first text).

**Comment by DandelionSprout** [comment]
I figured out just a minute after you did that the 4-step wasn't really needed anymore. 😅 

It took me 3 tests before I settled with w3schools' tree setup verbatim, but it seems to work now.

**Comment by collinbarrett** [comment]
Cool. Good work. Closing. Let me know if it should not be. Thanks!
