### ISSUE TITLE
wrong steven black url

### ISSUE THREAD

**Issue by jawz101** [collinbarrett/FilterLists#98]
Should be
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
not
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts

The one on your site has about 50 entries vs. the 36,000 or so entries in the real list.

**Comment by collinbarrett** [comment]
Thanks for the tip!

I think it's correct, though. There are two separate lists: [Unified Hosts](https://filterlists.com/#UnifiedHosts) and [Steven Black's Hosts](https://filterlists.com/#StevenBlacksHosts). The latter being just those hosts that the project itself has added (not from a 3rd-party source).

Closing for now, but please let me know if I am mistaken. Thanks!

**Comment by jawz101** [comment]
You're right.

BTW, thanks for making this.  I have a couple of other ramblings.
Have you checked out Firehol?
It's kinda the same idea but a library for all of the IP blocklists on the Interweb.
http://iplists.firehol.org/

I figure you and @ktsaou should become friends or something.

**Comment by collinbarrett** [comment]
Hey, thanks. No, I hadn't heard of that site. I'll check it out.
